"use client";
import { ArrowLeft, Check, Crown, CreditCard, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";

declare global { interface Window { liff?: {init(c:{liffId:string}):Promise<void>;isLoggedIn():boolean;login(c?:{redirectUri?:string}):void;getAccessToken():string|null} } }

function loadLiff(){return new Promise<void>((resolve,reject)=>{if(window.liff)return resolve();const script=document.createElement("script");script.src="https://static.line-scdn.net/liff/edge/2/sdk.js";script.onload=()=>resolve();script.onerror=()=>reject(new Error("LINE認証を読み込めませんでした"));document.head.appendChild(script)})}

export default function ResidentPage(){
 const [token,setToken]=useState(""),[status,setStatus]=useState<"loading"|"general"|"resident"|"error">("loading"),[message,setMessage]=useState(""),[submitting,setSubmitting]=useState(false);
 useEffect(()=>{let active=true;(async()=>{try{const config=await fetch("/api/v1/client-config").then(r=>r.json()),liffId=String(config.liffId??"");if(!liffId)throw new Error("LINE認証を準備できませんでした");await loadLiff();await window.liff!.init({liffId});if(!window.liff!.isLoggedIn()){window.liff!.login({redirectUri:location.href});return}const accessToken=window.liff!.getAccessToken();if(!accessToken)throw new Error("LINE認証を確認できませんでした");const response=await fetch("/api/v1/me/membership",{headers:{Authorization:`Bearer ${accessToken}`}});if(!response.ok)throw new Error("会員情報を確認できませんでした");const member=await response.json();if(!active)return;setToken(accessToken);setStatus(member.membershipType==="RESIDENT"?"resident":"general")}catch(error){if(active){setStatus("error");setMessage(error instanceof Error?error.message:"読み込みに失敗しました")}}})();return()=>{active=false}},[]);
 async function upgrade(){if(!token||submitting)return;setSubmitting(true);setMessage("");try{const response=await fetch("/api/v1/resident-upgrade",{method:"POST",headers:{Authorization:`Bearer ${token}`}}),result=await response.json();if(!response.ok)throw new Error(result.message??"申込画面を準備できませんでした");location.assign(result.checkoutUrl)}catch(error){setMessage(error instanceof Error?error.message:"申込画面を準備できませんでした")}finally{setSubmitting(false)}}
 return <main className="resident-shell"><header><button onClick={()=>location.href="/"} aria-label="会員証へ戻る"><ArrowLeft size={20}/></button><div><small>COMPASSION WORLD</small><h1>住民登録証</h1></div></header><section className="resident-hero"><Crown size={34}/><p>RESIDENT MEMBERSHIP</p><h2>COMPASSION WORLDを<br/>もっと身近な居場所に。</h2><span>住民登録を継続している間、会員証に「住民」と表示されます。</span></section>{status==="loading"?<section className="resident-status"><p>会員情報を確認しています…</p></section>:status==="resident"?<section className="resident-status active"><ShieldCheck size={30}/><h2>住民登録中です</h2><p>現在の会員証には住民資格が反映されています。</p><button onClick={()=>location.href="/"}>会員証へ戻る</button></section>:<><section className="resident-benefits"><h2>住民登録の特典</h2><article><Check/><div><strong>ゴールドランク以上を保証</strong><p>利用実績によるランクがゴールド未満でも、住民はゴールドからスタートします。</p></div></article><article><Check/><div><strong>会員証に「住民」を表示</strong><p>通常ランクとは別に、住民登録証として分かりやすく表示します。</p></div></article><article><Check/><div><strong>住民限定価格・サービス</strong><p>スタジオ料金など、対象サービスの住民特典を利用できます。</p></div></article></section><section className="resident-apply"><CreditCard size={25}/><div><small>MONTHLY MEMBERSHIP</small><h2>住民登録を申し込む</h2><p>現在利用しているStripeの申込画面へ進みます。月額料金へのポイント付与はありません。</p></div><button onClick={upgrade} disabled={submitting||status!=="general"}>{submitting?"申込画面を準備しています…":"住民登録へアップグレード"}</button>{message&&<p className="resident-message">{message}</p>}</section></>}</main>
}
