import {env} from "cloudflare:workers";
import {NextRequest} from "next/server";
import {auditReceipt,normalizeMemberCode,receiptBucket,receiptError,receiptId,receiptResponse,requireReceiptDevice,sourceHash,validRequestId} from "@/lib/receipt-api";
import {publicPurchase,purchaseByReceipt,purchaseItems} from "@/lib/receipt-view";

type Option={optionName?:unknown;optionPrice?:unknown};
type Item={productCode?:unknown;productName?:unknown;quantity?:unknown;unitPriceIncludingTax?:unknown;lineTotal?:unknown;taxRate?:unknown;options?:unknown};
type Body={requestId?:unknown;transactionId?:unknown;memberCode?:unknown;storeId?:unknown;storeName?:unknown;transactionDateTime?:unknown;status?:unknown;receiptMode?:unknown;currency?:unknown;items?:unknown;subtotal?:unknown;taxTotal?:unknown;totalIncludingTax?:unknown;pointsUsed?:unknown;paymentMethod?:unknown;paymentBreakdown?:unknown};
const modes=["PAPER","ELECTRONIC","NONE"],statuses=["PAYMENT_UNKNOWN","CONFIRMED"],paymentKeys=["cash","credit","electronicMoney","qr","points","other"];
const text=(value:unknown,max=160)=>typeof value==="string"?value.trim().slice(0,max):"";
const yen=(value:unknown)=>Number.isInteger(value)&&Number(value)>=0?Number(value):null;
function parseItems(value:unknown){if(!Array.isArray(value)||value.length===0||value.length>300)return null;const parsed=[];for(const raw of value as Item[]){const quantity=yen(raw.quantity),unitPriceIncludingTax=yen(raw.unitPriceIncludingTax),lineTotal=yen(raw.lineTotal),taxRate=yen(raw.taxRate),productCode=text(raw.productCode,80),productName=text(raw.productName,200);if(!productCode||!productName||!quantity||unitPriceIncludingTax===null||lineTotal===null||taxRate===null||taxRate>100)return null;const options=Array.isArray(raw.options)?raw.options.map((entry:Option)=>({optionName:text(entry.optionName,120),optionPrice:yen(entry.optionPrice)})).filter(entry=>entry.optionName&&entry.optionPrice!==null):[];parsed.push({productCode,productName,quantity,unitPriceIncludingTax,lineTotal,taxRate,options})}return parsed}
function parsePayment(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))return null;const result:Record<string,number>={};for(const key of paymentKeys){const amount=yen((value as Record<string,unknown>)[key]??0);if(amount===null)return null;result[key]=amount}return result}

export async function POST(request:NextRequest){const raw=await request.json().catch(()=>null) as Body|null,requestId=raw?.requestId,device=await requireReceiptDevice(request,"purchase:create");if(!device)return receiptError(401,"UNAUTHORIZED","端末認証に失敗しました",typeof requestId==="string"?requestId:undefined,false);if(!validRequestId(requestId))return receiptError(400,"INVALID_REQUEST","requestIdはUUIDで指定してください");
 const memberCode=normalizeMemberCode(raw?.memberCode),transactionId=text(raw?.transactionId,120),storeId=text(raw?.storeId,80),storeName=text(raw?.storeName,160),transactionDateTime=Date.parse(text(raw?.transactionDateTime,80)),status=text(raw?.status,30),receiptMode=text(raw?.receiptMode,30),currency=text(raw?.currency,3)||"JPY",items=parseItems(raw?.items),subtotal=yen(raw?.subtotal),taxTotal=yen(raw?.taxTotal),totalIncludingTax=yen(raw?.totalIncludingTax),pointsUsed=yen(raw?.pointsUsed??0),paymentMethod=text(raw?.paymentMethod,80),paymentBreakdown=parsePayment(raw?.paymentBreakdown);
 if(!/^[A-Z0-9]{10}$/.test(memberCode)||!transactionId||!storeId||!storeName||!Number.isFinite(transactionDateTime)||!statuses.includes(status)||!modes.includes(receiptMode)||currency!=="JPY"||!items||subtotal===null||taxTotal===null||totalIncludingTax===null||pointsUsed===null||!paymentMethod||!paymentBreakdown)return receiptError(400,"INVALID_REQUEST","取引情報の形式を確認してください",requestId,false);
 if(items.reduce((sum,item)=>sum+item.lineTotal,0)!==totalIncludingTax)return receiptError(422,"TOTAL_MISMATCH","商品明細の合計と税込合計が一致しません",requestId,false);
 if(Object.values(paymentBreakdown).reduce((sum,value)=>sum+value,0)!==totalIncludingTax)return receiptError(422,"PAYMENT_BREAKDOWN_MISMATCH","支払内訳と税込合計が一致しません",requestId,false);
 if(paymentBreakdown.points!==pointsUsed)return receiptError(422,"POINT_PAYMENT_MISMATCH","ポイント支払額が一致しません",requestId,false);
 if(totalIncludingTax>=50000&&receiptMode!=="ELECTRONIC")return receiptError(422,"ELECTRONIC_RECEIPT_REQUIRED","税込50,000円以上の取引は電子レシートが必須です",requestId,false);
 const canonical={transactionId,memberCode,storeId,storeName,transactionDateTime:new Date(transactionDateTime).toISOString(),status,receiptMode,currency,items,subtotal,taxTotal,totalIncludingTax,pointsUsed,paymentMethod,paymentBreakdown},hash=await sourceHash(canonical),existing=await env.DB.prepare("SELECT receipt_id AS receiptId,source_data_hash AS sourceDataHash FROM purchases WHERE transaction_id=? OR request_id=? LIMIT 1").bind(transactionId,requestId).first<{receiptId:string;sourceDataHash:string}>();
 if(existing){if(existing.sourceDataHash!==hash){await auditReceipt({actorType:"DEVICE",actorId:device.id,action:"PURCHASE_CREATE",receiptId:existing.receiptId,transactionId,deviceId:device.deviceId,result:"CONFLICT",reason:"SOURCE_DATA_HASH_MISMATCH"});return receiptError(409,"IDEMPOTENCY_CONFLICT","同じ取引IDまたはrequestIdに異なる内容が送信されました",requestId,false)}const row=await purchaseByReceipt(existing.receiptId);if(!row)return receiptError(503,"PURCHASE_UNAVAILABLE","購入履歴を確認できません",requestId,true);return receiptResponse({ok:true,idempotentReplay:true,purchase:publicPurchase(row,await purchaseItems(row.id))},200,{"X-Idempotent-Replay":"true"})}
 const member=await env.DB.prepare("SELECT id,status,verification_status AS verificationStatus FROM members WHERE member_code=? LIMIT 1").bind(memberCode).first<{id:string;status:string;verificationStatus:string}>();if(!member)return receiptError(404,"MEMBER_NOT_FOUND","会員が登録されていません",requestId,false);if(member.status!=="ACTIVE"||member.verificationStatus!=="ACTIVE")return receiptError(409,"MEMBER_INACTIVE","停止または退会済みの会員です",requestId,false);
 const id=crypto.randomUUID(),newReceiptId=receiptId(),now=Date.now(),confirmedAt=status==="CONFIRMED"?now:null,objectKey=receiptMode==="ELECTRONIC"?`electronic-receipts/${new Date(transactionDateTime).getUTCFullYear()}/${newReceiptId}/v1.json`:null,statements=[env.DB.prepare("INSERT INTO purchases(id,receipt_id,request_id,transaction_id,member_id,member_code_hash,store_id,store_name,transaction_date_time,status,receipt_mode,currency,subtotal,tax_total,total_including_tax,points_used,payment_method,payment_breakdown_json,receipt_version,source_data_hash,source_device_id,confirmed_at,cancelled_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,newReceiptId,requestId,transactionId,member.id,await sourceHash(memberCode),storeId,storeName,transactionDateTime,status,receiptMode,currency,subtotal,taxTotal,totalIncludingTax,pointsUsed,paymentMethod,JSON.stringify(paymentBreakdown),1,hash,device.deviceId,confirmedAt,null,now,now)];
 items.forEach((item,index)=>statements.push(env.DB.prepare("INSERT INTO purchase_items(id,purchase_id,line_number,product_code,product_name,quantity,unit_price_including_tax,line_total,tax_rate,options_json) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),id,index+1,item.productCode,item.productName,item.quantity,item.unitPriceIncludingTax,item.lineTotal,item.taxRate,JSON.stringify(item.options))));
 if(objectKey)statements.push(env.DB.prepare("INSERT INTO receipt_artifacts(id,purchase_id,version,object_key,content_type,source_data_hash,status,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),id,1,objectKey,"application/json",hash,"STORED",device.deviceId,now));
 try{if(objectKey)await receiptBucket().put(objectKey,JSON.stringify(canonical),{httpMetadata:{contentType:"application/json",cacheControl:"private, no-store"},customMetadata:{receiptId:newReceiptId,version:"1"}});await env.DB.batch(statements);await auditReceipt({actorType:"DEVICE",actorId:device.id,action:"PURCHASE_CREATE",receiptId:newReceiptId,transactionId,deviceId:device.deviceId,result:"SUCCESS"});const row=await purchaseByReceipt(newReceiptId);return receiptResponse({ok:true,idempotentReplay:false,purchase:publicPurchase(row!,await purchaseItems(id))},201)}catch(error){if(objectKey)await receiptBucket().delete(objectKey).catch(()=>undefined);console.error("purchase create failed",error instanceof Error?error.message:"UNKNOWN");return receiptError(503,"PURCHASE_WRITE_UNAVAILABLE","購入履歴を保存できませんでした",requestId,true)}
}
