import {env} from "cloudflare:workers";
import {NextRequest,NextResponse} from "next/server";
import {requireAdminSession} from "@/lib/admin-session";
import {getOrderProducts} from "@/lib/order-catalog";

const runtime=()=>env as unknown as Record<string,string|undefined>;
function headerAdmin(request:NextRequest){const email=request.headers.get("oai-authenticated-user-email")?.trim().toLowerCase(),allowed=(runtime().ADMIN_EMAILS??"").split(",").map(v=>v.trim().toLowerCase()).filter(Boolean);return email&&allowed.includes(email)?email:null}
async function actor(request:NextRequest){return headerAdmin(request)??await requireAdminSession(request)}
const safeCode=(value:unknown)=>String(value??"").trim().slice(0,64);
async function event(type:string,who:string,productCode:string|null,quantity:number|null,details:unknown={}){await env.DB.prepare("INSERT INTO inventory_events (id,event_type,product_code,quantity,details_json,actor,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),type,productCode,quantity,JSON.stringify(details),who,Date.now()).run()}
async function upstream(action:string,data:Record<string,unknown>={}){const settings=runtime(),url=settings.SMAREGI_INVENTORY_URL??settings.SMAREGI_SPEND_RECALC_URL,key=settings.SMAREGI_INVENTORY_KEY??settings.SMAREGI_SPEND_SYNC_KEY;if(!url||!key)return {configured:false,ok:false,error:"NOT_CONFIGURED"};try{const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,requestId:crypto.randomUUID(),syncKey:key,data}),signal:AbortSignal.timeout(12000)}),result=await response.json().catch(()=>({}));const payload=result?.result??result;return {configured:true,ok:response.ok&&result?.ok!==false,result:payload,error:response.ok&&result?.ok!==false?null:"UPSTREAM_FAILED"}}catch{return {configured:true,ok:false,error:"UPSTREAM_TIMEOUT"}}}

export async function GET(request:NextRequest){if(!await actor(request))return NextResponse.json({error:"UNAUTHORIZED"},{status:401});try{const refresh=request.nextUrl.searchParams.get("refresh")==="1";if(refresh){const sync=await upstream("inventory.list");if(sync.ok&&Array.isArray((sync.result as {stocks?:unknown[]})?.stocks)){const now=Date.now(),statements=((sync.result as {stocks:Record<string,unknown>[]}).stocks).slice(0,5000).map(row=>env.DB.prepare("INSERT INTO smaregi_stock_snapshots (product_code,product_id,store_id,stock_amount,layaway_stock_amount,source_updated_at,synced_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(product_code,store_id) DO UPDATE SET product_id=excluded.product_id,stock_amount=excluded.stock_amount,layaway_stock_amount=excluded.layaway_stock_amount,source_updated_at=excluded.source_updated_at,synced_at=excluded.synced_at").bind(safeCode(row.productCode),String(row.productId??""),String(row.storeId??""),Math.round(Number(row.stockAmount)||0),Math.round(Number(row.layawayStockAmount)||0),String(row.updDateTime??""),now));for(let index=0;index<statements.length;index+=100)await env.DB.batch(statements.slice(index,index+100))}}
 const [catalog,lots,stocks,count,events]=await Promise.all([getOrderProducts({includeOverrides:true,includeClosedProducts:true,allowSnapshotFallback:true}),env.DB.prepare("SELECT id,product_code AS productCode,product_name AS productName,received_quantity AS receivedQuantity,remaining_quantity AS remainingQuantity,expiry_date AS expiryDate,status,discount_rate AS discountRate,note,created_at AS createdAt,updated_at AS updatedAt FROM inventory_lots WHERE status<>'CLOSED' ORDER BY CASE WHEN expiry_date IS NULL THEN 1 ELSE 0 END,expiry_date,created_at DESC LIMIT 1000").all(),env.DB.prepare("SELECT product_code AS productCode,product_id AS productId,store_id AS storeId,stock_amount AS stockAmount,layaway_stock_amount AS layawayStockAmount,source_updated_at AS sourceUpdatedAt,synced_at AS syncedAt FROM smaregi_stock_snapshots ORDER BY product_code LIMIT 5000").all(),env.DB.prepare("SELECT id,status,started_by AS startedBy,started_at AS startedAt FROM inventory_counts WHERE status='OPEN' ORDER BY started_at DESC LIMIT 1").first(),env.DB.prepare("SELECT event_type AS eventType,product_code AS productCode,quantity,details_json AS detailsJson,actor,created_at AS createdAt FROM inventory_events ORDER BY created_at DESC LIMIT 50").all()]);
 let countItems:{results:unknown[]}={results:[]};if(count?.id)countItems=await env.DB.prepare("SELECT product_code AS productCode,product_name AS productName,expected_quantity AS expectedQuantity,counted_quantity AS countedQuantity,difference,note,updated_at AS updatedAt FROM inventory_count_items WHERE count_id=? ORDER BY product_name").bind(count.id).all();const configured=Boolean((runtime().SMAREGI_INVENTORY_URL??runtime().SMAREGI_SPEND_RECALC_URL)&&(runtime().SMAREGI_INVENTORY_KEY??runtime().SMAREGI_SPEND_SYNC_KEY));return NextResponse.json({configured,products:catalog.products.map(product=>({code:product.code,name:product.name,category:product.menuCategory,soldOut:product.soldOut,saleEndsAt:product.saleEndsAt??null})),lots:lots.results,stocks:stocks.results,count:count?{...count,items:countItems.results}:null,events:events.results},{headers:{"Cache-Control":"no-store"}})}catch(error){console.error("inventory read failed",error);return NextResponse.json({error:"INVENTORY_READ_FAILED"},{status:500})}}

export async function POST(request:NextRequest){const who=await actor(request);if(!who)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const body=await request.json().catch(()=>null) as Record<string,unknown>|null,action=String(body?.action??""),now=Date.now();if(!body)return NextResponse.json({error:"INVALID_INPUT"},{status:400});try{
 if(action==="RECEIVE"){const productCode=safeCode(body.productCode),productName=String(body.productName??"").trim().slice(0,120),quantity=Math.round(Number(body.quantity)||0),expiryDate=String(body.expiryDate??"").trim()||null;if(!productCode||!productName||quantity<1||quantity>100000||expiryDate&&!/^\d{4}-\d{2}-\d{2}$/.test(expiryDate))return NextResponse.json({error:"INVALID_INPUT"},{status:400});const id=crypto.randomUUID();await env.DB.batch([env.DB.prepare("INSERT INTO inventory_lots (id,product_code,product_name,received_quantity,remaining_quantity,expiry_date,status,discount_rate,note,created_by,created_at,updated_at) VALUES (?,?,?,?,?,?,'ACTIVE',0,?,?,?,?)").bind(id,productCode,productName,quantity,quantity,expiryDate,String(body.note??"").trim().slice(0,200),who,now,now),env.DB.prepare("INSERT INTO inventory_events (id,event_type,product_code,quantity,details_json,actor,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),"RECEIVED",productCode,quantity,JSON.stringify({lotId:id,expiryDate}),who,now)]);const sync=await upstream("inventory.add",{productCode,quantity});return NextResponse.json({ok:true,id,smaregi:sync.ok?"SYNCED":sync.configured?"FAILED":"WAITING"},{status:201})}
 if(action==="SET_DISCOUNT"){const id=String(body.id??""),rate=Math.max(0,Math.min(90,Math.round(Number(body.discountRate)||0)));const lot=await env.DB.prepare("SELECT product_code AS productCode FROM inventory_lots WHERE id=?").bind(id).first<{productCode:string}>();if(!lot)return NextResponse.json({error:"LOT_NOT_FOUND"},{status:404});await env.DB.prepare("UPDATE inventory_lots SET discount_rate=?,updated_at=? WHERE id=?").bind(rate,now,id).run();await event("DISCOUNT_CHANGED",who,lot.productCode,null,{lotId:id,discountRate:rate});return NextResponse.json({ok:true})}
 if(action==="START_COUNT"){const existing=await env.DB.prepare("SELECT id FROM inventory_counts WHERE status='OPEN' LIMIT 1").first();if(existing)return NextResponse.json({error:"COUNT_ALREADY_OPEN"},{status:409});const id=crypto.randomUUID(),stocks=await env.DB.prepare("SELECT product_code AS productCode,SUM(stock_amount-layaway_stock_amount) AS expected,MAX(product_id) AS productId FROM smaregi_stock_snapshots GROUP BY product_code").all<Record<string,unknown>>(),catalog=(await getOrderProducts({includeOverrides:true,includeClosedProducts:true,allowSnapshotFallback:true})).products,byCode=new Map(catalog.map(p=>[p.code,p.name]));await env.DB.prepare("INSERT INTO inventory_counts (id,status,started_by,started_at) VALUES (?,'OPEN',?,?)").bind(id,who,now).run();const statements=stocks.results.map(row=>env.DB.prepare("INSERT INTO inventory_count_items (count_id,product_code,product_name,expected_quantity,counted_quantity,difference,note,updated_at) VALUES (?,?,?,?,NULL,NULL,'',?)").bind(id,String(row.productCode),byCode.get(String(row.productCode))??String(row.productCode),Math.round(Number(row.expected)||0),now));for(let index=0;index<statements.length;index+=100)await env.DB.batch(statements.slice(index,index+100));await event("COUNT_STARTED",who,null,null,{countId:id,items:statements.length});return NextResponse.json({ok:true,id},{status:201})}
 if(action==="SAVE_COUNT"){const countId=String(body.countId??""),productCode=safeCode(body.productCode),counted=Math.max(0,Math.round(Number(body.countedQuantity)||0)),item=await env.DB.prepare("SELECT expected_quantity AS expected FROM inventory_count_items WHERE count_id=? AND product_code=?").bind(countId,productCode).first<{expected:number}>();if(!item)return NextResponse.json({error:"COUNT_ITEM_NOT_FOUND"},{status:404});await env.DB.prepare("UPDATE inventory_count_items SET counted_quantity=?,difference=?,note=?,updated_at=? WHERE count_id=? AND product_code=?").bind(counted,counted-item.expected,String(body.note??"").trim().slice(0,200),now,countId,productCode).run();return NextResponse.json({ok:true,difference:counted-item.expected})}
 if(action==="COMPLETE_COUNT"){const countId=String(body.countId??""),missing=await env.DB.prepare("SELECT COUNT(*) AS count FROM inventory_count_items WHERE count_id=? AND counted_quantity IS NULL").bind(countId).first<{count:number}>();if(Number(missing?.count??0)>0)return NextResponse.json({error:"COUNT_INCOMPLETE",missing:missing?.count},{status:409});const items=await env.DB.prepare("SELECT product_code AS productCode,counted_quantity AS countedQuantity,difference FROM inventory_count_items WHERE count_id=? AND difference<>0").bind(countId).all<Record<string,unknown>>(),sync=await upstream("inventory.bulk-adjust",{items:items.results});if(sync.configured&&!sync.ok)return NextResponse.json({error:"SMAREGI_ADJUST_FAILED"},{status:502});await env.DB.prepare("UPDATE inventory_counts SET status='COMPLETED',completed_by=?,completed_at=? WHERE id=? AND status='OPEN'").bind(who,now,countId).run();await event("COUNT_COMPLETED",who,null,null,{countId,differences:items.results.length,smaregi:sync.ok?"SYNCED":"WAITING"});return NextResponse.json({ok:true,differences:items.results.length,smaregi:sync.ok?"SYNCED":"WAITING"})}
 return NextResponse.json({error:"INVALID_ACTION"},{status:400})
 }catch(error){console.error("inventory write failed",error);return NextResponse.json({error:"INVENTORY_WRITE_FAILED"},{status:500})}}
