import{NextRequest,NextResponse}from"next/server";
import{getDb}from"@/db";
import{categorySchedules}from"@/db/schema";
import{requireKitchenToken}from"@/lib/kitchen-api";

const categories=["food-tsukemen","food-udon","food-pasta","food-don","food-side","dessert","soft-cafe","soft-simple","soft-mocktail","alcohol-main","alcohol-cocktail"] as const;
const time=/^(?:[01]\d|2[0-3]):[0-5]\d$/;
const defaults=()=>categories.map(category=>({category,enabled:category==="food-don",startTime:"11:30",endTime:"21:30",days:category==="food-don"?[6,7]:[1,2,3,4,5,6,7],note:category==="food-don"?"平日は炊飯しない運用":""}));

export async function GET(request:NextRequest){if(!await requireKitchenToken(request))return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const rows=await getDb().select().from(categorySchedules),saved=new Map(rows.map(row=>[row.category,row]));return NextResponse.json({schedules:defaults().map(item=>{const row=saved.get(item.category);return row?{...row,days:row.days.split(",").map(Number)}:item})},{headers:{"Cache-Control":"no-store"}})}
export async function PUT(request:NextRequest){if(!await requireKitchenToken(request))return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const body=await request.json().catch(()=>null)as{schedules?:unknown}|null;if(!Array.isArray(body?.schedules)||body.schedules.length!==categories.length)return NextResponse.json({error:"INVALID_SCHEDULES"},{status:400});const seen=new Set<string>(),now=new Date(),statements=[];for(const value of body.schedules as Record<string,unknown>[]){const category=String(value.category??""),days=Array.isArray(value.days)?[...new Set(value.days.map(Number).filter(day=>day>=1&&day<=7))].sort():[];if(!categories.includes(category as typeof categories[number])||seen.has(category)||!time.test(String(value.startTime??""))||!time.test(String(value.endTime??""))||String(value.startTime)>=String(value.endTime)||!days.length)return NextResponse.json({error:"INVALID_SCHEDULE"},{status:400});seen.add(category);const fields={category,enabled:value.enabled===true,startTime:String(value.startTime),endTime:String(value.endTime),days:days.join(","),note:String(value.note??"").trim().slice(0,120),updatedBy:"kitchen-monitor",updatedAt:now};statements.push(getDb().insert(categorySchedules).values(fields).onConflictDoUpdate({target:categorySchedules.category,set:fields}))}await getDb().batch(statements);return GET(request)}
