import { NextRequest,NextResponse } from "next/server";
import { getDb } from "@/db";
import { storeHours } from "@/db/schema";
import { requireKitchenToken } from "@/lib/kitchen-api";

const defaults={id:"AOZORA_KITCHEN",enabled:true,timezone:"Asia/Tokyo",openTime:"11:30",closeTime:"22:00",orderStart:"11:30",lastOrder:"21:30",businessDays:"2,3,4,5,6,7",lunchEnabled:true,lunchStart:"11:30",lunchEnd:"14:00",lunchLastOrder:"13:30",lunchDays:"2,3,4,5,6,7",dinnerEnabled:true,dinnerStart:"17:30",dinnerEnd:"22:00",dinnerLastOrder:"21:30",dinnerDays:"6",eventDinnerEnabled:true};
const time=(value:unknown,fallback:string)=>typeof value==="string"&&/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(value)?value:fallback;
const days=(value:unknown,fallback:string)=>{const list=Array.isArray(value)?value.map(Number).filter(day=>day>=1&&day<=7):[];return[...new Set(list)].sort().join(",")||fallback};
const exposed=(row:typeof storeHours.$inferSelect|typeof defaults)=>({...row,lunchDays:String(row.lunchDays).split(",").map(Number),dinnerDays:String(row.dinnerDays).split(",").map(Number)});

export async function GET(request:NextRequest){if(!await requireKitchenToken(request))return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const[saved]=await getDb().select().from(storeHours).limit(1);return NextResponse.json({hours:exposed(saved??defaults)},{headers:{"Cache-Control":"no-store"}})}
export async function PUT(request:NextRequest){if(!await requireKitchenToken(request))return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const body=await request.json().catch(()=>null)as Record<string,unknown>|null;if(!body)return NextResponse.json({error:"INVALID_INPUT"},{status:400});const values={id:defaults.id,enabled:body.enabled!==false,timezone:"Asia/Tokyo",openTime:time(body.lunchStart,defaults.lunchStart),closeTime:time(body.dinnerEnd,defaults.dinnerEnd),orderStart:time(body.lunchStart,defaults.lunchStart),lastOrder:time(body.dinnerLastOrder,defaults.dinnerLastOrder),businessDays:days(body.lunchDays,defaults.businessDays),lunchEnabled:body.lunchEnabled!==false,lunchStart:time(body.lunchStart,defaults.lunchStart),lunchEnd:time(body.lunchEnd,defaults.lunchEnd),lunchLastOrder:time(body.lunchLastOrder,defaults.lunchLastOrder),lunchDays:days(body.lunchDays,defaults.lunchDays),dinnerEnabled:body.dinnerEnabled!==false,dinnerStart:time(body.dinnerStart,defaults.dinnerStart),dinnerEnd:time(body.dinnerEnd,defaults.dinnerEnd),dinnerLastOrder:time(body.dinnerLastOrder,defaults.dinnerLastOrder),dinnerDays:days(body.dinnerDays,defaults.dinnerDays),eventDinnerEnabled:body.eventDinnerEnabled!==false,updatedBy:"KITCHEN_MONITOR",updatedAt:new Date()};await getDb().insert(storeHours).values(values).onConflictDoUpdate({target:storeHours.id,set:values});return NextResponse.json({hours:exposed(values)})}
