"use client";
import {useEffect,useMemo,useState} from "react";
import {GripVertical,Search} from "lucide-react";
import type {MasterProduct} from "./MasterCatalogPanel";

export function OmohideLayoutManager(){
 const [products,setProducts]=useState<MasterProduct[]>([]),[open,setOpen]=useState(false),[query,setQuery]=useState(""),[order,setOrder]=useState<string[]>([]),[dragged,setDragged]=useState(""),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 const load=async()=>{const response=await fetch("/api/v1/admin/inventory/master",{cache:"no-store",signal:AbortSignal.timeout(10000)});if(response.ok){const result=await response.json(),rows:MasterProduct[]=result.products??[];setProducts(rows);setOrder(rows.filter(p=>Number(p.omohideDisplay)===1).sort((a,b)=>Number(a.omohideSequence??999999)-Number(b.omohideSequence??999999)||a.productName.localeCompare(b.productName,"ja")).map(p=>p.productCode))}};
 useEffect(()=>{void load()},[]);
 const included=useMemo(()=>order.map(code=>products.find(p=>p.productCode===code)).filter((p):p is MasterProduct=>Boolean(p)),[order,products]);
 const candidates=useMemo(()=>products.filter(p=>!order.includes(p.productCode)&&(!query||`${p.productName} ${p.productCode} ${p.categoryName}`.toLowerCase().includes(query.toLowerCase()))).slice(0,40),[products,order,query]);
 const saveProduct=async(product:MasterProduct,show:boolean)=>{setBusy(product.productCode);setMessage("表示設定を保存しています…");try{const response=await fetch("/api/v1/admin/catalog",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({productCode:product.productCode,menuCategory:"retail",omohideDisplay:show,omohideSequence:show?(order.length+1)*10:null}),signal:AbortSignal.timeout(18000)});if(!response.ok)throw new Error();setOrder(current=>show?[...current,product.productCode]:current.filter(code=>code!==product.productCode));setMessage(show?`${product.productName}を「バーコードのない商品」に追加しました`:`${product.productName}を掲載対象から外しました`);await load()}catch{setMessage("表示設定を保存できませんでした")}finally{setBusy("")}};
 const drop=async(target:string)=>{if(!dragged||dragged===target)return;const next=[...order],from=next.indexOf(dragged),to=next.indexOf(target);next.splice(from,1);next.splice(to,0,dragged);setOrder(next);setDragged("");setBusy("ORDER");setMessage("並び順を保存しています…");try{const response=await fetch("/api/v1/admin/catalog",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({omohideOrder:next}),signal:AbortSignal.timeout(18000)});if(!response.ok)throw new Error();setMessage("おもひで商店の並び順を保存しました")}catch{setMessage("並び順を保存できませんでした")}finally{setBusy("")}};
 return <section className="omohide-layout-manager"><header><div><small>OMOHIDE SELF REGISTER</small><h2>おもひで商店 レイアウト管理</h2><p>セルフレジの「バーコードのない商品」へ掲載する商品と表示順を管理します。</p></div><button onClick={()=>setOpen(value=>!value)}>{open?"閉じる":"レイアウトを編集"}</button></header>{open&&<div className="omohide-layout-body"><div className="omohide-layout-column"><h3>掲載中（{included.length}件）</h3><p>カードをドラッグして並び替えられます。</p>{included.map(product=><article key={product.productCode} draggable onDragStart={()=>setDragged(product.productCode)} onDragOver={event=>event.preventDefault()} onDrop={()=>void drop(product.productCode)}><GripVertical size={17}/>{product.imageUrl?<img src={product.imageUrl} alt=""/>:<span className="omohide-no-image">画像なし</span>}<div><strong>{product.productName}</strong><small>{product.productCode}／{product.categoryName}</small></div><button disabled={Boolean(busy)} onClick={()=>void saveProduct(product,false)}>掲載を外す</button></article>)}</div><div className="omohide-layout-column"><h3>商品を追加</h3><label className="omohide-search"><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="商品名・コード・部門で検索"/></label>{candidates.map(product=><article key={product.productCode}>{product.imageUrl?<img src={product.imageUrl} alt=""/>:<span className="omohide-no-image">画像なし</span>}<div><strong>{product.productName}</strong><small>{product.productCode}／{product.categoryName}</small></div><button disabled={Boolean(busy)} onClick={()=>void saveProduct(product,true)}>{busy===product.productCode?"保存中…":"表示する"}</button></article>)}</div></div>}{message&&<p className="admin-global-message" role="status">{message}</p>}</section>
}
