"use client";
import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, CircleAlert, CircleCheck, Clock3, Database, GripVertical, Image as ImageIcon, LoaderCircle, RefreshCw, Save, Search, Smartphone, Store, Tags } from "lucide-react";
import {ProductMasterEditor,ProductMasterRegistration} from "./ProductMasterRegistration";
import {ProductMasterWorkspace} from "./ProductMasterWorkspace";
import {jstMonthInput} from "../../lib/jst-date";

type Product={id:string;code:string;name:string;price:number;basePrice:number;taxRate:number;category:"FOOD"|"DRINK";menuCategory:string;description:string;imageUrl:string;soldOut:boolean;displaySequence:number;showOnSelfRegister:boolean;showOnMobileOrder:boolean;scheduleEnabled:boolean;scheduleStart:string;scheduleEnd:string;scheduleDays:number[];saleStartsAt:number|null;saleEndsAt:number|null;hasOverride:boolean};
type Hours={enabled:boolean;lunchEnabled:boolean;lunchStart:string;lunchEnd:string;lunchLastOrder:string;lunchDays:number[];dinnerEnabled:boolean;dinnerStart:string;dinnerEnd:string;dinnerLastOrder:string;dinnerDays:number[];eventDinnerEnabled:boolean};
type Exception={date:string;status:"DEFAULT"|"CLOSED"|"CUSTOM"|"EVENT"|"CONTINUOUS";lunchEnabled:boolean;dinnerEnabled:boolean;lunchStart:string;lunchEnd:string;dinnerStart:string;dinnerEnd:string;continuousStart:string;continuousEnd:string;continuousLastOrder:string;note:string};
type CategorySchedule={category:string;enabled:boolean;startTime:string;endTime:string;days:number[];note:string};
type SaveState="IDLE"|"SAVING"|"SAVED"|"ERROR";
const categories=["food-tsukemen","food-udon","food-pasta","food-don","food-side","soft-cafe","soft-simple","soft-mocktail","alcohol-main","alcohol-cocktail","dessert"];
const categoryLabels:Record<string,string>={"food-tsukemen":"つけ麺","food-udon":"うどん・ほうとう","food-pasta":"パスタ","food-don":"ご飯もの","food-side":"サイド","soft-cafe":"カフェ","soft-simple":"ソフトドリンク","soft-mocktail":"モクテル","alcohol-main":"アルコール","alcohol-cocktail":"カクテル",dessert:"デザート"};
const weekdays=[[1,"月"],[2,"火"],[3,"水"],[4,"木"],[5,"金"],[6,"土"],[7,"日"]] as const;
const defaultHours:Hours={enabled:true,lunchEnabled:true,lunchStart:"11:30",lunchEnd:"14:00",lunchLastOrder:"13:30",lunchDays:[2,3,4,5,6,7],dinnerEnabled:true,dinnerStart:"17:30",dinnerEnd:"22:00",dinnerLastOrder:"21:30",dinnerDays:[6],eventDinnerEnabled:true};
const toggle=(list:number[],day:number)=>list.includes(day)?list.filter(value=>value!==day):[...list,day].sort();
const headers={"X-Compass-Preview":"representative"};

export default function MenuAdminPage(){
 const [products,setProducts]=useState<Product[]>([]),[selected,setSelected]=useState(""),[query,setQuery]=useState(""),[category,setCategory]=useState("ALL"),[view,setView]=useState<"MASTER"|"PRODUCTS"|"CATEGORIES"|"HOURS">("MASTER"),[dragged,setDragged]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[masterConfigured,setMasterConfigured]=useState(false),[hoursSaveState,setHoursSaveState]=useState<SaveState>("IDLE"),[hours,setHours]=useState<Hours>(defaultHours),[exceptions,setExceptions]=useState<Exception[]>([]),[month,setMonth]=useState(jstMonthInput),[selectedDate,setSelectedDate]=useState(""),[categorySchedules,setCategorySchedules]=useState<CategorySchedule[]>([]);
 const normalize=(p:Product):Product=>({...p,scheduleEnabled:p.scheduleEnabled??false,scheduleStart:p.scheduleStart??"11:30",scheduleEnd:p.scheduleEnd??"14:00",scheduleDays:p.scheduleDays??[1,2,3,4,5,6,7],saleStartsAt:p.saleStartsAt??null,saleEndsAt:p.saleEndsAt??null});
 const load=()=>Promise.all([fetch("/api/v1/admin/catalog",{headers}).then(r=>r.json()),fetch("/api/v1/admin/store-hours",{headers}).then(r=>r.json()),fetch("/api/v1/admin/category-schedules",{headers}).then(r=>r.json()),fetch("/api/v1/admin/product-master",{headers}).then(r=>r.json())]).then(([catalog,hourData,schedules,master])=>{const rows=(catalog.products??[]).map(normalize);setProducts(rows);if(!selected&&rows[0])setSelected(rows[0].code);if(hourData.hours)setHours({...defaultHours,...hourData.hours});setExceptions(hourData.exceptions??[]);setCategorySchedules(schedules.schedules??[]);setMasterConfigured(Boolean(master.configured))}).catch(()=>setMessage("管理情報を取得できませんでした"));
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>products.filter(p=>(category==="ALL"||p.menuCategory===category)&&(!query||`${p.name} ${p.code}`.toLowerCase().includes(query.toLowerCase()))),[products,category,query]);
 const current=products.find(p=>p.code===selected);
 const patchProduct=(values:Partial<Product>)=>setProducts(rows=>rows.map(row=>row.code===selected?{...row,...values}:row));
 async function saveProduct(){if(!current)return;setSaving(true);const response=await fetch("/api/v1/admin/catalog",{method:"PUT",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify({...current,productCode:current.code})});setMessage(response.ok?"商品設定を保存しました":"保存できませんでした");setSaving(false)}
 async function reorder(target:string){if(!dragged||dragged===target)return;const next=[...products],from=next.findIndex(p=>p.code===dragged),to=next.findIndex(p=>p.code===target);const [moved]=next.splice(from,1);next.splice(to,0,moved);const ordered=next.map((p,index)=>({...p,displaySequence:(index+1)*10}));setProducts(ordered);setDragged("");const response=await fetch("/api/v1/admin/catalog",{method:"PUT",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify({order:ordered.map(p=>p.code)})});setMessage(response.ok?"表示順を保存しました":"並び順を保存できませんでした")}
 const patchHours=(values:Partial<Hours>)=>{setHours(current=>({...current,...values}));setHoursSaveState("IDLE")};
 async function saveHours(){if(hoursSaveState==="SAVING")return;setHoursSaveState("SAVING");setMessage("");try{const response=await fetch("/api/v1/admin/store-hours",{method:"PUT",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify(hours)});if(!response.ok)throw new Error("save failed");setHoursSaveState("SAVED");setMessage("基本営業時間を保存しました")}catch{setHoursSaveState("ERROR");setMessage("基本営業時間を保存できませんでした")}}
 const activeException=exceptions.find(item=>item.date===selectedDate)??{date:selectedDate,status:"DEFAULT" as const,lunchEnabled:true,dinnerEnabled:false,lunchStart:hours.lunchStart,lunchEnd:hours.lunchEnd,dinnerStart:hours.dinnerStart,dinnerEnd:hours.dinnerEnd,continuousStart:hours.lunchStart,continuousEnd:hours.dinnerEnd,continuousLastOrder:hours.dinnerLastOrder,note:""};
 async function saveException(values:Exception){const response=await fetch("/api/v1/admin/store-hours",{method:"PUT",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify({...values,kind:"EXCEPTION"})});if(response.ok){setExceptions(rows=>[...rows.filter(row=>row.date!==values.date),values]);setMessage(`${values.date}の営業設定を保存しました`)}}
 const calendarDays=useMemo(()=>{const [year,mon]=month.split("-").map(Number),first=new Date(year,mon-1,1),last=new Date(year,mon,0),lead=first.getDay();return [...Array(lead).fill(null),...Array.from({length:last.getDate()},(_,index)=>`${month}-${String(index+1).padStart(2,"0")}`)] as (string|null)[]},[month]);
 return <main className="catalog-admin">
  <header><div><small>COMPASSION WORLD / MENU CONTROL</small><h1>共通メニュー管理</h1></div><button onClick={load}><RefreshCw size={16}/>最新情報へ更新</button></header>
  <nav className="admin-view-tabs"><button className={view==="MASTER"?"active":""} onClick={()=>setView("MASTER")}><Database size={16}/>商品マスタ</button><button className={view==="PRODUCTS"?"active":""} onClick={()=>setView("PRODUCTS")}><Store size={16}/>メニュー・並び順</button><button className={view==="CATEGORIES"?"active":""} onClick={()=>setView("CATEGORIES")}><Tags size={16}/>ジャンル時間</button><button className={view==="HOURS"?"active":""} onClick={()=>setView("HOURS")}><CalendarDays size={16}/>営業時間・カレンダー</button></nav>
  {message&&<p className="admin-global-message">{message}</p>}
  {view==="MASTER"&&<><ProductMasterRegistration onCreated={load}/><ProductMasterWorkspace/></>}
  {view==="PRODUCTS"&&<><section className="catalog-toolbar"><label><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="商品名・コードで検索"/></label><div><button className={category==="ALL"?"active":""} onClick={()=>setCategory("ALL")}>すべて</button>{categories.map(key=><button key={key} className={category===key?"active":""} onClick={()=>setCategory(key)}>{categoryLabels[key]}</button>)}</div></section><div className="menu-admin-board"><section className="sortable-product-grid">{filtered.map(p=><article key={p.code} draggable onDragStart={()=>setDragged(p.code)} onDragOver={event=>event.preventDefault()} onDrop={()=>reorder(p.code)} className={`${selected===p.code?"selected":""} ${dragged===p.code?"dragging":""}`} onClick={()=>setSelected(p.code)}><span className="drag-handle"><GripVertical size={16}/></span>{p.imageUrl?<span className="admin-product-image"><img src={p.imageUrl} alt=""/></span>:<span className="admin-product-image empty"><ImageIcon/></span>}<div><small>{categoryLabels[p.menuCategory]??p.menuCategory}</small><strong>{p.name}</strong><b>税抜主表示対象</b></div><em>{p.displaySequence}</em></article>)}</section>{current&&<aside className="quick-product-editor"><small>{current.code}</small><h2>{current.name}</h2><label>画像URL<input value={current.imageUrl} onChange={e=>patchProduct({imageUrl:e.target.value})}/></label><label>商品説明<textarea rows={3} value={current.description} onChange={e=>patchProduct({description:e.target.value})}/></label><div className="editor-switch"><span>セルフレジ掲載</span><input type="checkbox" checked={current.showOnSelfRegister} onChange={e=>patchProduct({showOnSelfRegister:e.target.checked})}/></div><div className="editor-switch"><span>モバイル掲載</span><input type="checkbox" checked={current.showOnMobileOrder} onChange={e=>patchProduct({showOnMobileOrder:e.target.checked})}/></div><div className="editor-switch"><span>売り切れ</span><input type="checkbox" checked={current.soldOut} onChange={e=>patchProduct({soldOut:e.target.checked})}/></div><div className="editor-switch"><span>個別販売時間で上書き</span><input type="checkbox" checked={current.scheduleEnabled} onChange={e=>patchProduct({scheduleEnabled:e.target.checked})}/></div>{current.scheduleEnabled&&<><div className="schedule-time-row"><label>開始<input type="time" value={current.scheduleStart} onChange={e=>patchProduct({scheduleStart:e.target.value})}/></label><label>終了<input type="time" value={current.scheduleEnd} onChange={e=>patchProduct({scheduleEnd:e.target.value})}/></label></div><Weekdays value={current.scheduleDays} onChange={days=>patchProduct({scheduleDays:days})}/></>}<button className="catalog-save" onClick={saveProduct} disabled={saving}><Save size={16}/>商品設定を保存</button><ProductMasterEditor product={current} configured={masterConfigured} onUpdated={load}/></aside>}</div></>}
  {view==="CATEGORIES"&&<CategorySchedules values={categorySchedules} onChange={setCategorySchedules} onMessage={setMessage}/>}
  {view==="HOURS"&&<section className="business-management"><div className="weekly-hours"><h2>基本営業時間</h2><p>通常週の営業時間です。月別カレンダーの設定が優先されます。</p><ServicePeriod title="ランチ" enabled={hours.lunchEnabled} start={hours.lunchStart} end={hours.lunchEnd} lastOrder={hours.lunchLastOrder} days={hours.lunchDays} onChange={values=>patchHours({lunchEnabled:values.enabled,lunchStart:values.start,lunchEnd:values.end,lunchLastOrder:values.lastOrder,lunchDays:values.days})}/><ServicePeriod title="ディナー" enabled={hours.dinnerEnabled} start={hours.dinnerStart} end={hours.dinnerEnd} lastOrder={hours.dinnerLastOrder} days={hours.dinnerDays} onChange={values=>patchHours({dinnerEnabled:values.enabled,dinnerStart:values.start,dinnerEnd:values.end,dinnerLastOrder:values.lastOrder,dinnerDays:values.days})}/><label className="event-dinner"><span><b>イベント実施日はディナー営業</b><small>カレンダーで「イベント営業」を選んだ日に適用</small></span><input type="checkbox" checked={hours.eventDinnerEnabled} onChange={e=>patchHours({eventDinnerEnabled:e.target.checked})}/></label><div className="save-action"><button className="catalog-save" onClick={saveHours} disabled={hoursSaveState==="SAVING"}>{hoursSaveState==="SAVING"?<LoaderCircle className="save-spinner" size={16}/>:hoursSaveState==="SAVED"?<CircleCheck size={16}/>:hoursSaveState==="ERROR"?<CircleAlert size={16}/>:<Save size={16}/>} {hoursSaveState==="SAVING"?"保存しています…":hoursSaveState==="SAVED"?"保存済み":"基本営業時間を保存"}</button><p className={`inline-save-status ${hoursSaveState.toLowerCase()}`} role="status" aria-live="polite">{hoursSaveState==="SAVING"?"基本営業時間を保存しています。画面を閉じずにお待ちください。":hoursSaveState==="SAVED"?"保存しました。再読み込み後も設定が反映されます。":hoursSaveState==="ERROR"?"保存できませんでした。通信を確認して、もう一度お試しください。":"変更後はこのボタンで保存してください。"}</p></div></div><div className="calendar-manager"><div className="calendar-head"><div><small>MONTHLY BUSINESS CALENDAR</small><h2>月別営業カレンダー</h2></div><input type="month" value={month} onChange={e=>{setMonth(e.target.value);setSelectedDate("")}}/></div><div className="calendar-week"><span>日</span><span>月</span><span>火</span><span>水</span><span>木</span><span>金</span><span>土</span></div><div className="business-calendar-grid">{calendarDays.map((date,index)=>date?<button key={date} onClick={()=>setSelectedDate(date)} className={`${selectedDate===date?"selected":""} ${exceptions.find(item=>item.date===date)?.status.toLowerCase()??""}`}><b>{Number(date.slice(-2))}</b><small>{exceptions.find(item=>item.date===date)?.status==="CLOSED"?"休業":exceptions.find(item=>item.date===date)?.status==="CONTINUOUS"?"通し":exceptions.find(item=>item.date===date)?.status==="EVENT"?"イベント":exceptions.find(item=>item.date===date)?.status==="CUSTOM"?"変更":"通常"}</small></button>:<span key={`blank-${index}`}/>)}</div>{selectedDate&&<ExceptionEditor value={activeException} onSave={saveException}/>}</div></section>}
 </main>
}

function Weekdays({value,onChange}:{value:number[];onChange:(days:number[])=>void}){return <div className="weekday-picker compact"><b>曜日</b><div>{weekdays.map(([day,label])=><button type="button" key={day} className={value.includes(day)?"active":""} onClick={()=>onChange(toggle(value,day))}>{label}</button>)}</div></div>}
function ServicePeriod({title,enabled,start,end,lastOrder,days,onChange}:{title:string;enabled:boolean;start:string;end:string;lastOrder:string;days:number[];onChange:(value:{enabled:boolean;start:string;end:string;lastOrder:string;days:number[]})=>void}){return <article className="service-period"><header><h3>{title}</h3><input type="checkbox" checked={enabled} onChange={e=>onChange({enabled:e.target.checked,start,end,lastOrder,days})}/></header><div><label>開始<input type="time" value={start} onChange={e=>onChange({enabled,start:e.target.value,end,lastOrder,days})}/></label><label>終了<input type="time" value={end} onChange={e=>onChange({enabled,start,end:e.target.value,lastOrder,days})}/></label><label>ラストオーダー<input type="time" value={lastOrder} onChange={e=>onChange({enabled,start,end,lastOrder:e.target.value,days})}/></label></div><Weekdays value={days} onChange={next=>onChange({enabled,start,end,lastOrder,days:next})}/></article>}
function ExceptionEditor({value,onSave}:{value:Exception;onSave:(value:Exception)=>void}){const [draft,setDraft]=useState(value);useEffect(()=>setDraft(value),[value.date]);return <section className="exception-editor"><h3>{value.date} の営業設定</h3><div className="exception-types">{[["DEFAULT","通常"],["CLOSED","臨時休業"],["CONTINUOUS","通し営業"],["CUSTOM","時間変更"],["EVENT","イベント営業"]].map(([key,label])=><button key={key} className={draft.status===key?"active":""} onClick={()=>setDraft({...draft,status:key as Exception["status"],dinnerEnabled:key==="EVENT"?true:draft.dinnerEnabled})}>{label}</button>)}</div>{draft.status==="CONTINUOUS"?<div className="continuous-period"><label>営業開始<input type="time" value={draft.continuousStart} onChange={e=>setDraft({...draft,continuousStart:e.target.value})}/></label><label>営業終了<input type="time" value={draft.continuousEnd} onChange={e=>setDraft({...draft,continuousEnd:e.target.value})}/></label><label>ラストオーダー<input type="time" value={draft.continuousLastOrder} onChange={e=>setDraft({...draft,continuousLastOrder:e.target.value})}/></label></div>:draft.status!=="CLOSED"&&draft.status!=="DEFAULT"&&<div className="exception-periods"><label><input type="checkbox" checked={draft.lunchEnabled} onChange={e=>setDraft({...draft,lunchEnabled:e.target.checked})}/>ランチ</label><input type="time" value={draft.lunchStart} onChange={e=>setDraft({...draft,lunchStart:e.target.value})}/><input type="time" value={draft.lunchEnd} onChange={e=>setDraft({...draft,lunchEnd:e.target.value})}/><label><input type="checkbox" checked={draft.dinnerEnabled} onChange={e=>setDraft({...draft,dinnerEnabled:e.target.checked})}/>ディナー</label><input type="time" value={draft.dinnerStart} onChange={e=>setDraft({...draft,dinnerStart:e.target.value})}/><input type="time" value={draft.dinnerEnd} onChange={e=>setDraft({...draft,dinnerEnd:e.target.value})}/></div>}<label>備考<input value={draft.note} onChange={e=>setDraft({...draft,note:e.target.value})} placeholder="イベント名、貸切など"/></label><button className="catalog-save" onClick={()=>onSave(draft)}><Save size={15}/>この日の設定を保存</button></section>}
function CategorySchedules({values,onChange,onMessage}:{values:CategorySchedule[];onChange:(values:CategorySchedule[])=>void;onMessage:(message:string)=>void}){const rows=categories.map(category=>values.find(row=>row.category===category)??{category,enabled:category==="food-don",startTime:"11:30",endTime:"14:00",days:category==="food-don"?[6,7]:[1,2,3,4,5,6,7],note:category==="food-don"?"お米使用メニューは土日限定":""});const patch=(category:string,values:Partial<CategorySchedule>)=>onChange(rows.map(row=>row.category===category?{...row,...values}:row));const save=async(row:CategorySchedule)=>{const response=await fetch("/api/v1/admin/category-schedules",{method:"PUT",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify(row)});onMessage(response.ok?`${categoryLabels[row.category]}の販売時間を保存しました`:"保存できませんでした")};return <section className="category-schedule-list"><header><small>CATEGORY AVAILABILITY</small><h2>ジャンルタブ別の販売時間</h2><p>ジャンル設定を基本とし、商品個別設定がある場合は個別設定を優先します。</p></header>{rows.map(row=><article key={row.category}><div className="category-schedule-title"><span><Tags/><b>{categoryLabels[row.category]}</b></span><input type="checkbox" checked={row.enabled} onChange={e=>patch(row.category,{enabled:e.target.checked})}/></div>{row.enabled&&<><div className="schedule-time-row"><label>販売開始<input type="time" value={row.startTime} onChange={e=>patch(row.category,{startTime:e.target.value})}/></label><label>販売終了<input type="time" value={row.endTime} onChange={e=>patch(row.category,{endTime:e.target.value})}/></label></div><Weekdays value={row.days} onChange={days=>patch(row.category,{days})}/><label>メモ<input value={row.note} onChange={e=>patch(row.category,{note:e.target.value})}/></label></>}<button onClick={()=>save(row)}><Save size={14}/>保存</button></article>)}</section>}
