import {env} from "cloudflare:workers";
import {NextRequest,NextResponse} from "next/server";
import {requireAdminSession} from "@/lib/admin-session";

const runtime=()=>env as unknown as Record<string,string|undefined>;
const foodCategories=new Set(["インスタント食品","おつまみ・間食","スナック菓子・チョコレート菓子・袋飴","ソフトドリンク(リサイクル容器)","ソフトドリンク(リターナブル容器)","テイクアウトドリンク","テイクアウトフード","栄養ドリンク・エナジードリンク","駄菓子","調味料","米・乾麺","和風菓子"]);
async function actor(request:NextRequest){const email=request.headers.get("oai-authenticated-user-email")?.trim().toLowerCase(),allowed=(runtime().ADMIN_EMAILS??"").split(",").map(v=>v.trim().toLowerCase()).filter(Boolean);return email&&allowed.includes(email)?email:await requireAdminSession(request)}
function connection(){const settings=runtime();return {url:settings.SMAREGI_PRODUCT_MASTER_URL??settings.SMAREGI_PRODUCT_CREATE_URL??settings.SMAREGI_SPEND_RECALC_URL??settings.SELF_REGISTER_CATALOG_URL,token:settings.SMAREGI_PRODUCT_API_TOKEN??settings.SMAREGI_SPEND_SYNC_KEY??settings.SELF_REGISTER_POS_API_TOKEN}}
type ProductRow={productCode:string;productId:string;productName:string;categoryName:string};
function newCode(productId:string){return `2900${productId.padStart(6,"0")}`}
async function targets(){const rows=await env.DB.prepare("SELECT product_code AS productCode,product_id AS productId,product_name AS productName,category_name AS categoryName FROM inventory_product_settings ORDER BY product_id").all<ProductRow>();return rows.results.filter(row=>/[A-Za-z]/.test(row.productCode)&&/^\d+$/.test(row.productId)&&foodCategories.has(row.categoryName)).map(row=>({...row,newCode:newCode(row.productId)}))}

export async function GET(request:NextRequest){if(!await actor(request))return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const rows=await targets(),all=await env.DB.prepare("SELECT product_code AS productCode FROM inventory_product_settings").all<{productCode:string}>(),used=new Set(all.results.map(row=>row.productCode)),collisions=rows.filter(row=>used.has(row.newCode));return NextResponse.json({ok:true,count:rows.length,collisions,targets:rows},{headers:{"Cache-Control":"no-store"}})}

export async function POST(request:NextRequest){const who=await actor(request);if(!who)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const contentType=request.headers.get("content-type")??"";let confirmCount=0;if(contentType.includes("application/json")){const body=await request.json().catch(()=>null) as {confirmCount?:number}|null;confirmCount=Number(body?.confirmCount??0)}else{const form=await request.formData().catch(()=>null);confirmCount=Number(form?.get("confirmCount")??0)}const rows=await targets();if(!rows.length)return NextResponse.json({ok:true,updated:0,message:"変更対象はありません"});if(confirmCount!==rows.length)return NextResponse.json({error:"TARGET_COUNT_CHANGED",count:rows.length},{status:409});const all=await env.DB.prepare("SELECT product_code AS productCode FROM inventory_product_settings").all<{productCode:string}>(),used=new Set(all.results.map(row=>row.productCode));if(rows.some(row=>used.has(row.newCode)))return NextResponse.json({error:"PRODUCT_CODE_COLLISION"},{status:409});const {url,token}=connection();if(!url||!token)return NextResponse.json({error:"PRODUCT_MASTER_API_NOT_CONNECTED"},{status:503});const requestId=`product-code-migration-${Date.now()}`;const upstream=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":requestId},body:JSON.stringify({version:2,action:"product.migrate-codes",requestId,apiToken:token,data:{migrations:rows.map(row=>({productId:row.productId,oldCode:row.productCode,newCode:row.newCode}))}}),signal:AbortSignal.timeout(120_000)}),result=await upstream.json().catch(()=>({}));if(!upstream.ok||result?.ok===false)return NextResponse.json({error:"SMAREGI_PRODUCT_CODE_MIGRATION_FAILED",detail:result},{status:502});const now=Date.now(),statements=[];for(const row of rows){statements.push(env.DB.prepare("INSERT INTO product_code_aliases (old_code,new_code,product_id,product_name,migrated_at,migrated_by) VALUES (?,?,?,?,?,?) ON CONFLICT(old_code) DO UPDATE SET new_code=excluded.new_code,product_id=excluded.product_id,product_name=excluded.product_name,migrated_at=excluded.migrated_at,migrated_by=excluded.migrated_by").bind(row.productCode,row.newCode,row.productId,row.productName,now,who));for(const table of ["catalog_overrides","inventory_product_settings","inventory_lots","inventory_count_items","smaregi_stock_snapshots","inventory_events"])statements.push(env.DB.prepare(`UPDATE ${table} SET product_code=? WHERE product_code=?`).bind(row.newCode,row.productCode))}for(let index=0;index<statements.length;index+=80)await env.DB.batch(statements.slice(index,index+80));await env.DB.prepare("INSERT INTO member_registration_events (id,member_id,event_type,actor,details_json,created_at) VALUES (?,NULL,'PRODUCT_CODES_MIGRATED',?,?,?)").bind(crypto.randomUUID(),who,JSON.stringify({requestId,count:rows.length}),now).run();return NextResponse.json({ok:true,updated:rows.length,requestId,result:result?.result??result})}
