"use client";
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useState} from "react";
type Member={memberCode:string;displayName:string;displayNameKana:string|null;lineDisplayName:string|null;phone:string|null;email:string|null;birthDate:string|null;gender:string|null;postalCode:string|null;prefecture:string|null;address:string|null;acquisitionSource:string|null;legacyTags:string|null;pointsBalance:number;status:string;sourceSystem:string;createdAt:number;updatedAt:number;residentStatus:string;residentCheckedAt:number|null;currentRank:string|null;pointRatePercent:number|null;qualifyingSpend:number|null;residentPlanActive:number|null;nextReviewAt:number|null;spendSyncedAt:number|null;syncStatus:string|null;syncError:string|null;syncedAt:number|null};
type EventRow={eventType:string;actor:string;details:{changedFields?:string[]};createdAt:number};
type Detail={member:Member;identities:{provider:string;linkedAt:number;revokedAt:number|null}[];events:EventRow[];reservations:{id:string;studioId:string;startsAt:number;endsAt:number;status:string}[];sessions:{id:string;studioId:string;checkedInAt:number|null;totalIncludingTax:number|null;paymentMethod:string|null;paymentStatus:string;pointsEarned:number;status:string;updatedAt:number}[];orders:{id:string;orderNumber:string;status:string;paymentMethod:string;totalIncludingTax:number;pointsEarned:number;createdAt:number}[];points:{purpose:string;sourceId:string;status:string;points:number;createdAt:number}[];stripe:{cardBrand:string|null;cardLast4:string|null;reusableConsentAt:number|null;updatedAt:number}|null};
type Tab="overview"|"reservations"|"purchases"|"benefits"|"subscription"|"history";
const fields=[['displayName','氏名'],['displayNameKana','フリガナ'],['lineDisplayName','LINE名'],['phone','電話番号'],['email','メールアドレス'],['birthDate','生年月日'],['gender','性別'],['postalCode','郵便番号'],['prefecture','都道府県'],['address','住所'],['acquisitionSource','追加経路'],['legacyTags','タグ']] as const;
const eventLabel:Record<string,string>={MEMBER_PROFILE_UPDATED:"会員情報を更新",MEMBER_STATUS_CHANGED:"利用状態を変更",SMAREGI_SYNC_REQUEUED:"スマレジ再同期を依頼",LOCAL_MEMBER_CREATED:"会員登録",CSV_GAP_COMPLETION:"CSV不足情報を補完"};
const rankLabel:Record<string,string>={STANDARD:"スタンダード",BRONZE:"ブロンズ",SILVER:"シルバー",GOLD:"ゴールド",PLATINUM:"プラチナ",DIAMOND:"ダイヤモンド"};
const dateTime=(value:number|null)=>value?new Date(value).toLocaleString("ja-JP",{timeZone:"Asia/Tokyo"}):"未記録";
const yen=(value:number|null)=>`¥${(value??0).toLocaleString("ja-JP")}`;
export default function MemberDetail({params}:{params:Promise<{memberCode:string}>}){
 const [code,setCode]=useState(""),[detail,setDetail]=useState<Detail|null>(null),[form,setForm]=useState<Record<string,string>>({}),[message,setMessage]=useState("読み込んでいます…"),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false),[tab,setTab]=useState<Tab>("overview");
 useEffect(()=>{void params.then(value=>setCode(value.memberCode))},[params]);
 const load=useCallback(async()=>{if(!code)return;const response=await fetch(`/api/v1/admin/members/${encodeURIComponent(code)}`,{cache:"no-store"});if(response.status===401){location.replace("/member-admin/login");return}const result=await response.json();if(!response.ok){setMessage("会員情報を取得できませんでした");return}setDetail(result);setForm(Object.fromEntries(fields.map(([key])=>[key,String(result.member[key]??"")])));setMessage("")},[code]);useEffect(()=>{void load()},[load]);
 const save=async(event:FormEvent)=>{event.preventDefault();if(!detail||busy)return;setBusy(true);setMessage("保存しています…");const response=await fetch(`/api/v1/admin/members/${encodeURIComponent(code)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,updatedAt:detail.member.updatedAt,requestId:crypto.randomUUID()})}),result=await response.json();if(response.status===409){setMessage("別画面で更新されたため、最新情報を読み直しました");await load()}else if(!response.ok)setMessage("入力内容を確認してください");else{setMessage("会員情報を更新しました");setEditing(false);await load()}setBusy(false)};
 if(!detail)return <main className="member-detail-page"><Link href="/member-admin">← 会員一覧へ</Link><p className="member-admin-message">{message}</p></main>;
 const {member}=detail,activeReservations=detail.reservations.filter(row=>row.status==="CONFIRMED");
 return <main className="member-detail-page"><header className="member-detail-header"><div><Link href="/member-admin">← 会員一覧へ</Link><small>{member.memberCode}</small><h1>{member.displayName} 様</h1><p>{member.status==="ACTIVE"?"利用中":"利用停止中"} ／ {member.residentPlanActive?"住民登録プラン有効":"一般会員"}</p></div><button onClick={()=>setEditing(value=>!value)}>{editing?"編集を閉じる":"会員情報を編集"}</button></header>{message&&<p className="member-admin-message" role="status">{message}</p>}
 <nav className="member-detail-tabs">{([['overview','概要'],['reservations',`予約・受付 ${activeReservations.length}`],['purchases',`購入 ${detail.orders.length+detail.sessions.length}`],['benefits','ポイント・特典'],['subscription','サブスク・決済'],['history',`操作履歴 ${detail.events.length}`]] as [Tab,string][]).map(([key,label])=><button className={tab===key?"active":""} key={key} onClick={()=>setTab(key)}>{label}</button>)}</nav>
 {tab==="overview"&&<><section className="member-detail-grid"><article className="member-detail-card"><small>MEMBERSHIP</small><h2>会員ステータス</h2><dl><div><dt>会員ランク</dt><dd>{rankLabel[member.currentRank??""]??"未集計"}</dd></div><div><dt>ポイント還元率</dt><dd>{member.pointRatePercent??1}%</dd></div><div><dt>ランク対象額</dt><dd>{yen(member.qualifyingSpend)}</dd></div><div><dt>ポイント残高</dt><dd>{member.pointsBalance.toLocaleString("ja-JP")}pt</dd></div><div><dt>住民判定</dt><dd>{member.residentStatus}</dd></div><div><dt>次回ランク判定</dt><dd>{dateTime(member.nextReviewAt)}</dd></div></dl></article><article className="member-detail-card"><small>CONNECTIONS</small><h2>外部連携</h2><dl><div><dt>LINE</dt><dd>{detail.identities.some(row=>row.provider==="LINE"&&!row.revokedAt)?"連携済み":"未連携"}</dd></div><div><dt>スマレジ</dt><dd>{member.syncStatus??"対象外"}</dd></div><div><dt>最終同期</dt><dd>{dateTime(member.syncedAt)}</dd></div><div><dt>購入額集計</dt><dd>{dateTime(member.spendSyncedAt)}</dd></div><div><dt>追加経路</dt><dd>{member.acquisitionSource||"未登録"}</dd></div><div><dt>タグ</dt><dd>{member.legacyTags||"未設定"}</dd></div></dl>{member.syncError&&<p className="detail-error">{member.syncError}</p>}</article></section><section className="member-detail-card"><small>PROFILE</small><div className="detail-title-row"><h2>基本情報</h2>{!editing&&<button onClick={()=>setEditing(true)}>編集</button>}</div>{editing?<form className="member-edit-form" onSubmit={save}>{fields.map(([key,label])=><label key={key}>{label}<input type={key==="email"?"email":key==="birthDate"?"date":"text"} value={form[key]??""} onChange={event=>setForm(current=>({...current,[key]:event.target.value}))}/></label>)}<footer><button type="button" onClick={()=>{setEditing(false);void load()}}>キャンセル</button><button disabled={busy}>変更を保存</button></footer></form>:<dl className="profile-readonly">{fields.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{String(member[key]??"")||"未登録"}</dd></div>)}</dl>}</section></>}
 {tab==="reservations"&&<section className="member-detail-card"><small>RESERVATIONS & CHECK-IN</small><h2>予約・利用履歴</h2><div className="admin-history-list">{detail.reservations.map(row=><article key={row.id}><div><strong>{row.studioId}・{row.status}</strong><span>{dateTime(row.startsAt)}〜{dateTime(row.endsAt)}</span></div><small>{row.id}</small></article>)}{detail.sessions.map(row=><article key={row.id}><div><strong>{row.studioId}・{row.status}・{row.paymentStatus}</strong><span>受付 {dateTime(row.checkedInAt)} ／ {yen(row.totalIncludingTax)}</span></div><small>{row.id}</small></article>)}{!detail.reservations.length&&!detail.sessions.length&&<p>予約・受付履歴はありません。</p>}</div></section>}
 {tab==="purchases"&&<section className="member-detail-card"><small>PURCHASES</small><h2>注文・スタジオ購入履歴</h2><div className="admin-history-list">{detail.orders.map(row=><article key={row.id}><div><strong>注文 {row.orderNumber}・{row.status}</strong><span>{dateTime(row.createdAt)} ／ {yen(row.totalIncludingTax)} ／ {row.pointsEarned}pt</span></div><small>{row.paymentMethod}</small></article>)}{detail.sessions.filter(row=>row.totalIncludingTax).map(row=><article key={`session-${row.id}`}><div><strong>スタジオ・{row.paymentStatus}</strong><span>{dateTime(row.updatedAt)} ／ {yen(row.totalIncludingTax)} ／ {row.pointsEarned}pt</span></div><small>{row.paymentMethod??"未設定"}</small></article>)}{!detail.orders.length&&!detail.sessions.some(row=>row.totalIncludingTax)&&<p>新基盤での購入履歴はありません。スマレジ全取引履歴の接続後に過去分も表示します。</p>}</div></section>}
 {tab==="benefits"&&<section className="member-detail-card"><small>POINTS & BENEFITS</small><h2>ポイント・クーポン・回数券</h2><div className="benefit-summary"><strong>{member.pointsBalance.toLocaleString("ja-JP")}pt</strong><span>スマレジを正本として表示</span></div><div className="admin-history-list">{detail.points.map((row,index)=><article key={`${row.sourceId}-${index}`}><div><strong>{row.purpose}・{row.status}</strong><span>{dateTime(row.createdAt)}</span></div><b>{row.points}pt</b></article>)}{!detail.points.length&&<p>ポイント処理履歴はありません。</p>}</div><aside className="connection-note"><strong>クーポン・回数券</strong><p>Lメンバーズの保有残高移行と新しい発行台帳の接続までは、誤発行防止のため閲覧専用です。</p></aside></section>}
 {tab==="subscription"&&<section className="member-detail-grid"><article className="member-detail-card"><small>RESIDENT SUBSCRIPTION</small><h2>住民登録</h2><dl><div><dt>契約状態</dt><dd>{member.residentPlanActive?"継続中":"未加入・停止"}</dd></div><div><dt>住民判定</dt><dd>{member.residentStatus}</dd></div><div><dt>確認日時</dt><dd>{dateTime(member.residentCheckedAt)}</dd></div></dl></article><article className="member-detail-card"><small>SMART PAYMENT</small><h2>登録カード</h2><dl><div><dt>カード</dt><dd>{detail.stripe?.cardLast4?`${detail.stripe.cardBrand??"CARD"} •••• ${detail.stripe.cardLast4}`:"未登録"}</dd></div><div><dt>保存同意</dt><dd>{dateTime(detail.stripe?.reusableConsentAt??null)}</dd></div><div><dt>最終更新</dt><dd>{dateTime(detail.stripe?.updatedAt??null)}</dd></div></dl></article></section>}
 {tab==="history"&&<section className="member-detail-card"><small>AUDIT LOG</small><h2>操作履歴</h2><div className="member-audit-list">{detail.events.length?detail.events.map((row,index)=><article key={`${row.createdAt}-${index}`}><div><strong>{eventLabel[row.eventType]??row.eventType}</strong><small>{row.actor}</small>{row.details.changedFields?.length?<span>変更項目：{row.details.changedFields.join("、")}</span>:null}</div><time>{dateTime(row.createdAt)}</time></article>):<p>操作履歴はありません。</p>}</div></section>}
 </main>
}
