"use client";
import Link from "next/link";
import { FormEvent,useCallback,useEffect,useState } from "react";

type Member={memberCode:string;displayName:string;displayNameKana:string|null;phone:string|null;email:string|null;birthDate:string|null;gender:string|null;postalCode:string|null;prefecture:string|null;address:string|null;pointsBalance:number;status:string;sourceSystem:string;createdAt:number;updatedAt:number;residentStatus:string;residentCheckedAt:number|null;currentRank:string|null;pointRatePercent:number|null;qualifyingSpend:number|null;membershipType:string|null;residentPlanActive:number|null;nextReviewAt:number|null;spendSyncedAt:number|null;syncStatus:string|null;syncAttempts:number|null;syncError:string|null;syncedAt:number|null};
type EventRow={eventType:string;actor:string;details:{changedFields?:string[]};createdAt:number};
type Detail={member:Member;identities:{provider:string;linkedAt:number;revokedAt:number|null}[];events:EventRow[]};
const fields=[['displayName','氏名'],['displayNameKana','フリガナ'],['phone','電話番号'],['email','メールアドレス'],['birthDate','生年月日'],['gender','性別'],['postalCode','郵便番号'],['prefecture','都道府県'],['address','住所']] as const;
const eventLabel:Record<string,string>={MEMBER_PROFILE_UPDATED:"会員情報を更新",MEMBER_STATUS_CHANGED:"利用状態を変更",SMAREGI_SYNC_REQUEUED:"スマレジ再同期を依頼",LOCAL_MEMBER_CREATED:"会員登録",CSV_GAP_COMPLETION:"CSV不足情報を補完"};
const rankLabel:Record<string,string>={STANDARD:"スタンダード",BRONZE:"ブロンズ",SILVER:"シルバー",GOLD:"ゴールド",PLATINUM:"プラチナ",DIAMOND:"ダイヤモンド"};
const dateTime=(value:number|null)=>value?new Date(value).toLocaleString("ja-JP",{timeZone:"Asia/Tokyo"}):"未記録";

export default function MemberDetail({params}:{params:Promise<{memberCode:string}>}){
 const [code,setCode]=useState(""),[detail,setDetail]=useState<Detail|null>(null),[form,setForm]=useState<Record<string,string>>({}),[message,setMessage]=useState("読み込んでいます…"),[busy,setBusy]=useState(false),[editing,setEditing]=useState(false);
 useEffect(()=>{void params.then(value=>setCode(value.memberCode))},[params]);
 const load=useCallback(async()=>{if(!code)return;const response=await fetch(`/api/v1/admin/members/${encodeURIComponent(code)}`,{cache:"no-store"});if(response.status===401){location.replace("/member-admin/login");return}const result=await response.json();if(!response.ok){setMessage("会員情報を取得できませんでした");return}setDetail(result);setForm(Object.fromEntries(fields.map(([key])=>[key,String(result.member[key]??"")])));setMessage("")},[code]);
 useEffect(()=>{void load()},[load]);
 const save=async(event:FormEvent)=>{event.preventDefault();if(!detail||busy)return;setBusy(true);setMessage("保存しています…");const response=await fetch(`/api/v1/admin/members/${encodeURIComponent(code)}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,updatedAt:detail.member.updatedAt,requestId:crypto.randomUUID()})}),result=await response.json();if(response.status===409){setMessage("別の画面で更新されました。最新情報を読み直しました");await load()}else if(!response.ok)setMessage("入力内容を確認してください");else{setMessage("会員情報を更新しました");setEditing(false);await load()}setBusy(false)};
 if(!detail)return <main className="member-detail-page"><Link href="/member-admin">← 会員一覧へ</Link><p className="member-admin-message">{message}</p></main>;
 const {member}=detail;
 return <main className="member-detail-page"><header className="member-detail-header"><div><Link href="/member-admin">← 会員一覧へ</Link><small>{member.memberCode}</small><h1>{member.displayName} 様</h1><p>{member.status==="ACTIVE"?"利用中":"利用停止中"} ／ {member.residentPlanActive?"住民登録プラン有効":"一般会員"}</p></div><button onClick={()=>setEditing(value=>!value)}>{editing?"編集を閉じる":"会員情報を編集"}</button></header>{message&&<p className="member-admin-message" role="status">{message}</p>}<section className="member-detail-grid"><article className="member-detail-card"><small>MEMBERSHIP</small><h2>会員ステータス</h2><dl><div><dt>会員ランク</dt><dd>{rankLabel[member.currentRank??""]??"未集計"}</dd></div><div><dt>ポイント還元率</dt><dd>{member.pointRatePercent??1}%</dd></div><div><dt>ランク対象額</dt><dd>¥{(member.qualifyingSpend??0).toLocaleString("ja-JP")}</dd></div><div><dt>ポイント残高</dt><dd>{member.pointsBalance.toLocaleString("ja-JP")}pt</dd></div><div><dt>住民判定</dt><dd>{member.residentStatus}</dd></div><div><dt>次回ランク判定</dt><dd>{dateTime(member.nextReviewAt)}</dd></div></dl></article><article className="member-detail-card"><small>CONNECTIONS</small><h2>外部連携</h2><dl><div><dt>LINE</dt><dd>{detail.identities.some(row=>row.provider==="LINE"&&!row.revokedAt)?"連携済み":"未連携"}</dd></div><div><dt>スマレジ</dt><dd>{member.syncStatus??"対象外"}</dd></div><div><dt>同期回数</dt><dd>{member.syncAttempts??0}回</dd></div><div><dt>最終同期</dt><dd>{dateTime(member.syncedAt)}</dd></div><div><dt>購入額集計</dt><dd>{dateTime(member.spendSyncedAt)}</dd></div></dl>{member.syncError&&<p className="detail-error">{member.syncError}</p>}</article></section><section className="member-detail-card"><small>PROFILE</small><div className="detail-title-row"><h2>基本情報</h2>{!editing&&<button onClick={()=>setEditing(true)}>編集</button>}</div>{editing?<form className="member-edit-form" onSubmit={save}>{fields.map(([key,label])=><label key={key}>{label}<input type={key==="email"?"email":key==="birthDate"?"date":"text"} value={form[key]??""} onChange={event=>setForm(current=>({...current,[key]:event.target.value}))}/></label>)}<footer><button type="button" onClick={()=>{setEditing(false);void load()}}>キャンセル</button><button disabled={busy}>変更を保存</button></footer></form>:<dl className="profile-readonly">{fields.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{String(member[key]??"")||"未登録"}</dd></div>)}</dl>}</section><section className="member-detail-card"><small>AUDIT LOG</small><h2>操作履歴</h2><div className="member-audit-list">{detail.events.length?detail.events.map((row,index)=><article key={`${row.createdAt}-${index}`}><div><strong>{eventLabel[row.eventType]??row.eventType}</strong><small>{row.actor}</small>{row.details.changedFields?.length?<span>変更項目：{row.details.changedFields.join("、")}</span>:null}</div><time>{dateTime(row.createdAt)}</time></article>):<p>操作履歴はありません。</p>}</div></section></main>
}
