import {env} from "cloudflare:workers";
import {NextRequest,NextResponse} from "next/server";
import {requireAdminSession} from "@/lib/admin-session";
import {facilityPost} from "@/lib/facility-api";
import {stripeRequest} from "@/lib/stripe";
import {expireStaleLocks,expireStaleOrder,reconcileCompletedOrders} from "@/lib/order-pos";
import {reconcileAllResidentSubscriptions} from "@/lib/resident-subscription";
type Health={key:string;label:string;status:"OK"|"FAILED"|"NOT_CONFIGURED";latencyMs:number|null;message:string;checkedAt:number};
const runtime=()=>env as unknown as Record<string,string|undefined>;
const labels:Record<string,string>={STRIPE:"Stripe決済",LINE:"LINE通知",FACILITY:"FEBBRAIO予約・受付",KITCHEN:"キッチン管理",SMAREGI:"スマレジ連携"};
async function timed(key:string,configured:boolean,check:()=>Promise<unknown>):Promise<Health>{const started=Date.now();if(!configured)return{key,label:labels[key],status:"NOT_CONFIGURED",latencyMs:null,message:"接続設定待ち",checkedAt:started};try{await check();return{key,label:labels[key],status:"OK",latencyMs:Date.now()-started,message:"正常に応答しています",checkedAt:Date.now()}}catch(error){return{key,label:labels[key],status:"FAILED",latencyMs:Date.now()-started,message:error instanceof Error?error.message:"接続確認に失敗しました",checkedAt:Date.now()}}}
async function checkAll(){const settings=runtime(),kitchenBase=(settings.KITCHEN_SCHEDULE_API_BASE_URL??settings.KITCHEN_API_BASE_URL??"").replace(/\/$/,"");return Promise.all([timed("STRIPE",Boolean(settings.STRIPE_SECRET_KEY),()=>stripeRequest("/account")),timed("LINE",Boolean(settings.LINE_CHANNEL_ACCESS_TOKEN),async()=>{const response=await fetch("https://api.line.me/v2/bot/info",{headers:{Authorization:`Bearer ${settings.LINE_CHANNEL_ACCESS_TOKEN}`},signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error(`LINE_HTTP_${response.status}`)}),timed("FACILITY",Boolean(settings.COMMON_FACILITY_GAS_URL&&(settings.FACILITY_STAFF_API_TOKEN||settings.FACILITY_API_TOKEN)),()=>facilityPost("facility.status",{facilityId:"FEBBRAIO"},crypto.randomUUID())),timed("KITCHEN",Boolean(kitchenBase&&settings.KITCHEN_API_TOKEN),async()=>{const response=await fetch(`${kitchenBase}/api/v1/health`,{headers:{Authorization:`Bearer ${settings.KITCHEN_API_TOKEN}`},signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error(`KITCHEN_HTTP_${response.status}`)}),timed("SMAREGI",Boolean(settings.SMAREGI_SPEND_RECALC_URL&&settings.SMAREGI_SPEND_SYNC_KEY),async()=>{const response=await fetch(settings.SMAREGI_SPEND_RECALC_URL!,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({op:"loyaltyAnnualSpendSyncStatus",syncKey:settings.SMAREGI_SPEND_SYNC_KEY}),signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error(`SMAREGI_HTTP_${response.status}`)})])}
async function saveRun(actor:string,requestId:string,action:string,details:unknown){await env.DB.prepare("INSERT INTO member_registration_events (id,member_id,event_type,actor,details_json,created_at) VALUES (?,NULL,'INTEGRATION_MAINTENANCE',?,?,?)").bind(crypto.randomUUID(),actor,JSON.stringify({requestId,action,details}),Date.now()).run()}
export async function GET(request:NextRequest){if(!await requireAdminSession(request))return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const rows=await env.DB.prepare("SELECT details_json AS details,created_at AS createdAt FROM member_registration_events WHERE event_type='INTEGRATION_MAINTENANCE' ORDER BY created_at DESC LIMIT 20").all<{details:string;createdAt:number}>();const history=rows.results.map(row=>{try{return{...JSON.parse(row.details),createdAt:row.createdAt}}catch{return null}}).filter(Boolean);return NextResponse.json({history,failedStripe:await env.DB.prepare("SELECT COUNT(*) AS count FROM stripe_webhook_events WHERE status='FAILED'").first(),pendingPos:await env.DB.prepare("SELECT COUNT(*) AS count FROM orders WHERE status IN ('PAID','ACCEPTED','COOKING','READY','PICKED_UP') AND smaregi_transaction_id IS NULL").first()},{headers:{"Cache-Control":"no-store"}})}
export async function POST(request:NextRequest){const actor=await requireAdminSession(request);if(!actor)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const body=await request.json().catch(()=>null) as {action?:"CHECK_ALL"|"RECONCILE_ALL";requestId?:string}|null;if(!body?.action||!body.requestId)return NextResponse.json({error:"INVALID_REQUEST"},{status:400});const duplicate=await env.DB.prepare("SELECT id FROM member_registration_events WHERE event_type='INTEGRATION_MAINTENANCE' AND details_json LIKE ? LIMIT 1").bind(`%${body.requestId}%`).first();if(duplicate)return NextResponse.json({ok:true,idempotent:true});if(body.action==="CHECK_ALL"){const results=await checkAll();await saveRun(actor,body.requestId,body.action,results);return NextResponse.json({ok:true,results})}await Promise.all([expireStaleLocks(),expireStaleOrder(),reconcileCompletedOrders()]);const residents=await reconcileAllResidentSubscriptions(100);const details={orders:"RECONCILED",residentSubscriptions:residents.length,failures:residents.filter(row=>!row.updated&&row.status!=="UNCHANGED").length};await saveRun(actor,body.requestId,body.action,details);return NextResponse.json({ok:true,details})}
