import { env } from "cloudflare:workers";
import { NextRequest,NextResponse } from "next/server";
import { requireKitchenToken } from "@/lib/kitchen-api";
import { allocateKitchenUnitNumber } from "@/lib/kitchen-units";

type Department="FOOD"|"DRINK";type Action="START"|"STEP"|"CALL"|"PICKUP"|"RESTORE_CALL"|"CANCEL";
const activeOrderStatuses="'PAID','ACCEPTED','COOKING','READY'";
const callDate=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());

async function nextNumber(department:Department,date:string){return allocateKitchenUnitNumber(department,date)}
async function ensureUnits(){const date=callDate(),items=await env.DB.prepare(`SELECT i.id,i.order_id AS orderId,i.department,i.quantity,CASE WHEN t.order_id IS NULL THEN 0 ELSE 1 END AS isTest FROM order_items i JOIN orders o ON o.id=i.order_id LEFT JOIN kitchen_test_orders t ON t.order_id=o.id WHERE o.status IN (${activeOrderStatuses})`).all<{id:string;orderId:string;department:Department;quantity:number;isTest:number}>();for(const item of items.results){const existing=await env.DB.prepare("SELECT unit_index AS unitIndex FROM kitchen_units WHERE order_item_id=?").bind(item.id).all<{unitIndex:number}>(),indices=new Set(existing.results.map(row=>row.unitIndex));for(let index=1;index<=item.quantity;index++){if(indices.has(index))continue;const counterDate=item.isTest?`TEST:${date}`:date,number=await nextNumber(item.department,counterDate),now=Date.now();await env.DB.prepare("INSERT OR IGNORE INTO kitchen_units(id,order_id,order_item_id,unit_index,department,call_date,call_number,status,current_step,total_steps,is_test,updated_at) VALUES(?,?,?,?,?,?,?,'ACCEPTED',0,1,?,?)").bind(`ku_${crypto.randomUUID()}`,item.orderId,item.id,index,item.department,counterDate,number,item.isTest,now).run()}}}

async function syncAggregate(unitId:string,now:number){const owner=await env.DB.prepare("SELECT order_id AS orderId,department FROM kitchen_units WHERE id=?").bind(unitId).first<{orderId:string;department:Department}>();if(!owner)return;const rows=await env.DB.prepare("SELECT status FROM kitchen_units WHERE order_id=? AND department=?").bind(owner.orderId,owner.department).all<{status:string}>(),states=rows.results.map(row=>row.status),active=states.filter(status=>status!=="CANCELLED");let departmentStatus="ACCEPTED";if(active.length===0)departmentStatus="CANCELLED";else if(active.every(status=>status==="PICKED_UP"))departmentStatus="PICKED_UP";else if(active.every(status=>status==="CALLED"||status==="PICKED_UP"))departmentStatus="CALLED";else if(active.every(status=>status==="READY"||status==="CALLED"||status==="PICKED_UP"))departmentStatus="READY";else if(active.some(status=>status!=="ACCEPTED"))departmentStatus="COOKING";await env.DB.prepare("UPDATE order_fulfillments SET status=?,ready_at=CASE WHEN ?='READY' AND ready_at IS NULL THEN ? ELSE ready_at END,called_at=CASE WHEN ?='CALLED' AND called_at IS NULL THEN ? ELSE called_at END,picked_up_at=CASE WHEN ?='PICKED_UP' AND picked_up_at IS NULL THEN ? ELSE picked_up_at END,updated_at=? WHERE order_id=? AND department=?").bind(departmentStatus,departmentStatus,now,departmentStatus,now,departmentStatus,now,now,owner.orderId,owner.department).run();const departments=await env.DB.prepare("SELECT status FROM order_fulfillments WHERE order_id=?").bind(owner.orderId).all<{status:string}>();let values=departments.results.map(row=>row.status);if(values.length===0){const units=await env.DB.prepare("SELECT status FROM kitchen_units WHERE order_id=?").bind(owner.orderId).all<{status:string}>();values=units.results.map(row=>row.status)}const orderStatus=values.length>0&&values.every(status=>status==="PICKED_UP"||status==="CANCELLED")?"PICKED_UP":values.some(status=>status==="READY"||status==="CALLED"||status==="PICKED_UP")?"READY":values.some(status=>status==="COOKING")?"COOKING":"ACCEPTED";await env.DB.prepare("UPDATE orders SET status=?,updated_at=? WHERE id=? AND status NOT IN ('CANCELLED','EXPIRED','REFUNDED')").bind(orderStatus,now,owner.orderId).run()}

export async function GET(request:NextRequest){if(!await requireKitchenToken(request))return NextResponse.json({error:"UNAUTHORIZED"},{status:401});await ensureUnits();const department=request.nextUrl.searchParams.get("department"),history=request.nextUrl.searchParams.get("history")==="true",testOnly=request.nextUrl.searchParams.get("test")==="true";if(department&&department!=="ALL"&&department!=="FOOD"&&department!=="DRINK")return NextResponse.json({error:"INVALID_DEPARTMENT"},{status:400});const where=[history?"u.status IN ('PICKED_UP','CANCELLED')":"u.status IN ('ACCEPTED','COOKING','READY','CALLED')"];const bindings:unknown[]=[];if(department&&department!=="ALL"){where.push("u.department=?");bindings.push(department)}if(testOnly)where.push("u.is_test=1");const result=await env.DB.prepare(`SELECT u.id,u.order_id AS orderId,u.department,u.call_number AS callNumber,u.status,u.current_step AS currentStep,u.total_steps AS totalSteps,u.is_test AS isTest,u.ready_at AS readyAt,u.called_at AS calledAt,u.updated_at AS updatedAt,o.pickup_at AS estimatedReadyAt,i.product_name AS productName,i.selected_options_json AS optionsJson,i.preparation_minutes AS preparationMinutes FROM kitchen_units u JOIN orders o ON o.id=u.order_id JOIN order_items i ON i.id=u.order_item_id WHERE ${where.join(" AND ")} ORDER BY COALESCE(o.pickup_at,u.updated_at),u.updated_at`).bind(...bindings).all<{id:string;orderId:string;department:Department;callNumber:number;status:string;currentStep:number;totalSteps:number;isTest:number;readyAt:number|null;calledAt:number|null;updatedAt:number;estimatedReadyAt:number|null;productName:string;optionsJson:string;preparationMinutes:number}>();return NextResponse.json({units:result.results.map(row=>({...row,isTest:!!row.isTest,items:[{name:row.productName,quantity:1,options:parseOptions(row.optionsJson),preparationMinutes:row.preparationMinutes}]}))},{headers:{"Cache-Control":"no-store"}})}

export async function PATCH(request:NextRequest){if(!await requireKitchenToken(request))return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const body=await request.json().catch(()=>null)as{unitId?:string;action?:Action;totalSteps?:number}|null,id=body?.unitId??"",action=body?.action,totalSteps=Math.max(1,Math.min(20,Math.floor(body?.totalSteps??1)));if(!/^ku_[A-Za-z0-9-]{10,80}$/.test(id)||!action)return NextResponse.json({error:"INVALID_REQUEST"},{status:400});const unit=await env.DB.prepare("SELECT status,current_step AS currentStep,total_steps AS totalSteps FROM kitchen_units WHERE id=?").bind(id).first<{status:string;currentStep:number;totalSteps:number}>();if(!unit)return NextResponse.json({error:"UNIT_NOT_FOUND"},{status:404});const now=Date.now();if(action==="START"&&unit.status==="ACCEPTED")await env.DB.prepare("UPDATE kitchen_units SET status='COOKING',total_steps=?,updated_at=? WHERE id=?").bind(totalSteps,now,id).run();else if(action==="STEP"&&(unit.status==="ACCEPTED"||unit.status==="COOKING")){const next=Math.min(totalSteps,unit.currentStep+1),done=next>=totalSteps;await env.DB.prepare("UPDATE kitchen_units SET status=?,current_step=?,total_steps=?,ready_at=CASE WHEN ? THEN ? ELSE ready_at END,updated_at=? WHERE id=?").bind(done?"READY":"COOKING",next,totalSteps,done?1:0,now,now,id).run()}else if(action==="CALL"&&unit.status==="READY")await env.DB.prepare("UPDATE kitchen_units SET status='CALLED',called_at=?,updated_at=? WHERE id=?").bind(now,now,id).run();else if(action==="PICKUP"&&(unit.status==="READY"||unit.status==="CALLED"))await env.DB.prepare("UPDATE kitchen_units SET status='PICKED_UP',picked_up_at=?,updated_at=? WHERE id=?").bind(now,now,id).run();else if(action==="RESTORE_CALL"&&unit.status==="PICKED_UP")await env.DB.prepare("UPDATE kitchen_units SET status='CALLED',picked_up_at=NULL,called_at=?,updated_at=? WHERE id=?").bind(now,now,id).run();else if(action==="CANCEL"&&!['PICKED_UP','CANCELLED'].includes(unit.status))await env.DB.prepare("UPDATE kitchen_units SET status='CANCELLED',updated_at=? WHERE id=?").bind(now,id).run();else return NextResponse.json({error:"INVALID_STATUS_TRANSITION",current:unit},{status:409});await syncAggregate(id,now);const updated=await env.DB.prepare("SELECT id,order_id AS orderId,department,call_number AS callNumber,status,current_step AS currentStep,total_steps AS totalSteps,ready_at AS readyAt,called_at AS calledAt,updated_at AS updatedAt FROM kitchen_units WHERE id=?").bind(id).first();return NextResponse.json(updated)}
function parseOptions(value:string){try{const parsed=JSON.parse(value);return Array.isArray(parsed)?parsed.map(option=>typeof option==="string"?option:option?.name??option?.label).filter(Boolean):[]}catch{return[]}}
