import {env} from "cloudflare:workers";
import {NextRequest} from "next/server";
import {requireAdminPermission} from "@/lib/admin-session";
import {receiptError,receiptResponse,sha256} from "@/lib/receipt-api";
const allowedScopes=["purchase:create","purchase:read-status","purchase:adjust"];
const tokenValue=()=>{const bytes=crypto.getRandomValues(new Uint8Array(32));return`rcpt_${btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}`};
export async function GET(request:NextRequest){const actor=await requireAdminPermission(request,"SETTINGS_ADMIN");if(!actor)return receiptError(401,"UNAUTHORIZED","管理者認証が必要です");const rows=(await env.DB.prepare("SELECT device_id AS deviceId,display_name AS displayName,scopes_json AS scopesJson,status,created_at AS createdAt,last_used_at AS lastUsedAt,revoked_at AS revokedAt FROM receipt_devices ORDER BY created_at DESC").all<Record<string,unknown>>()).results;return receiptResponse({ok:true,devices:rows.map(row=>({...row,scopes:JSON.parse(String(row.scopesJson)),scopesJson:undefined}))})}
export async function POST(request:NextRequest){const actor=await requireAdminPermission(request,"SETTINGS_ADMIN");if(!actor)return receiptError(401,"UNAUTHORIZED","管理者認証が必要です");const body=await request.json().catch(()=>null) as {deviceId?:unknown;displayName?:unknown;scopes?:unknown}|null,deviceId=typeof body?.deviceId==="string"?body.deviceId.trim().toUpperCase():"",displayName=typeof body?.displayName==="string"?body.displayName.trim().slice(0,120):"",scopes=Array.isArray(body?.scopes)?[...new Set(body.scopes.filter((scope):scope is string=>typeof scope==="string"&&allowedScopes.includes(scope)))]:[];if(!/^[A-Z0-9][A-Z0-9._:-]{2,79}$/.test(deviceId)||!displayName||scopes.length===0)return receiptError(400,"INVALID_REQUEST","端末ID、表示名、権限を確認してください");const runtime=env as unknown as Record<string,string|undefined>,pepper=runtime.RECEIPT_TOKEN_PEPPER?.trim();if(!pepper)return receiptError(503,"TOKEN_ISSUER_NOT_CONFIGURED","端末トークン発行設定が未完了です",undefined,true);const token=tokenValue(),hash=await sha256(`${pepper}\0${token}`),now=Date.now();try{await env.DB.prepare("INSERT INTO receipt_devices(id,device_id,display_name,token_hash,scopes_json,status,created_by,created_at,last_used_at,revoked_at) VALUES(?,?,?,?,?,'ACTIVE',?,?,NULL,NULL) ON CONFLICT(device_id) DO UPDATE SET display_name=excluded.display_name,token_hash=excluded.token_hash,scopes_json=excluded.scopes_json,status='ACTIVE',created_by=excluded.created_by,created_at=excluded.created_at,revoked_at=NULL").bind(crypto.randomUUID(),deviceId,displayName,hash,JSON.stringify(scopes),actor.email,now).run();return receiptResponse({ok:true,device:{deviceId,displayName,scopes},token,warning:"このトークンは今回だけ表示されます。セルフレジの暗号化領域へ保存してください。"},201)}catch{return receiptError(503,"DEVICE_REGISTRATION_UNAVAILABLE","端末を登録できませんでした",undefined,true)}}
export async function DELETE(request:NextRequest){const actor=await requireAdminPermission(request,"SETTINGS_ADMIN");if(!actor)return receiptError(401,"UNAUTHORIZED","管理者認証が必要です");const body=await request.json().catch(()=>null) as {deviceId?:unknown}|null,deviceId=typeof body?.deviceId==="string"?body.deviceId.trim().toUpperCase():"";if(!deviceId)return receiptError(400,"INVALID_REQUEST","deviceIdを指定してください");await env.DB.prepare("UPDATE receipt_devices SET status='REVOKED',revoked_at=? WHERE device_id=?").bind(Date.now(),deviceId).run();return receiptResponse({ok:true,deviceId,status:"REVOKED"})}
