"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";

type Resource="coupons"|"surveys"|"campaigns"|"automations";
type Item={id:string;name?:string;title?:string;description?:string;status?:string;enabled?:number;benefit_type?:string;benefit_value?:number;reward_points?:number;channel?:string;responseCount?:number;issuedCount?:number;usedCount?:number;updated_at:number};
const labels:Record<Resource,string>={coupons:"クーポン",surveys:"アンケート",campaigns:"お知らせ・配信",automations:"自動処理"};

export function EngagementPanel({mode}:{mode:"benefits"|"communication"}){
 const resources:Resource[]=mode==="benefits"?["coupons"]:["campaigns","surveys","automations"];
 const [resource,setResource]=useState<Resource>(resources[0]),[items,setItems]=useState<Item[]>([]),[busy,setBusy]=useState(""),[message,setMessage]=useState("");
 const [form,setForm]=useState({name:"",description:"",benefitType:"FIXED",benefitValue:"",rewardPoints:"",channel:"CARD",message:"",triggerType:"MANUAL"});
 const load=useCallback(async()=>{setBusy("LOAD");setMessage("");try{const response=await fetch(`/api/v1/admin/engagement?resource=${resource}`,{cache:"no-store",signal:AbortSignal.timeout(8000)});if(response.status===401){location.replace("/member-admin/login");return}if(response.ok)setItems((await response.json()).items??[]);else setMessage("一覧を取得できませんでした。もう一度更新してください")}catch{setMessage("一覧の取得が8秒を超えました。もう一度更新してください")}finally{setBusy("")}},[resource]);
 useEffect(()=>{void load()},[load]);
 const create=async(event:FormEvent)=>{event.preventDefault();if(!form.name.trim()||busy)return;setBusy("CREATE");setMessage(`${labels[resource]}を保存しています…`);const response=await fetch("/api/v1/admin/engagement",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource,requestId:crypto.randomUUID(),...form,title:form.name})});if(response.ok){setForm(value=>({...value,name:"",description:"",message:""}));setMessage(`${labels[resource]}を下書き保存しました`);await load()}else setMessage("保存できませんでした。入力内容と接続設定を確認してください");setBusy("")};
 const change=async(item:Item,value:string|boolean)=>{setBusy(item.id);const response=await fetch("/api/v1/admin/engagement",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource,id:item.id,requestId:crypto.randomUUID(),...(resource==="automations"?{enabled:value}:{status:value})})});setMessage(response.ok?"状態を更新しました":"状態を更新できませんでした");if(response.ok)await load();setBusy("")};
 return <section className="operations-panel engagement-panel"><header><div><small>{mode==="benefits"?"BENEFITS":"COMMUNICATION"}</small><h2>{mode==="benefits"?"特典・クーポン":"配信・アンケート・自動処理"}</h2><p>下書き作成、公開状態、利用実績を一つの画面で管理します。</p></div></header>
  {resources.length>1&&<nav className="engagement-tabs">{resources.map(value=><button className={resource===value?"active":""} key={value} onClick={()=>setResource(value)}>{labels[value]}</button>)}</nav>}
  {message&&<p className="member-admin-message" role="status">{message}</p>}
  <div className="engagement-layout"><form className="engagement-form" onSubmit={create}><h3>{labels[resource]}を新規作成</h3><label>管理名<input required maxLength={160} value={form.name} onChange={event=>setForm(value=>({...value,name:event.target.value}))} placeholder={resource==="coupons"?"例：住民限定ドリンク特典":"管理しやすい名前"}/></label><label>説明<textarea rows={4} value={resource==="campaigns"?form.message:form.description} onChange={event=>setForm(value=>resource==="campaigns"?{...value,message:event.target.value}:{...value,description:event.target.value})} placeholder="会員へ伝える内容やスタッフ向けの説明"/></label>
   {resource==="coupons"&&<div className="engagement-fields"><label>特典<select value={form.benefitType} onChange={event=>setForm(value=>({...value,benefitType:event.target.value}))}><option value="FIXED">定額値引き</option><option value="PERCENT">割引率</option><option value="POINTS">ポイント付与</option><option value="MEMBER_PRICE">会員価格</option></select></label><label>値<input type="number" min="0" value={form.benefitValue} onChange={event=>setForm(value=>({...value,benefitValue:event.target.value}))}/></label></div>}
   {resource==="surveys"&&<label>回答特典ポイント<input type="number" min="0" value={form.rewardPoints} onChange={event=>setForm(value=>({...value,rewardPoints:event.target.value}))}/></label>}
   {resource==="campaigns"&&<label>表示先<select value={form.channel} onChange={event=>setForm(value=>({...value,channel:event.target.value}))}><option value="CARD">会員証内</option><option value="LINE">LINE</option><option value="EMAIL">メール</option><option value="MULTI">複数</option></select></label>}
   {resource==="automations"&&<label>開始条件<select value={form.triggerType} onChange={event=>setForm(value=>({...value,triggerType:event.target.value}))}><option value="MANUAL">手動確認後</option><option value="MEMBER_REGISTERED">会員登録時</option><option value="PURCHASE_COMPLETED">購入完了時</option><option value="RESIDENT_STARTED">住民登録時</option></select></label>}
   <button disabled={Boolean(busy)}>{busy==="CREATE"?"保存しています…":"下書き保存"}</button><small>公開・送信は一覧で状態を切り替えるまで実行されません。</small></form>
   <div className="engagement-list"><div className="engagement-list-heading"><h3>登録済み {items.length}件</h3><button className="secondary" onClick={()=>void load()}>更新</button></div>{busy==="LOAD"?<p className="admin-empty">読み込んでいます…</p>:items.length===0?<p className="admin-empty">まだ登録はありません。</p>:items.map(item=><article key={item.id}><div><small>{labels[resource]}</small><strong>{item.name??item.title}</strong><p>{item.description||statusText(resource,item)}</p></div><div className="engagement-item-actions"><b>{statusText(resource,item)}</b>{resource==="automations"?<button disabled={busy===item.id} onClick={()=>void change(item,!item.enabled)}>{item.enabled?"停止する":"有効にする"}</button>:<select disabled={busy===item.id} value={item.status??"DRAFT"} onChange={event=>void change(item,event.target.value)}>{statusOptions(resource).map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>}</div></article>)}</div>
  </div>
 </section>
}
function statusOptions(resource:Resource){if(resource==="coupons")return [{value:"DRAFT",label:"下書き"},{value:"ACTIVE",label:"公開中"},{value:"PAUSED",label:"一時停止"},{value:"ENDED",label:"終了"}];if(resource==="surveys")return [{value:"DRAFT",label:"下書き"},{value:"ACTIVE",label:"受付中"},{value:"CLOSED",label:"終了"}];return [{value:"DRAFT",label:"下書き"},{value:"SCHEDULED",label:"配信予約"},{value:"CANCELLED",label:"取消"}]}
function statusText(resource:Resource,item:Item){if(resource==="automations")return item.enabled?"有効":"停止中";if(resource==="coupons")return `${item.status??"DRAFT"}・発行 ${Number(item.issuedCount??0)}件・利用 ${Number(item.usedCount??0)}件`;if(resource==="surveys")return `${item.status??"DRAFT"}・回答 ${Number(item.responseCount??0)}件`;return `${item.status??"DRAFT"}・${item.channel??"CARD"}`}

