"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";

type Message={role:"user"|"assistant";content:string};
type LedgerItem={id:string;name:string;status:string;channel:string;content_json:string;scheduled_at:number|null;updated_at:number};
const welcome:Message={role:"assistant",content:"投稿したい内容を教えてください。Instagram・X・Threads・LINEに合わせて、会話しながら整えます。日時や画像、対象のお客様が決まっていれば一緒に入力してください。"};
const itemContent=(item:LedgerItem)=>{try{const value=JSON.parse(item.content_json||"{}") as {title?:string;body?:string};return {title:value.title??item.name,body:value.body??""}}catch{return {title:item.name,body:"本文を読み取れませんでした"}}};
const when=(value:number|null)=>value?new Date(value).toLocaleString("ja-JP",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}):"未設定";

export function SnsAssistantPanel(){
 const [messages,setMessages]=useState<Message[]>([welcome]),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[configured,setConfigured]=useState<boolean|null>(null),[notice,setNotice]=useState(""),[ledger,setLedger]=useState<LedgerItem[]>([]),[ledgerBusy,setLedgerBusy]=useState(false);
 const loadLedger=useCallback(async()=>{setLedgerBusy(true);try{const response=await fetch("/api/v1/admin/engagement?resource=campaigns",{cache:"no-store",signal:AbortSignal.timeout(8000)});if(response.status===401){location.replace("/member-admin/login");return}if(!response.ok)throw new Error();setLedger((await response.json()).items??[])}catch{setNotice("投稿台帳を取得できませんでした。更新ボタンから再試行できます")}finally{setLedgerBusy(false)}},[]);
 useEffect(()=>{void loadLedger();void fetch("/api/v1/admin/sns-assistant",{cache:"no-store"}).then(async response=>{if(response.status===401){location.replace("/member-admin/login");return}const ready=response.ok&&Boolean((await response.json()).configured);setConfigured(ready);if(!ready)return;setNotice("本日の投稿案を確認しています…");const daily=await fetch("/api/v1/admin/sns-assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({daily:true}),signal:AbortSignal.timeout(30000)}),result=await daily.json();if(!daily.ok)throw new Error(result.message??"本日の投稿案を取得できませんでした");if(result.message)setMessages(value=>[...value,{role:"assistant",content:`本日の自動提案（投稿台帳へ保存済み）\n\n${String(result.message)}`}]);setNotice(result.existing?"本日の投稿案を表示しました":"本日の投稿案を生成し、投稿台帳へ下書き保存しました");await loadLedger()}).catch(error=>{setConfigured(value=>value??false);setNotice(error instanceof Error?error.message:"本日の投稿案を取得できませんでした")})},[loadLedger]);
 const send=async(event:FormEvent)=>{event.preventDefault();const text=input.trim();if(!text||busy)return;const next=[...messages,{role:"user" as const,content:text}];setMessages(next);setInput("");setBusy(true);setNotice("");try{const response=await fetch("/api/v1/admin/sns-assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:next.slice(1)}),signal:AbortSignal.timeout(30000)}),result=await response.json();if(!response.ok)throw new Error(result.message??"投稿案を生成できませんでした");setMessages(value=>[...value,{role:"assistant",content:String(result.message)}])}catch(error){setNotice(error instanceof Error?error.message:"投稿案を生成できませんでした")}finally{setBusy(false)}};
 const save=async(message:string)=>{setNotice("投稿台帳へ保存しています…");const response=await fetch("/api/v1/admin/engagement",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource:"campaigns",requestId:crypto.randomUUID(),name:`SNS投稿案 ${new Date().toLocaleString("ja-JP")}`,title:"SNS投稿案",message,channel:"MULTI"})});setNotice(response.ok?"投稿案を配信台帳へ下書き保存しました":"下書きを保存できませんでした");if(response.ok)await loadLedger()};
 const changeStatus=async(item:LedgerItem,status:string)=>{setLedgerBusy(true);const response=await fetch("/api/v1/admin/engagement",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({resource:"campaigns",id:item.id,status,requestId:crypto.randomUUID()})});setNotice(response.ok?"台帳の状態を更新しました":"状態を更新できませんでした");if(response.ok)await loadLedger();else setLedgerBusy(false)};
 return <section className="sns-assistant-panel"><header><div><small>SNS CREATIVE ASSISTANT</small><h2>投稿相談AI</h2><p>媒体ごとの投稿案を会話しながら作り、承認前の下書きとして保存します。</p></div><span className={configured?"ready":"waiting"}>{configured===null?"接続確認中":configured?"AI接続済み":"APIキー設定待ち"}</span></header>
  {!configured&&configured!==null&&<p className="sns-assistant-warning">OpenAI APIキーの設定後に会話生成が有効になります。投稿台帳や既存SNS管理はそのまま利用できます。</p>}
  <div className="sns-chat-log">{messages.map((message,index)=><article className={message.role} key={index}><small>{message.role==="assistant"?"SNSアシスタント":"スタッフ"}</small><p>{message.content}</p>{message.role==="assistant"&&index>0&&<button onClick={()=>void save(message.content)}>この案を投稿台帳へ保存</button>}</article>)}{busy&&<article className="assistant thinking"><small>SNSアシスタント</small><p>投稿案を考えています…</p></article>}</div>
  {notice&&<p className="member-admin-message" role="status">{notice}</p>}
  <form className="sns-chat-form" onSubmit={send}><textarea rows={4} maxLength={4000} value={input} onChange={event=>setInput(event.target.value)} placeholder="例：今週土曜の無料ライブを、近所の人がふらっと来たくなる雰囲気で。LINEは短め、Instagramは詳しく。"/><button disabled={busy||!configured||!input.trim()}>{busy?"考案中…":"投稿案を相談する"}</button></form>
  <div className="sns-quick-prompts"><button onClick={()=>setInput("Instagram・X・Threads・LINEの4媒体向けに、それぞれ文章を作り分けてください。")}>4媒体分を作る</button><button onClick={()=>setInput("もっと近所の人が気軽にふらっと立ち寄りたくなる文章に直してください。")}>親しみやすくする</button><button onClick={()=>setInput("重要情報が冒頭だけで伝わる短いLINE告知にしてください。")}>LINE向けに短く</button></div>
  <section className="sns-ledger"><header><div><small>CONTENT LEDGER</small><h2>投稿台帳</h2><p>AIの提案、LINE告知、手動作成した投稿案をこの画面で確認できます。</p></div><button disabled={ledgerBusy} onClick={()=>void loadLedger()}>{ledgerBusy?"更新中…":"最新状態に更新"}</button></header>
   {ledgerBusy&&ledger.length===0?<p className="admin-empty">投稿台帳を読み込んでいます…</p>:ledger.length===0?<p className="admin-empty">保存済みの投稿案はありません。</p>:<div className="sns-ledger-list">{ledger.map(item=>{const body=itemContent(item);return <details key={item.id}><summary><span><small>{item.channel}・更新 {when(item.updated_at)}</small><strong>{item.name}</strong><b>{body.title}</b></span><em>{item.status==="DRAFT"?"下書き":item.status==="SCHEDULED"?"配信予約":"取消"}</em></summary><pre>{body.body}</pre><footer><span>配信予定：{when(item.scheduled_at)}</span><label>状態<select disabled={ledgerBusy} value={item.status} onChange={event=>void changeStatus(item,event.target.value)}><option value="DRAFT">下書き</option><option value="SCHEDULED">配信予約</option><option value="CANCELLED">取消</option></select></label></footer></details>})}</div>}
  </section>
 </section>
}
