"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {jstDateInput} from "../../lib/jst-date";
type Row={reservationId:string;memberCode:string;memberName:string;startAt:string;endAt:string;status:string;sessionStatus?:string;paymentStatus?:string};

export function StudioReservationOverview({onMember}:{onMember:(memberCode:string)=>void}){
 const today=new Date(),later=new Date(Date.now()+31*86400000),[from,setFrom]=useState(jstDateInput(today)),[to,setTo]=useState(jstDateInput(later)),[rows,setRows]=useState<Row[]>([]),[message,setMessage]=useState("予約一覧を読み込んでいます…"),[busy,setBusy]=useState(false),requestId=useRef(0),initial=useRef(false);
 const load=useCallback(async()=>{const current=++requestId.current;setBusy(true);setMessage("予約一覧を更新しています…");try{const response=await fetch(`/api/v1/admin/studio/reservations?from=${from}&to=${to}`,{cache:"default",signal:AbortSignal.timeout(8000)}),result=await response.json();if(current!==requestId.current)return;setRows(result.reservations??[]);setMessage(response.ok?(result.reservations?.length?"":"期間内の予約はありません"):result.message??"予約一覧を取得できませんでした")}catch{if(current===requestId.current)setMessage("8秒以内に取得できませんでした。時間を置いて再度お試しください")}finally{if(current===requestId.current)setBusy(false)}},[from,to]);
 useEffect(()=>{if(initial.current)return;initial.current=true;void load()},[load]);
 return <section className="studio-all-reservations"><header><div><small>ALL RESERVATIONS</small><h2>スタジオ予約一覧</h2><p>会員を選択する前に、期間内の予約・利用・精算状態を確認できます。</p></div><div><label>開始<input type="date" value={from} onChange={event=>setFrom(event.target.value)}/></label><label>終了<input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><button disabled={busy} onClick={()=>void load()}>{busy?"更新中…":"表示を更新"}</button></div></header>{message&&<p className="studio-list-message">{message}</p>}<div className="studio-reservation-table-wrap"><table><thead><tr><th>日時</th><th>会員</th><th>予約状態</th><th>利用</th><th>精算</th><th>操作</th></tr></thead><tbody>{rows.map(row=><tr key={row.reservationId}><td><strong>{new Date(row.startAt).toLocaleString("ja-JP",{month:"numeric",day:"numeric",weekday:"short",hour:"2-digit",minute:"2-digit"})}</strong><small>〜{new Date(row.endAt).toLocaleTimeString("ja-JP",{hour:"2-digit",minute:"2-digit"})}</small></td><td><strong>{row.memberName}</strong><small>{row.memberCode}</small></td><td>{row.status}</td><td>{row.sessionStatus??"受付前"}</td><td>{row.paymentStatus??"未確定"}</td><td><button onClick={()=>onMember(row.memberCode)}>詳細・受付</button></td></tr>)}</tbody></table></div></section>;
}
