"use client";

import {FormEvent,useCallback,useEffect,useState} from "react";

type Task={id:string;title:string;description:string;status:string;priority:string;category:string;assignee:string|null;dueAt:number|null;sourceType:string|null;sourceId:string|null;memberCode:string|null;memberName:string|null;createdAt:number};
const statusLabel:Record<string,string>={OPEN:"未着手",IN_PROGRESS:"対応中",WAITING:"確認待ち",DONE:"完了",CANCELLED:"取消"};
const priorityLabel:Record<string,string>={LOW:"低",NORMAL:"通常",HIGH:"高",URGENT:"緊急"};

export function TaskPanel(){
 const [tasks,setTasks]=useState<Task[]>([]),[filter,setFilter]=useState("ACTIVE"),[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[creating,setCreating]=useState(false),[form,setForm]=useState({title:"",description:"",priority:"NORMAL",category:"GENERAL",assignee:"",dueAt:""});
 const load=useCallback(async()=>{setBusy("LOAD");setMessage("");try{const response=await fetch(`/api/v1/admin/tasks${filter?`?status=${filter}`:""}`,{cache:"no-store",signal:AbortSignal.timeout(8000)});if(response.status===401){location.replace("/member-admin/login");return}if(response.ok)setTasks((await response.json()).tasks??[]);else setMessage("タスク一覧を取得できませんでした")}catch{setMessage("タスク一覧の取得が8秒を超えました")}finally{setBusy("")}},[filter]);useEffect(()=>{void load()},[load]);
 const create=async(event:FormEvent)=>{event.preventDefault();if(!form.title.trim()||busy)return;setBusy("CREATE");setMessage("タスクを登録しています…");const response=await fetch("/api/v1/admin/tasks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,dueAt:form.dueAt?new Date(form.dueAt).getTime():null,requestId:crypto.randomUUID()})});setMessage(response.ok?"タスクを登録しました":"登録できませんでした");if(response.ok){setForm({title:"",description:"",priority:"NORMAL",category:"GENERAL",assignee:"",dueAt:""});setCreating(false);await load()}setBusy("")};
 const update=async(id:string,status:string)=>{if(busy)return;setBusy(id);setMessage("タスクを更新しています…");const response=await fetch("/api/v1/admin/tasks",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status,requestId:crypto.randomUUID()})});setMessage(response.ok?"タスクを更新しました":"更新できませんでした");if(response.ok)await load();setBusy("")};
 return <section className="operations-panel"><header><div><small>OPERATIONS TASKS</small><h2>作業タスク</h2><p>通常作業と、未精算・在庫不足・SNS投稿失敗などの要対応を一元管理します。</p></div><button onClick={()=>setCreating(value=>!value)}>{creating?"入力を閉じる":"新しいタスク"}</button></header>
  {creating&&<form className="task-form" onSubmit={create}><label>タスク名<input value={form.title} maxLength={160} required onChange={event=>setForm(v=>({...v,title:event.target.value}))}/></label><label>内容<textarea value={form.description} onChange={event=>setForm(v=>({...v,description:event.target.value}))}/></label><label>分類<select value={form.category} onChange={event=>setForm(v=>({...v,category:event.target.value}))}><option value="GENERAL">一般</option><option value="MEMBER">会員</option><option value="STUDIO">スタジオ</option><option value="ORDER">注文</option><option value="PAYMENT">精算</option><option value="INVENTORY">在庫</option><option value="SNS">SNS</option><option value="SYSTEM">システム</option></select></label><label>優先度<select value={form.priority} onChange={event=>setForm(v=>({...v,priority:event.target.value}))}><option value="LOW">低</option><option value="NORMAL">通常</option><option value="HIGH">高</option><option value="URGENT">緊急</option></select></label><label>担当者<input value={form.assignee} onChange={event=>setForm(v=>({...v,assignee:event.target.value}))}/></label><label>期限<input type="datetime-local" value={form.dueAt} onChange={event=>setForm(v=>({...v,dueAt:event.target.value}))}/></label><button disabled={busy==="CREATE"}>{busy==="CREATE"?"登録中…":"タスクを登録"}</button></form>}
  <div className="task-filter"><button className={filter==="ACTIVE"?"active":""} onClick={()=>setFilter("ACTIVE")}>対応が必要</button>{["OPEN","IN_PROGRESS","WAITING","DONE","CANCELLED"].map(status=><button className={filter===status?"active":""} key={status} onClick={()=>setFilter(status)}>{statusLabel[status]}</button>)}</div>{message&&<p className="member-admin-message" role="status">{message}</p>}
  <div className="task-list">{tasks.map(task=><article key={task.id} className={`priority-${task.priority.toLowerCase()}`}><div><span>{task.category}</span><strong>{task.title}</strong><p>{task.description||"詳細なし"}</p><small>{task.assignee?`担当 ${task.assignee} ／ `:""}{task.dueAt?`期限 ${new Date(task.dueAt).toLocaleString("ja-JP")}`:"期限なし"}{task.memberName?` ／ ${task.memberName} 様`:""}</small></div><aside><b>{priorityLabel[task.priority]}</b><em>{statusLabel[task.status]??task.status}</em>{task.status!=="DONE"&&<><button disabled={busy===task.id} onClick={()=>void update(task.id,"IN_PROGRESS")}>対応中</button><button disabled={busy===task.id} onClick={()=>void update(task.id,"DONE")}>完了</button></>}</aside></article>)}{!tasks.length&&<p className="admin-empty">該当するタスクはありません。</p>}</div>
 </section>;
}
