import { env } from "cloudflare:workers";
import { NextRequest,NextResponse } from "next/server";
import {requireAdminSession} from "@/lib/admin-session";

function admin(request:NextRequest){const email=request.headers.get("oai-authenticated-user-email")?.trim().toLowerCase(),allowed=((env as unknown as Record<string,string|undefined>).ADMIN_EMAILS??"").split(",").map(v=>v.trim().toLowerCase()).filter(Boolean);return email&&allowed.includes(email)?email:null}
const validStatus=new Set(["OPEN","IN_PROGRESS","WAITING","DONE","CANCELLED"]),validPriority=new Set(["LOW","NORMAL","HIGH","URGENT"]),validCategory=new Set(["GENERAL","MEMBER","STUDIO","ORDER","PAYMENT","INVENTORY","SNS","SYSTEM"]);

export async function GET(request:NextRequest){if(!(admin(request)??await requireAdminSession(request)))return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const status=(request.nextUrl.searchParams.get("status")??"").toUpperCase(),category=(request.nextUrl.searchParams.get("category")??"").toUpperCase();const rows=await env.DB.prepare(`SELECT t.id,t.title,t.description,t.status,t.priority,t.category,t.assignee,t.due_at AS dueAt,t.source_type AS sourceType,t.source_id AS sourceId,t.created_by AS createdBy,t.completed_at AS completedAt,t.created_at AS createdAt,t.updated_at AS updatedAt,m.member_code AS memberCode,m.display_name AS memberName FROM operations_tasks t LEFT JOIN members m ON m.id=t.member_id WHERE (?='' OR t.status=?) AND (?='' OR t.category=?) ORDER BY CASE t.status WHEN 'OPEN' THEN 0 WHEN 'IN_PROGRESS' THEN 1 WHEN 'WAITING' THEN 2 ELSE 3 END,CASE t.priority WHEN 'URGENT' THEN 0 WHEN 'HIGH' THEN 1 WHEN 'NORMAL' THEN 2 ELSE 3 END,COALESCE(t.due_at,9223372036854775807),t.created_at DESC LIMIT 500`).bind(status,status,category,category).all();return NextResponse.json({tasks:rows.results},{headers:{"Cache-Control":"no-store"}})}

export async function POST(request:NextRequest){const actor=admin(request)??await requireAdminSession(request);if(!actor)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const body=await request.json().catch(()=>null) as {title?:string;description?:string;priority?:string;category?:string;assignee?:string;dueAt?:number|null;memberCode?:string;sourceType?:string;sourceId?:string;requestId?:string}|null,title=String(body?.title??"").trim().slice(0,160),description=String(body?.description??"").trim().slice(0,2000),priority=String(body?.priority??"NORMAL").toUpperCase(),category=String(body?.category??"GENERAL").toUpperCase();if(!title||!body?.requestId||!validPriority.has(priority)||!validCategory.has(category))return NextResponse.json({error:"INVALID_REQUEST"},{status:400});const existing=await env.DB.prepare("SELECT details_json AS details FROM member_registration_events WHERE event_type='OPERATIONS_TASK_CREATED' AND details_json LIKE ? LIMIT 1").bind(`%${body.requestId}%`).first();if(existing)return NextResponse.json({ok:true,idempotent:true});const memberCode=String(body.memberCode??"").trim().toUpperCase(),member=memberCode?await env.DB.prepare("SELECT id FROM members WHERE member_code=? LIMIT 1").bind(memberCode).first<{id:string}>():null;if(memberCode&&!member)return NextResponse.json({error:"MEMBER_NOT_FOUND"},{status:404});const id=crypto.randomUUID(),now=Date.now(),dueAt=body.dueAt&&Number.isFinite(body.dueAt)?Number(body.dueAt):null;await env.DB.batch([env.DB.prepare("INSERT INTO operations_tasks (id,title,description,status,priority,category,assignee,due_at,source_type,source_id,member_id,created_by,completed_at,created_at,updated_at) VALUES (?,?,?,'OPEN',?,?,?,?,?,?,?,?,NULL,?,?)").bind(id,title,description,priority,category,String(body.assignee??"").trim().slice(0,160)||null,dueAt,String(body.sourceType??"").trim().slice(0,80)||null,String(body.sourceId??"").trim().slice(0,160)||null,member?.id??null,actor,now,now),env.DB.prepare("INSERT INTO member_registration_events (id,member_id,event_type,actor,details_json,created_at) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),member?.id??null,"OPERATIONS_TASK_CREATED",actor,JSON.stringify({requestId:body.requestId,taskId:id,title}),now)]);return NextResponse.json({ok:true,id},{status:201})}

export async function PATCH(request:NextRequest){const actor=admin(request)??await requireAdminSession(request);if(!actor)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const body=await request.json().catch(()=>null) as {id?:string;status?:string;assignee?:string;priority?:string;requestId?:string}|null,id=String(body?.id??""),status=String(body?.status??"").toUpperCase(),priority=String(body?.priority??"").toUpperCase();if(!id||!body?.requestId||(!validStatus.has(status)&&!validPriority.has(priority)&&body?.assignee===undefined))return NextResponse.json({error:"INVALID_REQUEST"},{status:400});const current=await env.DB.prepare("SELECT id,status,priority,assignee FROM operations_tasks WHERE id=? LIMIT 1").bind(id).first<{id:string;status:string;priority:string;assignee:string|null}>();if(!current)return NextResponse.json({error:"TASK_NOT_FOUND"},{status:404});const nextStatus=validStatus.has(status)?status:current.status,nextPriority=validPriority.has(priority)?priority:current.priority,nextAssignee=body.assignee===undefined?current.assignee:String(body.assignee).trim().slice(0,160)||null,now=Date.now();await env.DB.batch([env.DB.prepare("UPDATE operations_tasks SET status=?,priority=?,assignee=?,completed_at=?,updated_at=? WHERE id=?").bind(nextStatus,nextPriority,nextAssignee,nextStatus==="DONE"?now:null,now,id),env.DB.prepare("INSERT INTO member_registration_events (id,member_id,event_type,actor,details_json,created_at) VALUES (?,NULL,'OPERATIONS_TASK_UPDATED',?,?,?)").bind(crypto.randomUUID(),actor,JSON.stringify({requestId:body.requestId,taskId:id,before:current,after:{status:nextStatus,priority:nextPriority,assignee:nextAssignee}}),now)]);return NextResponse.json({ok:true,id,status:nextStatus})}

