import {env} from "cloudflare:workers";
import {NextRequest} from "next/server";
const COOKIE_NAME="cw_admin_session",MAX_AGE=60*60*8,encoder=new TextEncoder();
const settings=()=>env as unknown as Record<string,string|undefined>;
const encode=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
const decode=(value:string)=>Uint8Array.from(atob(value.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(value.length/4)*4,"=")),character=>character.charCodeAt(0));
const equal=(left:Uint8Array,right:Uint8Array)=>{if(left.length!==right.length)return false;let difference=0;for(let index=0;index<left.length;index++)difference|=left[index]^right[index];return difference===0};
async function allowedEmail(email:string){const normalized=email.trim().toLowerCase();if(settings().ADMIN_EMAILS?.split(",").map(value=>value.trim().toLowerCase()).filter(Boolean).includes(normalized))return true;try{return Boolean(await env.DB.prepare("SELECT email FROM staff_accounts WHERE email=? AND status='ACTIVE' LIMIT 1").bind(normalized).first())}catch{return false}}
async function signature(value:string){const key=await crypto.subtle.importKey("raw",encoder.encode(settings().ADMIN_SESSION_SECRET??""),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return new Uint8Array(await crypto.subtle.sign("HMAC",key,encoder.encode(value)))}
async function pbkdf2(password:string,salt:Uint8Array,iterations:number,peppered=false){const material=peppered?`${password}\0${settings().ADMIN_SESSION_SECRET??""}`:password,key=await crypto.subtle.importKey("raw",encoder.encode(material),"PBKDF2",false,["deriveBits"]),bits=await crypto.subtle.deriveBits({name:"PBKDF2",hash:"SHA-256",salt,iterations},key,256);return new Uint8Array(bits)}
export async function createAdminPasswordRecord(password:string){const salt=crypto.getRandomValues(new Uint8Array(16));return {scheme:"pbkdf2_sha256_120000",salt:encode(salt),hash:encode(await pbkdf2(password,salt,120000))}}
async function upgradeLegacyPassword(email:string,password:string){try{const record=await createAdminPasswordRecord(password),now=Date.now();await env.DB.prepare("UPDATE admin_accounts SET password_scheme=?,password_salt=?,password_hash=?,password_changed_at=?,updated_by=? WHERE email=?").bind(record.scheme,record.salt,record.hash,now,email,email).run()}catch(error){console.error("admin password scheme upgrade failed",error)}}
export async function verifyAdminPassword(email:string,password:string){if(!await allowedEmail(email)||!password)return false;try{const normalized=email.trim().toLowerCase(),account=await env.DB.prepare("SELECT password_scheme AS scheme,password_salt AS salt,password_hash AS hash FROM admin_accounts WHERE email=? LIMIT 1").bind(normalized).first<{scheme:string;salt:string;hash:string}>();if(account){const peppered=account.scheme==="pbkdf2_sha256_30000_peppered",iterations=peppered?30000:account.scheme==="pbkdf2_sha256_210000"?210000:account.scheme==="pbkdf2_sha256_120000"?120000:0;if(!iterations)return false;const valid=equal(await pbkdf2(password,decode(account.salt),iterations,peppered),decode(account.hash));if(valid&&peppered)await upgradeLegacyPassword(normalized,password);return valid}const [scheme,hashText]=(settings().ADMIN_PASSWORD_HASH??"").split("$");if(scheme!=="hmac_sha256"||!hashText)return false;const key=await crypto.subtle.importKey("raw",encoder.encode(settings().ADMIN_SESSION_SECRET??""),{name:"HMAC",hash:"SHA-256"},false,["sign"]),result=new Uint8Array(await crypto.subtle.sign("HMAC",key,encoder.encode(password)));return equal(result,decode(hashText))}catch{return false}}
export async function createAdminSession(email:string){const payload=encode(encoder.encode(JSON.stringify({email:email.trim().toLowerCase(),exp:Date.now()+MAX_AGE*1000})));return `${payload}.${encode(await signature(payload))}`}
export async function requireAdminSession(request:NextRequest){const token=request.cookies.get(COOKIE_NAME)?.value;if(!token)return null;const [payload,provided]=token.split(".");if(!payload||!provided)return null;try{if(!equal(await signature(payload),decode(provided)))return null;const parsed=JSON.parse(new TextDecoder().decode(decode(payload))) as {email?:string;exp?:number};return parsed.email&&await allowedEmail(parsed.email)&&Number(parsed.exp)>Date.now()?parsed.email:null}catch{return null}}
export const adminCookie={name:COOKIE_NAME,maxAge:MAX_AGE,options:{httpOnly:true,secure:true,sameSite:"strict" as const,path:"/"}};
