export type StoredNoticeRow={id:string;eventId?:string;eventType?:string;category:"PAYMENT"|"POINT"|"RESERVATION"|"ORDER"|"NEWS";title:string;body:string;sender:string;metadataJson?:string;readAt:number|null;occurredAt?:number;createdAt:number};

export function storedNotice(item:StoredNoticeRow){return{id:item.id,category:item.category,title:item.title,body:item.body,sender:item.sender,createdAt:new Date(item.createdAt).toLocaleString("ja-JP",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"}),unread:!item.readAt}}

function dateKey(timestamp:number){return new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(timestamp)}
function normalizedText(value:string){return value.replace(/\s+/g," ").trim()}
export function isWelcomeNotice(item:Pick<StoredNoticeRow,"eventType"|"title">){return item.eventType==="MEMBER_WELCOME"||/ポイントカード/.test(item.title)&&/(ご利用ありがとうございます|会員登録ありがとうございます|ようこそ)/.test(item.title)}
function targetKey(item:StoredNoticeRow){try{const metadata=JSON.parse(item.metadataJson||"{}") as Record<string,unknown>;for(const name of ["orderId","reservationId","paymentId","sessionId","sourceId","resourceId"]){const value=String(metadata[name]??"").trim();if(value)return `${name}:${value}`}}catch{/* 壊れた付加情報は本文による重複判定へフォールバック */}return""}
export function dedupeStoredNotices(rows:StoredNoticeRow[]){const seen=new Set<string>();return rows.filter(item=>{const timestamp=item.occurredAt??item.createdAt,date=dateKey(timestamp),isEntry=item.eventType==="ENTRY_THANK_YOU"||item.title==="COMPASSION WORLDへご来店ありがとうございます";let key:string;if(isWelcomeNotice(item))key="MEMBER_WELCOME";else if(isEntry)key=`ENTRY_THANK_YOU:${date}`;else{const target=targetKey(item);key=target?`${item.eventType??item.category}:${target}:${normalizedText(item.title)}`:`${item.eventType??item.category}:${date}:${normalizedText(item.title)}:${normalizedText(item.body)}`}if(seen.has(key))return false;seen.add(key);return true})}

export function welcomeNotice(member:{id:string;createdAt:number;cardStartedAt:number|null}){return{id:`welcome:${member.id}`,category:"NEWS" as const,title:"新しいポイントカードのご利用ありがとうございます",body:"COMPASSION WORLDの新しいポイントカードへようこそ。これまでの会員情報を引き継いだ方も、初めて登録した方も、予約・注文・会員特典をこの画面からご利用いただけます。",createdAt:new Date(member.cardStartedAt??member.createdAt).toLocaleDateString("ja-JP",{timeZone:"Asia/Tokyo"}),unread:false}}

export function memberNotices(rows:StoredNoticeRow[],member:{id:string;createdAt:number;cardStartedAt:number|null}){const unique=dedupeStoredNotices(rows);return[...unique.map(storedNotice),...(unique.some(isWelcomeNotice)?[]:[welcomeNotice(member)])]}
