import { env } from "cloudflare:workers";
import { getDb } from "@/db";
import { businessCalendar, catalogOverrides, categorySchedules, storeHours } from "@/db/schema";
import { inferMocktailPair } from "@/lib/drink-pairing";

export type OrderOptionChoice={id:string;name:string;priceDelta:number;productCode?:string};
export type OrderOptionGroup={id:string;name:string;type:"single"|"multiple";required:boolean;choices:OrderOptionChoice[]};
export type OrderProduct={id:string;code:string;name:string;category:"FOOD"|"DRINK";menuCategory:string;description:string;price:number;basePrice:number;taxDivision:string;taxRate:number;taxRounding:string;priceLabel:string;imageUrl:string;soldOut:boolean;optionGroups:OrderOptionGroup[];cocktailBase:string;cocktailMixer:string};
type SourceProduct={code:string;name:string;price:number;basePrice?:number;taxDivision?:string;taxRate?:number;taxRounding?:string;priceLabel?:string;section:string;menuCategory:string;description?:string;imageUrl?:string;soldOut?:boolean;optionGroups?:OrderOptionGroup[];displaySequence?:number;cocktailBase?:string;cocktailMixer?:string};
type CatalogResponse={ok:boolean;result?:{products?:SourceProduct[];sync?:{state?:string;completedAt?:string;storedCount?:number}}};

export async function getOrderProducts(options:{includeOverrides?:boolean;channel?:"MOBILE_ORDER"|"SELF_REGISTER"}={}){
 const runtime=env as unknown as Record<string,string|undefined>;const url=runtime.SELF_REGISTER_CATALOG_URL;
 if(!url)throw new Error("CATALOG_URL_NOT_CONFIGURED");
 const response=await fetch(url,{redirect:"follow",cache:"no-store"});if(!response.ok)throw new Error("CATALOG_UNAVAILABLE");
 const body=await response.json() as CatalogResponse;if(!body.ok||!body.result)throw new Error("CATALOG_INVALID_RESPONSE");
 let overrides:Record<string,typeof catalogOverrides.$inferSelect>={};
 let hours:typeof storeHours.$inferSelect|undefined;
 let exceptions:typeof businessCalendar.$inferSelect[]=[];
 let categoryRules:Record<string,typeof categorySchedules.$inferSelect>={};
 try{overrides=Object.fromEntries((await getDb().select().from(catalogOverrides)).map(row=>[row.productCode,row]));}catch{overrides={};}
 try{[hours]=await getDb().select().from(storeHours).limit(1);}catch{hours=undefined;}
 try{exceptions=await getDb().select().from(businessCalendar);categoryRules=Object.fromEntries((await getDb().select().from(categorySchedules)).map(row=>[row.category,row]));}catch{exceptions=[];categoryRules={};}
 const products=(body.result.products??[]).filter(product=>product.section==="kitchen"&&Boolean(product.menuCategory)).map(product=>{const override=overrides[product.code];const menuCategory=override?.menuCategory??product.menuCategory;const inferred=inferMocktailPair(product.name,menuCategory);return{id:`smaregi:${product.code}`,code:product.code,name:product.name,category:menuCategory.startsWith("food-")?"FOOD" as const:"DRINK" as const,menuCategory,description:override?.description||product.description||"",price:Number(product.price),basePrice:Number(product.basePrice??product.price),taxDivision:String(product.taxDivision??"0"),taxRate:Number(product.taxRate??0),taxRounding:String(product.taxRounding??"1"),priceLabel:product.priceLabel||"税込",imageUrl:override?.imageUrl||product.imageUrl||"",soldOut:override?.soldOut??Boolean(product.soldOut),optionGroups:product.optionGroups??[],cocktailBase:product.cocktailBase||inferred.base,cocktailMixer:product.cocktailMixer||inferred.mixer,displaySequence:override?.displaySequence??Number(product.displaySequence??999999999),showOnSelfRegister:override?.showOnSelfRegister??true,showOnMobileOrder:override?.showOnMobileOrder??true,scheduleEnabled:override?.scheduleEnabled??false,scheduleStart:override?.scheduleStart??"11:00",scheduleEnd:override?.scheduleEnd??"20:00",scheduleDays:(override?.scheduleDays??"1,2,3,4,5,6,7").split(",").map(Number),hasOverride:Boolean(override)}}).filter(product=>Number.isFinite(product.price)&&product.price>=0).sort((a,b)=>a.displaySequence-b.displaySequence||a.name.localeCompare(b.name,"ja"));
 const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",weekday:"short",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date());const value=(type:string)=>parts.find(part=>part.type===type)?.value??"";const dayMap:Record<string,number>={Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6,Sun:7};const today=dayMap[value("weekday")]??1,dateKey=`${value("year")}-${value("month")}-${value("day")}`;const nowMinutes=Number(value("hour"))*60+Number(value("minute"));const toMinutes=(time:string)=>{const [hour,minute]=time.split(":").map(Number);return hour*60+minute};const within=(start:string,end:string)=>{const from=toMinutes(start),to=toMinutes(end);return from<=to?nowMinutes>=from&&nowMinutes<to:nowMinutes>=from||nowMinutes<to};const exception=exceptions.find(item=>item.date===dateKey);const defaultOpen=!hours||(hours.enabled&&((hours.lunchEnabled&&hours.lunchDays.split(",").map(Number).includes(today)&&within(hours.lunchStart,hours.lunchLastOrder))||(hours.dinnerEnabled&&hours.dinnerDays.split(",").map(Number).includes(today)&&within(hours.dinnerStart,hours.dinnerLastOrder))));const storeOpen=exception?.status==="CLOSED"?false:exception&&exception.status!=="DEFAULT"?((exception.lunchEnabled&&within(exception.lunchStart,exception.lunchEnd))||(exception.dinnerEnabled&&within(exception.dinnerStart,exception.dinnerEnd))):defaultOpen;
 const visible=options.includeOverrides?products:products.filter(product=>{const categoryRule=categoryRules[product.menuCategory];const scheduleOpen=product.scheduleEnabled?product.scheduleDays.includes(today)&&within(product.scheduleStart,product.scheduleEnd):!categoryRule?.enabled||(categoryRule.days.split(",").map(Number).includes(today)&&within(categoryRule.startTime,categoryRule.endTime));return(options.channel==="SELF_REGISTER"?product.showOnSelfRegister:product.showOnMobileOrder)&&storeOpen&&scheduleOpen});
 return{products:visible.map(product=>options.includeOverrides?product:((({displaySequence,showOnSelfRegister,showOnMobileOrder,hasOverride,...publicProduct})=>publicProduct)(product))),sync:body.result.sync??{}};
}
