"use client";
import { ArrowLeft, CalendarDays, CheckCircle2, Clock3 } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";

declare global { interface Window { liff?: {init(c:{liffId:string}):Promise<void>;isLoggedIn():boolean;login(c?:{redirectUri?:string}):void;getAccessToken():string|null} } }
type Slot={startAt:number;label:string;available:boolean};
type Day={date:string;opensAt:number;closesAt:number;slots:Slot[];minDate:string;maxDate:string};
type Reservation={id:string;startsAt:number;endsAt:number;status:string};
type TimeBand="MORNING"|"AFTERNOON"|"NIGHT";
const timeBands:[TimeBand,string,string][]=[["MORNING","午前","8:00〜12:00"],["AFTERNOON","午後","12:00〜18:00"],["NIGHT","夜間","18:00〜翌2:00"]];
function slotHour(value:number){return Number(new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",hour:"2-digit",hourCycle:"h23"}).format(value))}
function inBand(slot:Slot,band:TimeBand){const hour=slotHour(slot.startAt);return band==="MORNING"?hour>=8&&hour<12:band==="AFTERNOON"?hour>=12&&hour<18:hour>=18||hour<2}

function loadLiff(){return new Promise<void>((resolve,reject)=>{if(window.liff)return resolve();const script=document.createElement("script");script.src="https://static.line-scdn.net/liff/edge/2/sdk.js";script.onload=()=>resolve();script.onerror=()=>reject(new Error("LINE認証を読み込めませんでした"));document.head.appendChild(script)})}
function localDate(value:number){return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",month:"numeric",day:"numeric",weekday:"short",hour:"2-digit",minute:"2-digit"}).format(value)}

export default function AvailabilityPage(){
 const [token,setToken]=useState(""),[day,setDay]=useState<Day|null>(null),[date,setDate]=useState(""),[band,setBand]=useState<TimeBand|null>(null),[selected,setSelected]=useState<Slot|null>(null),[duration,setDuration]=useState(1),[reservations,setReservations]=useState<Reservation[]>([]),[message,setMessage]=useState("会員情報を確認しています…"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
 const authHeaders=useMemo(()=>token?{Authorization:`Bearer ${token}`} as Record<string,string>:undefined,[token]);
 const visibleSlots=useMemo(()=>band?day?.slots.filter(slot=>inBand(slot,band))??[]:[],[band,day]);
 const loadDay=useCallback(async(target:string)=>{if(!target)return;setLoading(true);setBand(null);setSelected(null);setMessage("空き状況を確認しています…");try{const response=await fetch(`/api/v1/availability?date=${encodeURIComponent(target)}`,{cache:"no-store"}),result=await response.json();if(!response.ok)throw new Error(result.message??"空き状況を取得できませんでした");setDay(result);setMessage("")}catch(error){setMessage(error instanceof Error?error.message:"空き状況を取得できませんでした")}finally{setLoading(false)}},[]);
 useEffect(()=>{void(async()=>{try{const config=await fetch("/api/v1/client-config").then(r=>r.json()),liffId=String(config.liffId??"");if(!liffId)throw new Error("LINE認証を準備できませんでした");await loadLiff();await window.liff!.init({liffId});if(!window.liff!.isLoggedIn()){window.liff!.login({redirectUri:location.href});return}const accessToken=window.liff!.getAccessToken();if(!accessToken)throw new Error("LINE認証を確認できませんでした");setToken(accessToken);const range=await fetch("/api/v1/availability/range").then(r=>r.json()).catch(()=>null);const today=range?.minDate??new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Tokyo"}).format(new Date());setDate(today);const history=await fetch("/api/v1/reservations",{headers:{Authorization:`Bearer ${accessToken}`}}).then(r=>r.ok?r.json():{reservations:[]});setReservations(history.reservations??[]);await loadDay(today)}catch(error){setLoading(false);setMessage(error instanceof Error?error.message:"予約画面を開けませんでした")}})()},[loadDay]);
 async function reserve(){if(!selected||!authHeaders||saving)return;setSaving(true);setMessage("予約内容を確認しています…");try{const response=await fetch("/api/v1/reservations",{method:"POST",headers:{...authHeaders,"Content-Type":"application/json"},body:JSON.stringify({startAt:new Date(selected.startAt).toISOString(),durationHours:duration,requestId:crypto.randomUUID()})}),result=await response.json();if(!response.ok)throw new Error(result.error==="TIME_NOT_AVAILABLE"?"選択した時間は直前に予約不可となりました。別の時間をお選びください。":"予約を確定できませんでした");setReservations(current=>[{id:result.reservationId,startsAt:result.startsAt,endsAt:result.endsAt,status:result.status},...current]);setSelected(null);setMessage("予約を確定しました");await loadDay(date)}catch(error){setMessage(error instanceof Error?error.message:"予約を確定できませんでした")}finally{setSaving(false)}}
 return <main className="booking-shell internal-booking"><header className="booking-head"><div><small>MUSIC STUDIO</small><h1>FEBBRAIO</h1></div><a href="/"><ArrowLeft size={15}/> 会員証トップへ戻る</a></header><section className="booking-intro"><p>STUDIO RESERVATION</p><h2>スタジオ予約</h2><span>利用日と時間帯を選んだあと、開始時刻を15分単位で選択できます。</span></section><section className="booking-date-card"><label><CalendarDays size={18}/><span>利用日</span><input type="date" value={date} min={day?.minDate} max={day?.maxDate} onChange={event=>{setDate(event.target.value);void loadDay(event.target.value)}}/></label></section><section className="booking-time-band"><header><small>TIME ZONE</small><h2>時間帯を選ぶ</h2></header><div>{timeBands.map(([key,label,time])=>{const slots=day?.slots.filter(slot=>inBand(slot,key))??[],available=slots.filter(slot=>slot.available).length;return <button key={key} disabled={loading||slots.length===0} className={band===key?"selected":""} onClick={()=>{setBand(key);setSelected(null)}}><strong>{label}</strong><span>{time}</span><small>{available?`${available}枠予約可能`:"予約不可"}</small></button>})}</div></section>{band&&<section className="booking-slots"><header><div><small>START TIME</small><h2>開始時刻を選ぶ</h2></div><span><i/>予約可能　<i/>予約不可</span></header>{loading?<p className="booking-state">{message}</p>:visibleSlots.length?<div className="quarter-slot-grid">{visibleSlots.map(slot=><button key={slot.startAt} disabled={!slot.available} className={selected?.startAt===slot.startAt?"selected":""} onClick={()=>setSelected(slot)}>{slot.label}<small>{slot.available?"選択":"予約不可"}</small></button>)}</div>:<p className="booking-state">この時間帯に予約枠はありません</p>}</section>}{!band&&!loading&&<p className="booking-band-guide">午前・午後・夜間から、ご希望の時間帯を選択してください。</p>}{selected&&<section className="booking-confirm"><div><Clock3 size={20}/><span><small>選択中</small><strong>{localDate(selected.startAt)}から</strong></span></div><label>利用時間<select value={duration} onChange={event=>setDuration(Number(event.target.value))}>{Array.from({length:10},(_,index)=><option key={index+1} value={index+1}>{index+1}時間</option>)}</select></label><button disabled={saving} onClick={reserve}>{saving?"予約を確定しています…":"この内容で予約する"}</button></section>}{message&&!loading&&<p className={`booking-message ${message.includes("確定しました")?"success":""}`}>{message.includes("確定しました")&&<CheckCircle2 size={16}/>} {message}</p>}<section className="booking-history"><header><small>MY RESERVATIONS</small><h2>予約履歴</h2></header>{reservations.length?reservations.map(item=><article key={item.id}><b>{item.status==="CONFIRMED"?"予約確定":item.status==="CANCELLED"?"キャンセル":"ご利用済み"}</b><span><strong>{localDate(item.startsAt)}</strong><small>〜 {new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",hour:"2-digit",minute:"2-digit"}).format(item.endsAt)}</small></span></article>):<p className="booking-state">予約履歴はありません</p>}</section></main>
}
