import {env} from "cloudflare:workers";
import {NextRequest,NextResponse} from "next/server";
import {requireAdminSession} from "@/lib/admin-session";

type Body=Record<string,unknown>;
const runtime=()=>env as unknown as Record<string,string|undefined>;
function headerAdmin(request:NextRequest){const email=request.headers.get("oai-authenticated-user-email")?.trim().toLowerCase(),allowed=(runtime().ADMIN_EMAILS??"").split(",").map(value=>value.trim().toLowerCase()).filter(Boolean);return email&&allowed.includes(email)?email:null}
async function actor(request:NextRequest){return headerAdmin(request)??await requireAdminSession(request)}
function endpoint(){const settings=runtime();return {url:settings.SMAREGI_PRODUCT_MASTER_URL??settings.SMAREGI_PRODUCT_CREATE_URL??settings.SMAREGI_SPEND_RECALC_URL??settings.SELF_REGISTER_CATALOG_URL,token:settings.SMAREGI_PRODUCT_API_TOKEN??settings.SMAREGI_SPEND_SYNC_KEY??settings.SELF_REGISTER_POS_API_TOKEN}}
function textValue(value:unknown,max:number){return String(value??"").trim().slice(0,max)}
function productData(body:Body){return {productCode:textValue(body.productCode,40),name:textValue(body.name,120),janCode:textValue(body.janCode,40)||null,priceExcludingTax:Math.max(0,Math.round(Number(body.priceExcludingTax)||0)),costPrice:body.costPrice===""||body.costPrice==null?null:Math.max(0,Math.round(Number(body.costPrice)||0)),taxRate:[8,10].includes(Number(body.taxRate))?Number(body.taxRate):10,category:textValue(body.category,80)||"FOOD",pointEligible:body.pointEligible!==false,active:body.active!==false,saleStartsAt:body.saleStartsAt||null,saleEndsAt:body.saleEndsAt||null}}
function valid(data:ReturnType<typeof productData>,requestId:string){return Boolean(requestId&&/^[A-Za-z0-9_-]{1,40}$/.test(data.productCode)&&data.name&&data.name.length<=120&&(!data.janCode||/^[A-Za-z0-9_-]{1,40}$/.test(data.janCode)))}
async function forward(action:"product.create"|"product.update"|"product.status",requestId:string,data:ReturnType<typeof productData>){const connection=endpoint();if(!connection.url||!connection.token)return {response:NextResponse.json({error:"PRODUCT_MASTER_API_NOT_CONNECTED",message:"セルフレジ側の商品マスタ管理APIを接続してください"},{status:503}),result:null};try{const upstream=await fetch(connection.url,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":requestId},body:JSON.stringify({version:2,action,requestId,apiToken:connection.token,data}),signal:AbortSignal.timeout(15_000)}),result=await upstream.json().catch(()=>({}));if(!upstream.ok||result?.ok===false)return {response:NextResponse.json({error:"PRODUCT_MASTER_UPDATE_FAILED",message:result?.error==="SMAREGI_PRODUCT_WRITE_SCOPE_REQUIRED"?"スマレジ・アプリへ商品編集権限を追加してください":"スマレジへ反映できませんでした",detail:result},{status:502}),result:null};return {response:null,result:result?.result??result}}catch(error){return {response:NextResponse.json({error:"PRODUCT_MASTER_UNAVAILABLE",message:error instanceof Error&&error.name==="TimeoutError"?"スマレジとの通信がタイムアウトしました。再試行してください":"スマレジへ接続できませんでした"},{status:502}),result:null}}}
async function audit(eventType:string,who:string,requestId:string,data:ReturnType<typeof productData>){await env.DB.prepare("INSERT INTO member_registration_events (id,member_id,event_type,actor,details_json,created_at) VALUES (?,NULL,?,?,?,?)").bind(crypto.randomUUID(),eventType,who,JSON.stringify({requestId,productCode:data.productCode,name:data.name,active:data.active}),Date.now()).run()}

export async function GET(request:NextRequest){if(!await actor(request))return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const connection=endpoint();return NextResponse.json({configured:Boolean(connection.url&&connection.token),capabilities:{create:true,update:true,suspend:true,restore:true,hardDelete:false},autoSyncMinutes:5,source:"SMAREGI",message:connection.url&&connection.token?"スマレジ商品マスタ管理API接続済み":"セルフレジ側の商品マスタ管理API接続待ち"},{headers:{"Cache-Control":"no-store"}})}
export async function POST(request:NextRequest){const who=await actor(request);if(!who)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const body=await request.json().catch(()=>null) as Body|null,requestId=textValue(body?.requestId,100),data=productData(body??{});if(!valid(data,requestId))return NextResponse.json({error:"INVALID_INPUT",message:"商品コード・商品名・JANを確認してください"},{status:400});const forwarded=await forward("product.create",requestId,data);if(forwarded.response)return forwarded.response;await audit("PRODUCT_MASTER_CREATED",who,requestId,data);return NextResponse.json({ok:true,result:forwarded.result},{status:201})}
export async function PUT(request:NextRequest){const who=await actor(request);if(!who)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const body=await request.json().catch(()=>null) as Body|null,requestId=textValue(body?.requestId,100),data=productData(body??{});if(!valid(data,requestId))return NextResponse.json({error:"INVALID_INPUT",message:"商品コード・商品名・JANを確認してください"},{status:400});const forwarded=await forward("product.update",requestId,data);if(forwarded.response)return forwarded.response;await audit("PRODUCT_MASTER_UPDATED",who,requestId,data);return NextResponse.json({ok:true,result:forwarded.result})}
export async function PATCH(request:NextRequest){const who=await actor(request);if(!who)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const body=await request.json().catch(()=>null) as Body|null,requestId=textValue(body?.requestId,100),data=productData(body??{});if(!valid(data,requestId))return NextResponse.json({error:"INVALID_INPUT",message:"商品情報を確認してください"},{status:400});const forwarded=await forward("product.status",requestId,data);if(forwarded.response)return forwarded.response;await audit(data.active?"PRODUCT_MASTER_RESTORED":"PRODUCT_MASTER_SUSPENDED",who,requestId,data);return NextResponse.json({ok:true,result:forwarded.result})}
