import { env } from "cloudflare:workers";
import { NextRequest, NextResponse } from "next/server";
import {requireAdminSession} from "@/lib/admin-session";
import { getDb } from "@/db";
import { businessCalendar, storeHours } from "@/db/schema";

const defaults={id:"AOZORA_KITCHEN",enabled:true,timezone:"Asia/Tokyo",openTime:"11:30",closeTime:"22:00",orderStart:"11:30",lastOrder:"21:30",businessDays:"2,3,4,5,6,7",lunchEnabled:true,lunchStart:"11:30",lunchEnd:"14:00",lunchLastOrder:"13:30",lunchDays:"2,3,4,5,6,7",dinnerEnabled:true,dinnerStart:"17:30",dinnerEnd:"22:00",dinnerLastOrder:"21:30",dinnerDays:"6",eventDinnerEnabled:true};
function adminEmail(request:NextRequest){const email=request.headers.get("oai-authenticated-user-email")?.toLowerCase();const allowed=((env as unknown as Record<string,string|undefined>).ADMIN_EMAILS??"").split(",").map(v=>v.trim().toLowerCase()).filter(Boolean);return email&&allowed.includes(email)?email:null}
function time(value:unknown,fallback:string){return typeof value==="string"&&/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(value)?value:fallback}
function days(value:unknown,fallback:string){const list=Array.isArray(value)?value.map(Number).filter(v=>v>=1&&v<=7):[];return [...new Set(list)].sort().join(",")||fallback}
const exposed=(row:typeof storeHours.$inferSelect|typeof defaults)=>({...row,businessDays:String(row.businessDays).split(",").map(Number),lunchDays:String(row.lunchDays).split(",").map(Number),dinnerDays:String(row.dinnerDays).split(",").map(Number)});

export async function GET(request:NextRequest){if(!(adminEmail(request)??await requireAdminSession(request)))return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const [saved]=await getDb().select().from(storeHours).limit(1);const exceptions=await getDb().select().from(businessCalendar);return NextResponse.json({hours:exposed(saved??defaults),exceptions},{headers:{"Cache-Control":"no-store"}})}
export async function PUT(request:NextRequest){const email=adminEmail(request)??await requireAdminSession(request);if(!email)return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return NextResponse.json({error:"INVALID_INPUT"},{status:400});if(body.kind==="EXCEPTION"){const date=typeof body.date==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(body.date)?body.date:"";const status=["DEFAULT","CLOSED","CUSTOM","EVENT","CONTINUOUS"].includes(String(body.status))?String(body.status) as "DEFAULT"|"CLOSED"|"CUSTOM"|"EVENT"|"CONTINUOUS":"DEFAULT";if(!date)return NextResponse.json({error:"INVALID_DATE"},{status:400});const values={date,status,lunchEnabled:body.lunchEnabled!==false,dinnerEnabled:body.dinnerEnabled===true,lunchStart:time(body.lunchStart,defaults.lunchStart),lunchEnd:time(body.lunchEnd,defaults.lunchEnd),dinnerStart:time(body.dinnerStart,defaults.dinnerStart),dinnerEnd:time(body.dinnerEnd,defaults.dinnerEnd),continuousStart:time(body.continuousStart,defaults.lunchStart),continuousEnd:time(body.continuousEnd,defaults.dinnerEnd),continuousLastOrder:time(body.continuousLastOrder,defaults.dinnerLastOrder),note:typeof body.note==="string"?body.note.trim().slice(0,120):"",updatedBy:email,updatedAt:new Date()};await getDb().insert(businessCalendar).values(values).onConflictDoUpdate({target:businessCalendar.date,set:values});return NextResponse.json({saved:values})}const values={id:defaults.id,enabled:body.enabled!==false,timezone:"Asia/Tokyo",openTime:time(body.lunchStart,defaults.lunchStart),closeTime:time(body.dinnerEnd,defaults.dinnerEnd),orderStart:time(body.lunchStart,defaults.lunchStart),lastOrder:time(body.dinnerLastOrder,defaults.dinnerLastOrder),businessDays:days(body.lunchDays,defaults.businessDays),lunchEnabled:body.lunchEnabled!==false,lunchStart:time(body.lunchStart,defaults.lunchStart),lunchEnd:time(body.lunchEnd,defaults.lunchEnd),lunchLastOrder:time(body.lunchLastOrder,defaults.lunchLastOrder),lunchDays:days(body.lunchDays,defaults.lunchDays),dinnerEnabled:body.dinnerEnabled!==false,dinnerStart:time(body.dinnerStart,defaults.dinnerStart),dinnerEnd:time(body.dinnerEnd,defaults.dinnerEnd),dinnerLastOrder:time(body.dinnerLastOrder,defaults.dinnerLastOrder),dinnerDays:days(body.dinnerDays,defaults.dinnerDays),eventDinnerEnabled:body.eventDinnerEnabled!==false,updatedBy:email,updatedAt:new Date()};await getDb().insert(storeHours).values(values).onConflictDoUpdate({target:storeHours.id,set:values});return NextResponse.json({saved:exposed(values)})}



