import { env } from "cloudflare:workers";
import { NextRequest,NextResponse } from "next/server";
import { importedResidentStatus } from "@/lib/member-rank";

type ImportRow={sourceRow:number;memberCode?:string;lineUserId?:string;displayName?:string;displayNameKana?:string;lineDisplayName?:string;phone?:string;email?:string;birthDate?:string;gender?:string;postalCode?:string;prefecture?:string;address?:string;points?:number;rank?:string;registeredAt?:string;acquisitionSource?:string;tags?:string};
const clean=(value:unknown,max=240)=>typeof value==="string"?value.trim().slice(0,max):"";
export async function POST(request:NextRequest){
 const actor=request.headers.get("oai-authenticated-user-email")?.trim().toLowerCase();
 const body=await request.json().catch(()=>null) as {rows?:ImportRow[];requestId?:string}|null;
 if(!actor||!Array.isArray(body?.rows)||body.rows.length<1||body.rows.length>50||!body.requestId)return NextResponse.json({error:"INVALID_REQUEST"},{status:400});
 const unknown=body.rows.map(row=>clean(row.rank,40)).filter(rank=>rank&&importedResidentStatus(rank)===null);if(unknown.length)return NextResponse.json({error:"UNKNOWN_MEMBERSHIP_TYPE"},{status:400});
 const now=Date.now();let added=0,completed=0,unregistered=0,skipped=0;
 for(const row of body.rows){const code=clean(row.memberCode,10).toUpperCase(),lineUserId=clean(row.lineUserId,80);
  if(code&&/^[A-Z0-9]{10}$/.test(code)){const existed=await env.DB.prepare("SELECT id FROM members WHERE member_code=?").bind(code).first();
   await env.DB.batch([env.DB.prepare(`INSERT INTO members (id,member_code,display_name,display_name_kana,line_display_name,phone,email,birth_date,gender,postal_code,prefecture,address,points_balance,member_rank,resident_status,resident_checked_at,status,source_system,source_customer_id,acquisition_source,legacy_tags,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'L_MEMBERS',?,?,?,?,?) ON CONFLICT(member_code) DO UPDATE SET display_name=CASE WHEN members.display_name IS NULL OR TRIM(members.display_name)='' OR members.display_name='名称未登録' THEN excluded.display_name ELSE members.display_name END,display_name_kana=COALESCE(NULLIF(members.display_name_kana,''),excluded.display_name_kana),line_display_name=COALESCE(NULLIF(excluded.line_display_name,''),members.line_display_name),phone=COALESCE(NULLIF(members.phone,''),excluded.phone),email=COALESCE(NULLIF(members.email,''),excluded.email),birth_date=COALESCE(NULLIF(members.birth_date,''),excluded.birth_date),gender=COALESCE(NULLIF(members.gender,''),excluded.gender),postal_code=COALESCE(NULLIF(members.postal_code,''),excluded.postal_code),prefecture=COALESCE(NULLIF(members.prefecture,''),excluded.prefecture),address=COALESCE(NULLIF(members.address,''),excluded.address),resident_status=CASE WHEN members.resident_status IS NULL OR members.resident_status='UNKNOWN' THEN excluded.resident_status ELSE members.resident_status END,resident_checked_at=excluded.resident_checked_at,acquisition_source=COALESCE(NULLIF(excluded.acquisition_source,''),members.acquisition_source),legacy_tags=COALESCE(NULLIF(excluded.legacy_tags,''),members.legacy_tags),updated_at=excluded.updated_at`).bind(`legacy:${code}`,code,clean(row.displayName,120)||"名称未登録",clean(row.displayNameKana,120)||null,clean(row.lineDisplayName,120)||null,clean(row.phone,40)||null,clean(row.email,160)||null,clean(row.birthDate,20)||null,clean(row.gender,20)||null,clean(row.postalCode,16)||null,clean(row.prefecture,40)||null,clean(row.address,240)||null,Math.max(0,Number(row.points)||0),"STANDARD",importedResidentStatus(row.rank)??"UNKNOWN",now,"ACTIVE",code,clean(row.acquisitionSource,120)||null,clean(row.tags,500)||null,now,now),...(lineUserId?[env.DB.prepare(`INSERT INTO identity_links (id,member_id,provider,provider_user_id,linked_at,revoked_at) VALUES (?,(SELECT id FROM members WHERE member_code=?),'LINE',?,?,NULL) ON CONFLICT(provider,provider_user_id) DO UPDATE SET member_id=excluded.member_id,linked_at=excluded.linked_at,revoked_at=NULL`).bind(`line:${lineUserId}`,code,lineUserId,now)]:[])]);existed?completed++:added++;
  }else if(lineUserId){await env.DB.prepare(`INSERT INTO legacy_member_imports (id,line_user_id,display_name,display_name_kana,line_display_name,phone,email,birth_date,gender,postal_code,prefecture,address,source_registered_at,acquisition_source,legacy_tags,status,imported_at,migrated_member_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,'UNREGISTERED',?,NULL) ON CONFLICT(line_user_id) DO UPDATE SET display_name=COALESCE(NULLIF(legacy_member_imports.display_name,''),excluded.display_name),display_name_kana=COALESCE(NULLIF(legacy_member_imports.display_name_kana,''),excluded.display_name_kana),line_display_name=COALESCE(NULLIF(excluded.line_display_name,''),legacy_member_imports.line_display_name),phone=COALESCE(NULLIF(legacy_member_imports.phone,''),excluded.phone),email=COALESCE(NULLIF(legacy_member_imports.email,''),excluded.email),birth_date=COALESCE(NULLIF(legacy_member_imports.birth_date,''),excluded.birth_date),gender=COALESCE(NULLIF(legacy_member_imports.gender,''),excluded.gender),postal_code=COALESCE(NULLIF(legacy_member_imports.postal_code,''),excluded.postal_code),prefecture=COALESCE(NULLIF(legacy_member_imports.prefecture,''),excluded.prefecture),address=COALESCE(NULLIF(legacy_member_imports.address,''),excluded.address),source_registered_at=COALESCE(NULLIF(legacy_member_imports.source_registered_at,''),excluded.source_registered_at),acquisition_source=COALESCE(NULLIF(excluded.acquisition_source,''),legacy_member_imports.acquisition_source),legacy_tags=COALESCE(NULLIF(excluded.legacy_tags,''),legacy_member_imports.legacy_tags),imported_at=excluded.imported_at`).bind(`legacy-line:${lineUserId}`,lineUserId,clean(row.displayName,120)||null,clean(row.displayNameKana,120)||null,clean(row.lineDisplayName,120)||null,clean(row.phone,40)||null,clean(row.email,160)||null,clean(row.birthDate,20)||null,clean(row.gender,20)||null,clean(row.postalCode,16)||null,clean(row.prefecture,40)||null,clean(row.address,240)||null,clean(row.registeredAt,40)||null,clean(row.acquisitionSource,120)||null,clean(row.tags,500)||null,now).run();unregistered++}else skipped++;
 }
 await env.DB.prepare("INSERT INTO member_registration_events (id,member_id,event_type,actor,details_json,created_at) VALUES (?,NULL,'CSV_GAP_COMPLETION',?,?,?)").bind(crypto.randomUUID(),actor,JSON.stringify({requestId:body.requestId,rows:body.rows.length,added,completed,unregistered,skipped}),now).run();
 return NextResponse.json({added,completed,unregistered,skipped,total:body.rows.length});
}
