import { env } from "cloudflare:workers";
import { NextRequest,NextResponse } from "next/server";
import { getOrderProducts } from "@/lib/order-catalog";
import { requirePosToken } from "@/lib/pos-api";
import { expireStaleLocks,expireStaleOrder,orderDetails,PAYMENT_LOCK_TTL_MS,PosOrderRow } from "@/lib/order-pos";

type Body={requestId?:string;deviceId?:string};
const valid=(value:string)=>/^[A-Za-z0-9._:-]{3,100}$/.test(value);

export async function POST(request:NextRequest,{params}:{params:Promise<{id:string}>}){
 if(!await requirePosToken(request))return NextResponse.json({ok:false,error:"UNAUTHORIZED"},{status:401});
 const {id}=await params;const body=await request.json().catch(()=>null) as Body|null;const requestId=body?.requestId?.trim()??"",deviceId=body?.deviceId?.trim()??"";if(!valid(requestId)||!valid(deviceId))return NextResponse.json({ok:false,error:"INVALID_REQUEST"},{status:400});
 await expireStaleLocks(id);await expireStaleOrder(id);
 const replay=await env.DB.prepare(`SELECT id AS lockId,locked_at AS lockedAt,expires_at AS expiresAt,status,device_id AS deviceId FROM order_payment_locks WHERE request_id=?`).bind(requestId).first<{lockId:string;lockedAt:number;expiresAt:number;status:string;deviceId:string}>();if(replay){if(replay.deviceId!==deviceId)return NextResponse.json({ok:false,error:"LOCK_NOT_OWNED"},{status:409});const replayOrder=await env.DB.prepare(`SELECT o.id,o.order_number AS orderNumber,m.member_code AS memberCode,o.status,o.created_at AS createdAt,o.expires_at AS expiresAt,o.pickup_at AS pickupRequestedAt,o.total_including_tax AS totalIncludingTax,o.smaregi_transaction_id AS smaregiTransactionId FROM orders o JOIN members m ON m.id=o.member_id WHERE o.id=?`).bind(id).first<PosOrderRow>();if(!replayOrder)return NextResponse.json({ok:false,error:"ORDER_NOT_FOUND"},{status:404});return NextResponse.json({ok:true,lockId:replay.lockId,lockedAt:new Date(replay.lockedAt).toISOString(),expiresAt:new Date(replay.expiresAt).toISOString(),idempotentReplay:true,order:await orderDetails(replayOrder)});}
 const order=await env.DB.prepare(`SELECT o.id,o.order_number AS orderNumber,m.member_code AS memberCode,o.status,o.created_at AS createdAt,o.expires_at AS expiresAt,o.pickup_at AS pickupRequestedAt,o.total_including_tax AS totalIncludingTax,o.smaregi_transaction_id AS smaregiTransactionId FROM orders o JOIN members m ON m.id=o.member_id WHERE o.id=?`).bind(id).first<PosOrderRow>();if(!order)return NextResponse.json({ok:false,error:"ORDER_NOT_FOUND"},{status:404});if(order.status==="PAID")return NextResponse.json({ok:false,error:"ORDER_ALREADY_PAID"},{status:409});if(order.status==="EXPIRED")return NextResponse.json({ok:false,error:"ORDER_EXPIRED"},{status:410});if(order.status==="CANCELLED")return NextResponse.json({ok:false,error:"ORDER_CANCELLED"},{status:409});if(order.status!=="WAITING_STORE_PAYMENT")return NextResponse.json({ok:false,error:"ORDER_LOCKED"},{status:409});
 const active=await env.DB.prepare(`SELECT id,expires_at AS expiresAt FROM order_payment_locks WHERE order_id=? AND status='ACTIVE' AND expires_at>?`).bind(id,Date.now()).first();if(active)return NextResponse.json({ok:false,error:"ORDER_LOCKED"},{status:409});
 const stored=await env.DB.prepare(`SELECT product_code AS productCode,unit_price_including_tax AS price,quantity FROM order_items WHERE order_id=?`).bind(id).all<{productCode:string;price:number;quantity:number}>();let catalog;try{catalog=(await getOrderProducts({channel:"SELF_REGISTER",timeoutMs:3_000,allowSnapshotFallback:true})).products}catch{return NextResponse.json({ok:false,error:"PRODUCT_UNAVAILABLE",message:"商品情報を再確認できません"},{status:503})}for(const item of stored.results){const current=catalog.find(product=>product.code===item.productCode);if(!current)return NextResponse.json({ok:false,error:"PRODUCT_UNAVAILABLE",productCode:item.productCode},{status:409});if(current.soldOut)return NextResponse.json({ok:false,error:"PRODUCT_SOLD_OUT",productCode:item.productCode},{status:409});if(current.price!==item.price)return NextResponse.json({ok:false,error:"PRICE_CHANGED",productCode:item.productCode,orderedPrice:item.price,currentPrice:current.price},{status:409});if(!Number.isInteger(item.quantity)||item.quantity<1)return NextResponse.json({ok:false,error:"PRODUCT_UNAVAILABLE",productCode:item.productCode},{status:409});}
 const now=Date.now(),expiresAt=now+PAYMENT_LOCK_TTL_MS,lockId=`lock_${crypto.randomUUID()}`;const changed=await env.DB.prepare(`UPDATE orders SET status='PAYMENT_PROCESSING',updated_at=? WHERE id=? AND status='WAITING_STORE_PAYMENT'`).bind(now,id).run();if((changed.meta.changes??0)!==1)return NextResponse.json({ok:false,error:"ORDER_LOCKED"},{status:409});await env.DB.prepare(`INSERT INTO order_payment_locks (id,order_id,request_id,device_id,status,locked_at,expires_at) VALUES (?,?,?,?,'ACTIVE',?,?)`).bind(lockId,id,requestId,deviceId,now,expiresAt).run();
 const confirmed={...order,status:"PAYMENT_PROCESSING"};return NextResponse.json({ok:true,lockId,lockedAt:new Date(now).toISOString(),expiresAt:new Date(expiresAt).toISOString(),idempotentReplay:false,order:await orderDetails(confirmed)});
}
