import {env} from "cloudflare:workers";
import {NextRequest,NextResponse} from "next/server";
import {requireAdminSession} from "@/lib/admin-session";
const roles=["ADMIN","STORE","KITCHEN","VIEWER"] as const;
const hex=(bytes:Uint8Array)=>[...bytes].map(value=>value.toString(16).padStart(2,"0")).join("");
async function digest(value:string){return hex(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value))))}
async function manager(request:NextRequest){const email=await requireAdminSession(request);if(!email)return null;const owners=((env as unknown as Record<string,string|undefined>).ADMIN_EMAILS??"").split(",").map(v=>v.trim().toLowerCase());if(owners.includes(email))return email;const row=await env.DB.prepare("SELECT role,status FROM staff_accounts WHERE email=? LIMIT 1").bind(email).first<{role:string;status:string}>();return row?.status==="ACTIVE"&&row.role==="ADMIN"?email:null}
export async function GET(request:NextRequest){if(!await manager(request))return NextResponse.json({error:"FORBIDDEN"},{status:403});const rows=await env.DB.prepare("SELECT email,display_name AS displayName,role,status,invited_by AS invitedBy,invited_at AS invitedAt,invite_expires_at AS inviteExpiresAt,accepted_at AS acceptedAt,last_login_at AS lastLoginAt FROM staff_accounts ORDER BY CASE status WHEN 'ACTIVE' THEN 0 WHEN 'INVITED' THEN 1 ELSE 2 END,display_name").all();return NextResponse.json({staff:rows.results},{headers:{"Cache-Control":"no-store"}})}
export async function POST(request:NextRequest){const actor=await manager(request);if(!actor)return NextResponse.json({error:"FORBIDDEN"},{status:403});const body=await request.json().catch(()=>null) as {email?:string;displayName?:string;role?:string}|null,email=String(body?.email??"").trim().toLowerCase(),displayName=String(body?.displayName??"").trim().slice(0,80),role=String(body?.role??"STORE");if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!displayName||!roles.includes(role as typeof roles[number]))return NextResponse.json({error:"INVALID_INPUT"},{status:400});const token=crypto.randomUUID()+crypto.randomUUID().replace(/-/g,""),hash=await digest(token),now=Date.now(),expiresAt=now+72*3600000;await env.DB.batch([env.DB.prepare("INSERT INTO staff_accounts (email,display_name,role,status,invite_token_hash,invite_expires_at,invited_by,invited_at,accepted_at,last_login_at,updated_at) VALUES (?,?,?,'INVITED',?,?,?,?,NULL,NULL,?) ON CONFLICT(email) DO UPDATE SET display_name=excluded.display_name,role=excluded.role,status='INVITED',invite_token_hash=excluded.invite_token_hash,invite_expires_at=excluded.invite_expires_at,invited_by=excluded.invited_by,invited_at=excluded.invited_at,updated_at=excluded.updated_at").bind(email,displayName,role,hash,expiresAt,actor,now,now),env.DB.prepare("INSERT INTO member_registration_events (id,member_id,event_type,actor,details_json,created_at) VALUES (?,NULL,'STAFF_INVITED',?,?,?)").bind(crypto.randomUUID(),actor,JSON.stringify({email,role}),now)]);const inviteUrl=`${new URL(request.url).origin}/member-admin/invite?token=${encodeURIComponent(token)}`;return NextResponse.json({ok:true,inviteUrl,email,expiresAt})}
export async function PATCH(request:NextRequest){const actor=await manager(request);if(!actor)return NextResponse.json({error:"FORBIDDEN"},{status:403});const body=await request.json().catch(()=>null) as {email?:string;role?:string;status?:string}|null,email=String(body?.email??"").trim().toLowerCase(),role=String(body?.role??""),status=String(body?.status??"");if(!email||role&&!roles.includes(role as typeof roles[number])||status&&!["ACTIVE","SUSPENDED"].includes(status))return NextResponse.json({error:"INVALID_INPUT"},{status:400});const current=await env.DB.prepare("SELECT role,status FROM staff_accounts WHERE email=? LIMIT 1").bind(email).first();if(!current)return NextResponse.json({error:"NOT_FOUND"},{status:404});await env.DB.prepare("UPDATE staff_accounts SET role=COALESCE(NULLIF(?,''),role),status=COALESCE(NULLIF(?,''),status),invite_token_hash=CASE WHEN ?='SUSPENDED' THEN NULL ELSE invite_token_hash END,updated_at=? WHERE email=?").bind(role,status,status,Date.now(),email).run();await env.DB.prepare("INSERT INTO member_registration_events (id,member_id,event_type,actor,details_json,created_at) VALUES (?,NULL,'STAFF_UPDATED',?,?,?)").bind(crypto.randomUUID(),actor,JSON.stringify({email,role,status}),Date.now()).run();return NextResponse.json({ok:true})}
