import { env } from "cloudflare:workers";
import { NextRequest, NextResponse } from "next/server";
import { authenticatedLineUserId, authenticatedMember } from "@/lib/member-auth";
import { facilityPost } from "@/lib/facility-api";
import { expireStaleLocks,expireStaleOrder } from "@/lib/order-pos";
import { getOrderSchedule } from "@/lib/kitchen-schedule";
import { memberPresentation } from "@/lib/member-rank";

export async function GET(request: NextRequest) {
  const identity = await authenticatedMember(request);
  if (!identity) {const lineUserId=await authenticatedLineUserId(request);if(!lineUserId)return NextResponse.json({error:"LINE_AUTH_REQUIRED"},{status:401});const staged=await env.DB.prepare("SELECT id FROM legacy_member_imports WHERE line_user_id=? AND status='UNREGISTERED' LIMIT 1").bind(lineUserId).first();return NextResponse.json({error:staged?"REGISTRATION_REQUIRED":"MEMBERSHIP_NOT_LINKED"},{status:staged?422:404})}
  const member = await env.DB.prepare(`SELECT id, member_code AS memberCode, display_name AS displayName, member_rank AS memberRank, resident_status AS residentStatus, points_balance AS pointsBalance FROM members WHERE id = ? AND status = 'ACTIVE'`).bind(identity.id).first<{id:string;memberCode:string;displayName:string;memberRank:string|null;residentStatus:"UNKNOWN"|"ACTIVE"|"INACTIVE";pointsBalance:number}>();
  if (!member) return NextResponse.json({ error: "MEMBERSHIP_NOT_LINKED" }, { status: 404 });
  const rankPeriodStart=Date.now()-365*24*60*60*1000;
  const [reservations,sessionResult,orderSpend,studioSpend,smaregiSpend] = await Promise.all([facilityPost<{reservationId:string;startAt:string;endAt:string;status:string}[]>("reservation.get", { facilityId:"FEBBRAIO", memberCode:member.memberCode },crypto.randomUUID(),1_500).catch(()=>[]),facilityPost<{found:boolean;session?:{checkedInAt:number|null;scheduledEndAt:string;status:string;paymentStatus:string;billingAmount:number|null}}>("facility.session.get", { facilityId:"FEBBRAIO", memberCode:member.memberCode },crypto.randomUUID(),1_500).catch(()=>({found:false})),env.DB.prepare(`SELECT COALESCE(SUM(i.unit_price_excluding_tax*i.quantity),0) AS amount FROM orders o JOIN order_items i ON i.order_id=o.id WHERE o.member_id=? AND o.point_eligible=1 AND o.status IN ('PAID','ACCEPTED','COOKING','READY','PICKED_UP') AND o.created_at>=?`).bind(member.id,rankPeriodStart).first<{amount:number}>(),env.DB.prepare(`SELECT COALESCE(SUM(e.total_excluding_tax),0) AS amount FROM pos_payment_events e JOIN studio_sessions s ON s.id=e.session_id WHERE s.member_id=? AND s.point_eligible=1 AND e.paid_at>=?`).bind(member.id,rankPeriodStart).first<{amount:number}>(),env.DB.prepare(`SELECT qualifying_spend_excluding_tax AS qualifyingSpend,synced_at AS syncedAt FROM member_spend_snapshots WHERE member_id=? LIMIT 1`).bind(member.id).first<{qualifyingSpend:number;syncedAt:number}>()]);
  const reservation = reservations.filter(row=>row.status==="CONFIRMED"&&Date.parse(row.startAt)>Date.now()).sort((a,b)=>Date.parse(a.startAt)-Date.parse(b.startAt))[0];
  const session=sessionResult.found?sessionResult.session:null;
  await expireStaleLocks();await expireStaleOrder();const order = await env.DB.prepare(`SELECT o.id,o.order_number AS orderNumber,o.status,(SELECT call_number FROM order_fulfillments WHERE order_id=o.id AND department='FOOD') AS foodCallNumber,(SELECT status FROM order_fulfillments WHERE order_id=o.id AND department='FOOD') AS foodStatus,(SELECT call_number FROM order_fulfillments WHERE order_id=o.id AND department='DRINK') AS drinkCallNumber,(SELECT status FROM order_fulfillments WHERE order_id=o.id AND department='DRINK') AS drinkStatus FROM orders o WHERE o.member_id = ? AND o.status IN ('WAITING_STORE_PAYMENT','PAID','ACCEPTED','COOKING','READY') ORDER BY o.created_at DESC LIMIT 1`).bind(member.id).first<{id:string;orderNumber:string;status:string;foodCallNumber:number|null;foodStatus:string|null;drinkCallNumber:number|null;drinkStatus:string|null}>();
  const schedule=order?await getOrderSchedule(order.id):null;
  const orderStatus:Record<string,string>={WAITING_STORE_PAYMENT:"WAITING_PAYMENT",PAID:"ACCEPTED",ACCEPTED:"ACCEPTED",COOKING:"COOKING",READY:"READY"};
  const localSpend=(orderSpend?.amount??0)+(studioSpend?.amount??0);
  const qualifyingSpend=smaregiSpend?.qualifyingSpend??localSpend;
  const runtime=env as unknown as Record<string,string|undefined>;
  const legacyResident=member.residentStatus==="UNKNOWN"&&(runtime.LEGACY_RESIDENT_MEMBER_CODES??"").split(",").map(value=>value.trim().toUpperCase()).includes(member.memberCode);
  return NextResponse.json({memberId:member.id,memberCode:member.memberCode,displayName:member.displayName,points:member.pointsBalance,...memberPresentation(member.memberRank,qualifyingSpend,member.residentStatus,legacyResident),rankPeriodMonths:12,qualifyingSpendSource:smaregiSpend?"SMAREGI":"LOCAL",qualifyingSpendUpdatedAt:smaregiSpend?.syncedAt?new Date(smaregiSpend.syncedAt).toISOString():null,nextReservation:reservation?{facilityName:"Music Studio FEBBRAIO",startsAt:reservation.startAt,endsAt:reservation.endAt}:null,session:session?{facilityName:"Music Studio FEBBRAIO",status:session.status==="ACTIVE"?"IN_USE":session.status,paymentStatus:session.paymentStatus,startedAt:session.checkedInAt?new Date(session.checkedInAt).toISOString():undefined,scheduledEndsAt:session.scheduledEndAt||undefined,unpaidAmount:session.billingAmount}:null,activeOrder:order?{orderNumber:order.orderNumber,foodCallNumber:order.foodCallNumber,foodStatus:order.foodStatus,drinkCallNumber:order.drinkCallNumber,drinkStatus:order.drinkStatus,status:orderStatus[order.status],schedule,scheduleLabel:schedule?null:"提供予定：できあがり次第"}:null,notices:[]});
}
