import { env } from "cloudflare:workers";
import { NextRequest, NextResponse } from "next/server";
import { authenticatedLineUserId, authenticatedMember } from "@/lib/member-auth";
import { facilityPost, filterOwnedFacilityRows, isOwnedFacilityRow } from "@/lib/facility-api";
import { expireStaleLocks,expireStaleOrder,reconcileCompletedOrders } from "@/lib/order-pos";
import { getOrderSchedule } from "@/lib/kitchen-schedule";
import { memberPresentation, MEMBER_RANK_TERMS_VERSION, rankPeriodFor } from "@/lib/member-rank";
import { memberNotices, StoredNoticeRow } from "@/lib/member-notices";

export async function GET(request: NextRequest) {
  const identity = await authenticatedMember(request);
  if (!identity) {const lineUserId=await authenticatedLineUserId(request);if(!lineUserId)return NextResponse.json({error:"LINE_AUTH_REQUIRED"},{status:401});const staged=await env.DB.prepare("SELECT id FROM legacy_member_imports WHERE line_user_id=? AND status='UNREGISTERED' LIMIT 1").bind(lineUserId).first();return NextResponse.json({error:staged?"REGISTRATION_REQUIRED":"MEMBERSHIP_NOT_LINKED"},{status:staged?422:404})}
  const member = await env.DB.prepare(`SELECT m.id,m.member_code AS memberCode,m.display_name AS displayName,m.member_rank AS memberRank,m.resident_status AS residentStatus,m.points_balance AS pointsBalance,m.created_at AS createdAt,(SELECT linked_at FROM identity_links WHERE member_id=m.id AND provider='LINE' AND revoked_at IS NULL ORDER BY linked_at DESC LIMIT 1) AS cardStartedAt FROM members m WHERE m.id = ? AND m.status = 'ACTIVE'`).bind(identity.id).first<{id:string;memberCode:string;displayName:string;memberRank:string|null;residentStatus:"UNKNOWN"|"ACTIVE"|"INACTIVE";pointsBalance:number;createdAt:number;cardStartedAt:number|null}>();
  if (!member) return NextResponse.json({ error: "MEMBERSHIP_NOT_LINKED" }, { status: 404 });
  const [reservationRows,sessionResult,smaregiSpend,registrationSync,rankState,rankConsent,notificationRows] = await Promise.all([facilityPost<{reservationId:string;memberCode:string;startAt:string;endAt:string;status:string}[]>("reservation.get", { facilityId:"FEBBRAIO", memberCode:member.memberCode },crypto.randomUUID(),4_000).catch(()=>null),facilityPost<{found:boolean;session?:{memberCode:string;checkedInAt:number|null;scheduledEndAt:string;status:string;paymentStatus:string;billingAmount:number|null}}>("facility.session.get", { facilityId:"FEBBRAIO", memberCode:member.memberCode },crypto.randomUUID(),1_500).catch(()=>({found:false})),env.DB.prepare(`SELECT qualifying_spend_excluding_tax AS qualifyingSpend,synced_at AS syncedAt FROM member_spend_snapshots WHERE member_id=? LIMIT 1`).bind(member.id).first<{qualifyingSpend:number;syncedAt:number}>(),env.DB.prepare(`SELECT status FROM member_registration_syncs WHERE member_id=? LIMIT 1`).bind(member.id).first<{status:"PENDING"|"SYNCING"|"SYNCED"|"FAILED"}>(),env.DB.prepare(`SELECT current_rank AS currentRank,current_rate_percent AS currentRatePercent,rank_period_started_at AS rankPeriodStartedAt,rank_period_ends_at AS rankPeriodEndsAt,next_review_at AS nextReviewAt,resident_plan_active AS residentPlanActive FROM member_rank_states WHERE member_id=?`).bind(member.id).first<{currentRank:string;currentRatePercent:number;rankPeriodStartedAt:number;rankPeriodEndsAt:number;nextReviewAt:number;residentPlanActive:number}>(),env.DB.prepare(`SELECT agreed_at AS agreedAt FROM member_policy_consents WHERE member_id=? AND terms_version=? AND consent_type='MEMBERSHIP_AND_POINTS' LIMIT 1`).bind(member.id,MEMBER_RANK_TERMS_VERSION).first<{agreedAt:number}>(),env.DB.prepare(`SELECT id,event_id AS eventId,event_type AS eventType,category,title,body,sender,metadata_json AS metadataJson,read_at AS readAt,occurred_at AS occurredAt,created_at AS createdAt FROM member_notifications WHERE member_id=? ORDER BY created_at DESC LIMIT 50`).bind(member.id).all<StoredNoticeRow>()]);
  const reservationsAvailable=reservationRows!==null;
  const reservations=filterOwnedFacilityRows(reservationRows??[],member.memberCode);
  const activeReservations = reservations.filter(row=>row.status==="CONFIRMED"&&Date.parse(row.endAt)>Date.now()).sort((a,b)=>Date.parse(a.startAt)-Date.parse(b.startAt));
  const reservationHistory = reservations.filter(row=>row.status!=="CONFIRMED"||Date.parse(row.endAt)<=Date.now()).sort((a,b)=>Date.parse(b.startAt)-Date.parse(a.startAt));
  const session=sessionResult.found&&isOwnedFacilityRow(sessionResult.session,member.memberCode)?sessionResult.session:null;
  await expireStaleLocks();await expireStaleOrder();await reconcileCompletedOrders(member.id);const orderRows = await env.DB.prepare(`SELECT o.id,o.order_number AS orderNumber,o.status,o.created_at AS createdAt,(SELECT call_number FROM order_fulfillments WHERE order_id=o.id AND department='FOOD') AS foodCallNumber,(SELECT status FROM order_fulfillments WHERE order_id=o.id AND department='FOOD') AS foodStatus,(SELECT call_number FROM order_fulfillments WHERE order_id=o.id AND department='DRINK') AS drinkCallNumber,(SELECT status FROM order_fulfillments WHERE order_id=o.id AND department='DRINK') AS drinkStatus FROM orders o WHERE o.member_id = ? ORDER BY o.created_at DESC`).bind(member.id).all<{id:string;orderNumber:string;status:string;createdAt:number;foodCallNumber:number|null;foodStatus:string|null;drinkCallNumber:number|null;drinkStatus:string|null}>();
  const orderStatus:Record<string,string>={WAITING_STORE_PAYMENT:"WAITING_PAYMENT",PAID:"ACCEPTED",ACCEPTED:"ACCEPTED",COOKING:"COOKING",READY:"READY"};
  const openOrderRows=orderRows.results.filter(row=>orderStatus[row.status]&&(row.status==="WAITING_STORE_PAYMENT"||![row.foodStatus,row.drinkStatus].filter(Boolean).every(status=>status==="PICKED_UP"||status==="CANCELLED")));
  const activeOrders=await Promise.all(openOrderRows.map(async row=>({orderNumber:row.orderNumber,foodCallNumber:row.foodCallNumber,foodStatus:row.foodStatus,drinkCallNumber:row.drinkCallNumber,drinkStatus:row.drinkStatus,status:orderStatus[row.status],createdAt:new Date(row.createdAt).toISOString(),schedule:await getOrderSchedule(row.id),scheduleLabel:"提供予定時間を確認しています。しばらくお待ちください。"})));
  const orderHistory=orderRows.results.filter(row=>!openOrderRows.some(open=>open.id===row.id)).map(row=>({orderNumber:row.orderNumber,status:row.status,createdAt:new Date(row.createdAt).toISOString(),foodCallNumber:row.foodCallNumber,drinkCallNumber:row.drinkCallNumber}));
  // 年間購入額の正本はスマレジ集計のみ。一部の注文・スタジオ売上を
  // 年間実績として代替表示すると過少額になるため、未同期時は0円を返して
  // qualifyingSpendSource で「集計中」と表示させる。
  const qualifyingSpend=smaregiSpend?.qualifyingSpend??0;
  const runtime=env as unknown as Record<string,string|undefined>;
  const legacyResident=member.residentStatus==="UNKNOWN"&&(runtime.LEGACY_RESIDENT_MEMBER_CODES??"").split(",").map(value=>value.trim().toUpperCase()).includes(member.memberCode);
  const rankPeriod=rankState??rankPeriodFor(member.cardStartedAt??member.createdAt),presentation=memberPresentation(rankState?.currentRank??member.memberRank,qualifyingSpend,member.residentStatus,legacyResident);
  const notices=memberNotices(notificationRows.results,member);
  Object.assign(presentation,{reservationsAvailable});
  return NextResponse.json({memberId:member.id,memberCode:member.memberCode,displayName:member.displayName,points:member.pointsBalance,smaregiSyncStatus:registrationSync?.status??null,...presentation,rank:rankState?.currentRank??presentation.rank,rankLabel:presentation.rankLabel,pointRatePercent:rankState?.currentRatePercent??presentation.pointRatePercent,rankPeriodMonths:12,rankPeriodStartedAt:rankPeriod.rankPeriodStartedAt,rankPeriodEndsAt:rankPeriod.rankPeriodEndsAt,nextReviewAt:rankPeriod.nextReviewAt,residentPlanActive:Boolean(rankState?.residentPlanActive)||presentation.membershipType==="RESIDENT",rankTermsVersion:MEMBER_RANK_TERMS_VERSION,rankTermsConsentRequired:!rankConsent,qualifyingSpendSource:smaregiSpend?"SMAREGI":"NOT_SYNCED",qualifyingSpendUpdatedAt:smaregiSpend?.syncedAt?new Date(smaregiSpend.syncedAt).toISOString():null,reservations:activeReservations.map(row=>({reservationId:row.reservationId,facilityName:"Music Studio FEBBRAIO",startsAt:row.startAt,endsAt:row.endAt,status:row.status})),reservationHistory:reservationHistory.map(row=>({reservationId:row.reservationId,facilityName:"Music Studio FEBBRAIO",startsAt:row.startAt,endsAt:row.endAt,status:row.status})),nextReservation:activeReservations[0]?{facilityName:"Music Studio FEBBRAIO",startsAt:activeReservations[0].startAt,endsAt:activeReservations[0].endAt}:null,session:session?{facilityName:"Music Studio FEBBRAIO",status:session.status==="ACTIVE"?"IN_USE":session.status,paymentStatus:session.paymentStatus,startedAt:session.checkedInAt?new Date(session.checkedInAt).toISOString():undefined,scheduledEndsAt:session.scheduledEndAt||undefined,unpaidAmount:session.billingAmount}:null,orders:activeOrders,orderHistory,activeOrder:activeOrders[0]??null,notices});
}
