import { env } from "cloudflare:workers";
import { NextRequest, NextResponse } from "next/server";
import { authenticatedLineUserId, authenticatedMember } from "@/lib/member-auth";
import { facilityPost, filterOwnedFacilityRows, isOwnedFacilityRow } from "@/lib/facility-api";
import { expireStaleLocks,expireStaleOrder,reconcileCompletedOrders } from "@/lib/order-pos";
import { getOrderSchedule } from "@/lib/kitchen-schedule";
import { memberPresentation, MEMBER_RANK_TERMS_VERSION, rankPeriodFor } from "@/lib/member-rank";
import { memberNotices, StoredNoticeRow } from "@/lib/member-notices";
import { orderUnits } from "@/lib/kitchen-units";

export async function GET(request: NextRequest) {
  const identity = await authenticatedMember(request);
  if (!identity) {const lineUserId=await authenticatedLineUserId(request);if(!lineUserId)return NextResponse.json({error:"LINE_AUTH_REQUIRED"},{status:401});const staged=await env.DB.prepare("SELECT id FROM legacy_member_imports WHERE line_user_id=? AND status='UNREGISTERED' LIMIT 1").bind(lineUserId).first();return NextResponse.json({error:staged?"REGISTRATION_REQUIRED":"MEMBERSHIP_NOT_LINKED"},{status:staged?422:404})}
  const member = await env.DB.prepare(`SELECT m.id,m.member_code AS memberCode,m.display_name AS displayName,m.member_rank AS memberRank,m.resident_status AS residentStatus,m.points_balance AS pointsBalance,m.created_at AS createdAt,(SELECT linked_at FROM identity_links WHERE member_id=m.id AND provider='LINE' AND revoked_at IS NULL ORDER BY linked_at DESC LIMIT 1) AS cardStartedAt FROM members m WHERE m.id = ? AND m.status = 'ACTIVE'`).bind(identity.id).first<{id:string;memberCode:string;displayName:string;memberRank:string|null;residentStatus:"UNKNOWN"|"ACTIVE"|"INACTIVE";pointsBalance:number;createdAt:number;cardStartedAt:number|null}>();
  if (!member) return NextResponse.json({ error: "MEMBERSHIP_NOT_LINKED" }, { status: 404 });
  const reservationStartedAt=Date.now();
  const [reservationResult,sessionResult,smaregiSpend,registrationSync,rankState,rankConsent,notificationRows] = await Promise.all([facilityPost<{reservationId:string;memberCode:string;startAt:string;endAt:string;status:string}[]>("reservation.get", { facilityId:"FEBBRAIO", memberCode:member.memberCode },crypto.randomUUID(),8_000).then(rows=>({rows,error:null as string|null})).catch(error=>{const code=error instanceof Error?error.name==="TimeoutError"?"TIMEOUT":error.message:"FACILITY_API_ERROR";console.error("membership reservation.get failed",{code,durationMs:Date.now()-reservationStartedAt});return{rows:null,error:code}}),facilityPost<{found:boolean;session?:{reservationId?:string;memberCode:string;checkedInAt:number|null;scheduledEndAt:string;status:string;paymentStatus:string;billingAmount:number|null}}>("facility.session.get", { facilityId:"FEBBRAIO", memberCode:member.memberCode },crypto.randomUUID(),6_000).then(data=>({data,error:null as string|null})).catch(error=>{const code=error instanceof Error?error.message:"FACILITY_API_ERROR";console.error("membership facility.session.get failed",{code});return{data:{found:false},error:code}}),env.DB.prepare(`SELECT qualifying_spend_excluding_tax AS qualifyingSpend,synced_at AS syncedAt FROM member_spend_snapshots WHERE member_id=? LIMIT 1`).bind(member.id).first<{qualifyingSpend:number;syncedAt:number}>(),env.DB.prepare(`SELECT status FROM member_registration_syncs WHERE member_id=? LIMIT 1`).bind(member.id).first<{status:"PENDING"|"SYNCING"|"SYNCED"|"FAILED"}>(),env.DB.prepare(`SELECT current_rank AS currentRank,current_rate_percent AS currentRatePercent,rank_period_started_at AS rankPeriodStartedAt,rank_period_ends_at AS rankPeriodEndsAt,next_review_at AS nextReviewAt,resident_plan_active AS residentPlanActive FROM member_rank_states WHERE member_id=?`).bind(member.id).first<{currentRank:string;currentRatePercent:number;rankPeriodStartedAt:number;rankPeriodEndsAt:number;nextReviewAt:number;residentPlanActive:number}>(),env.DB.prepare(`SELECT agreed_at AS agreedAt FROM member_policy_consents WHERE member_id=? AND terms_version=? AND consent_type='MEMBERSHIP_AND_POINTS' LIMIT 1`).bind(member.id,MEMBER_RANK_TERMS_VERSION).first<{agreedAt:number}>(),env.DB.prepare(`SELECT id,event_id AS eventId,event_type AS eventType,category,title,body,sender,metadata_json AS metadataJson,read_at AS readAt,occurred_at AS occurredAt,created_at AS createdAt FROM member_notifications WHERE member_id=? ORDER BY created_at DESC LIMIT 50`).bind(member.id).all<StoredNoticeRow>()]);
  const reservationsAvailable=reservationResult.rows!==null;
  const reservations=filterOwnedFacilityRows(reservationResult.rows??[],member.memberCode);
  const session=sessionResult.data.found&&isOwnedFacilityRow(sessionResult.data.session,member.memberCode)?sessionResult.data.session:null;
  const noShowCutoff=Date.now()-15*60_000,noShows=sessionResult.error===null?reservations.filter(row=>row.status==="CONFIRMED"&&Date.parse(row.startAt)<=noShowCutoff&&session?.reservationId!==row.reservationId):[];
  if(noShows.length)await Promise.all(noShows.map(row=>facilityPost("reservation.cancel",{facilityId:"FEBBRAIO",reservationId:row.reservationId,memberCode:member.memberCode},`no-show:${row.reservationId}`,8_000).catch(error=>console.error("membership no-show cancellation failed",{reservationId:row.reservationId,code:error instanceof Error?error.message:"FACILITY_API_ERROR"}))));
  const noShowIds=new Set(noShows.map(row=>row.reservationId));
  const activeReservations = reservations.filter(row=>row.status==="CONFIRMED"&&!noShowIds.has(row.reservationId)&&Date.parse(row.startAt)>noShowCutoff).sort((a,b)=>Date.parse(a.startAt)-Date.parse(b.startAt));
  const reservationHistory = reservations.filter(row=>row.status!=="CONFIRMED"||noShowIds.has(row.reservationId)||Date.parse(row.startAt)<=noShowCutoff).map(row=>noShowIds.has(row.reservationId)?{...row,status:"CANCELLED"}:row).sort((a,b)=>Date.parse(b.startAt)-Date.parse(a.startAt));
  await expireStaleLocks();await expireStaleOrder();await reconcileCompletedOrders(member.id);const orderRows = await env.DB.prepare(`SELECT o.id,o.order_number AS orderNumber,o.status,o.payment_method AS paymentMethod,o.total_including_tax AS totalIncludingTax,o.points_earned AS pointsEarned,o.pickup_at AS pickupAt,o.created_at AS createdAt,(SELECT call_number FROM order_fulfillments WHERE order_id=o.id AND department='FOOD') AS foodCallNumber,(SELECT status FROM order_fulfillments WHERE order_id=o.id AND department='FOOD') AS foodStatus,(SELECT call_number FROM order_fulfillments WHERE order_id=o.id AND department='DRINK') AS drinkCallNumber,(SELECT status FROM order_fulfillments WHERE order_id=o.id AND department='DRINK') AS drinkStatus FROM orders o WHERE o.member_id = ? ORDER BY o.created_at DESC`).bind(member.id).all<{id:string;orderNumber:string;status:string;paymentMethod:string;totalIncludingTax:number;pointsEarned:number;pickupAt:number|null;createdAt:number;foodCallNumber:number|null;foodStatus:string|null;drinkCallNumber:number|null;drinkStatus:string|null}>();
  const orderItemRows=await env.DB.prepare(`SELECT oi.order_id AS orderId,oi.product_name AS productName,oi.quantity FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE o.member_id=? ORDER BY o.created_at DESC,oi.rowid`).bind(member.id).all<{orderId:string;productName:string;quantity:number}>();
  const orderStatus:Record<string,string>={WAITING_STORE_PAYMENT:"WAITING_PAYMENT",PAID:"ACCEPTED",ACCEPTED:"ACCEPTED",COOKING:"COOKING",READY:"READY"};
  const openOrderRows=orderRows.results.filter(row=>orderStatus[row.status]&&(row.status==="WAITING_STORE_PAYMENT"||![row.foodStatus,row.drinkStatus].filter(Boolean).every(status=>status==="PICKED_UP"||status==="CANCELLED")));
  const activeOrders=await Promise.all(openOrderRows.map(async row=>({orderNumber:row.orderNumber,units:await orderUnits(row.id),foodCallNumber:row.foodCallNumber,foodStatus:row.foodStatus,drinkCallNumber:row.drinkCallNumber,drinkStatus:row.drinkStatus,status:orderStatus[row.status],createdAt:new Date(row.createdAt).toISOString(),schedule:await getOrderSchedule(row.id),scheduleLabel:"提供予定時間を確認しています。しばらくお待ちください。"})));
  const orderHistory=orderRows.results.filter(row=>!openOrderRows.some(open=>open.id===row.id)).map(row=>({orderNumber:row.orderNumber,status:row.status,createdAt:new Date(row.createdAt).toISOString(),pickupAt:row.pickupAt?new Date(row.pickupAt).toISOString():null,paymentMethod:row.paymentMethod,paymentLabel:row.paymentMethod==="STRIPE"?"スマート決済":"現地決済",totalIncludingTax:row.totalIncludingTax,pointsEarned:row.pointsEarned,items:orderItemRows.results.filter(item=>item.orderId===row.id).map(item=>({name:item.productName,quantity:item.quantity})),foodCallNumber:row.foodCallNumber,drinkCallNumber:row.drinkCallNumber}));
  // 年間購入額の正本はスマレジ集計のみ。一部の注文・スタジオ売上を
  // 年間実績として代替表示すると過少額になるため、未同期時は0円を返して
  // qualifyingSpendSource で「集計中」と表示させる。
  const qualifyingSpend=smaregiSpend?.qualifyingSpend??0;
  const runtime=env as unknown as Record<string,string|undefined>;
  const legacyResident=member.residentStatus==="UNKNOWN"&&(runtime.LEGACY_RESIDENT_MEMBER_CODES??"").split(",").map(value=>value.trim().toUpperCase()).includes(member.memberCode);
  const rankPeriod=rankState??rankPeriodFor(member.cardStartedAt??member.createdAt),presentation=memberPresentation(rankState?.currentRank??member.memberRank,qualifyingSpend,member.residentStatus,legacyResident);
  const notices=memberNotices(notificationRows.results,member);
  Object.assign(presentation,{reservationsAvailable});
  return NextResponse.json({memberId:member.id,memberCode:member.memberCode,displayName:member.displayName,points:member.pointsBalance,smaregiSyncStatus:registrationSync?.status??null,...presentation,reservationsError:reservationResult.error,rank:rankState?.currentRank??presentation.rank,rankLabel:presentation.rankLabel,pointRatePercent:rankState?.currentRatePercent??presentation.pointRatePercent,rankPeriodMonths:12,rankPeriodStartedAt:rankPeriod.rankPeriodStartedAt,rankPeriodEndsAt:rankPeriod.rankPeriodEndsAt,nextReviewAt:rankPeriod.nextReviewAt,residentPlanActive:Boolean(rankState?.residentPlanActive)||presentation.membershipType==="RESIDENT",rankTermsVersion:MEMBER_RANK_TERMS_VERSION,rankTermsConsentRequired:!rankConsent,qualifyingSpendSource:smaregiSpend?"SMAREGI":"NOT_SYNCED",qualifyingSpendUpdatedAt:smaregiSpend?.syncedAt?new Date(smaregiSpend.syncedAt).toISOString():null,reservations:activeReservations.map(row=>({reservationId:row.reservationId,facilityName:"Music Studio FEBBRAIO",startsAt:row.startAt,endsAt:row.endAt,status:row.status})),reservationHistory:reservationHistory.map(row=>({reservationId:row.reservationId,facilityName:"Music Studio FEBBRAIO",startsAt:row.startAt,endsAt:row.endAt,status:row.status})),nextReservation:activeReservations[0]?{facilityName:"Music Studio FEBBRAIO",startsAt:activeReservations[0].startAt,endsAt:activeReservations[0].endAt}:null,session:session?{facilityName:"Music Studio FEBBRAIO",status:session.status==="ACTIVE"?"IN_USE":session.status,paymentStatus:session.paymentStatus,startedAt:session.checkedInAt?new Date(session.checkedInAt).toISOString():undefined,scheduledEndsAt:session.scheduledEndAt||undefined,unpaidAmount:session.billingAmount}:null,orders:activeOrders,orderHistory,activeOrder:activeOrders[0]??null,notices});
}
