"use client";

import { ArrowLeft, Bell, MailOpen } from "lucide-react";
import { useEffect, useState } from "react";

type Notice={id:string;category:"PAYMENT"|"POINT"|"RESERVATION"|"ORDER"|"NEWS";title:string;body:string;sender?:string;createdAt:string;unread:boolean};
declare global{interface Window{liff?:{init:(config:{liffId:string})=>Promise<void>;isLoggedIn:()=>boolean;login:(config?:{redirectUri?:string})=>void;getAccessToken:()=>string|null}}}

function script(src:string){return new Promise<void>((resolve,reject)=>{if(window.liff)return resolve();const existing=document.querySelector(`script[src="${src}"]`);if(existing){existing.addEventListener("load",()=>resolve(),{once:true});return}const tag=document.createElement("script");tag.src=src;tag.onload=()=>resolve();tag.onerror=()=>reject(new Error("LINE認証を読み込めませんでした"));document.head.appendChild(tag)})}
function label(category:Notice["category"]){return{PAYMENT:"決済",POINT:"ポイント",RESERVATION:"予約",ORDER:"注文",NEWS:"お知らせ"}[category]}

export default function InboxPage(){
 const [notices,setNotices]=useState<Notice[]>([]),[selected,setSelected]=useState<Notice|null>(null),[authHeaders,setAuthHeaders]=useState<Record<string,string>|null>(null),[loading,setLoading]=useState(true),[markingAll,setMarkingAll]=useState(false),[error,setError]=useState("");
 useEffect(()=>{let active=true;(async()=>{try{const config=await fetch("/api/v1/client-config").then(response=>response.json()) as {liffId?:string};let headers:Record<string,string>;if(config.liffId){await script("https://static.line-scdn.net/liff/edge/2/sdk.js");await window.liff!.init({liffId:config.liffId});if(!window.liff!.isLoggedIn()){window.liff!.login({redirectUri:window.location.href});return}const value=window.liff!.getAccessToken()??"";headers={Authorization:`Bearer ${value}`}}else headers={"X-Compass-Preview":"representative"};setAuthHeaders(headers);const response=await fetch("/api/v1/me/notifications",{headers,cache:"no-store"});if(!response.ok)throw new Error("受信ボックスを取得できませんでした");const result=await response.json() as {notices:Notice[]};if(active)setNotices(result.notices)}catch(reason){if(active)setError(reason instanceof Error?reason.message:"読み込みに失敗しました")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
 const open=async(item:Notice)=>{setSelected({...item,unread:false});if(!item.unread)return;setNotices(current=>current.map(notice=>notice.id===item.id?{...notice,unread:false}:notice));if(authHeaders)void fetch(`/api/v1/me/notifications/${encodeURIComponent(item.id)}`,{method:"PATCH",headers:authHeaders})};
 const markAllRead=async()=>{if(!authHeaders||markingAll||!notices.some(item=>item.unread))return;setMarkingAll(true);setError("");try{const response=await fetch("/api/v1/me/notifications",{method:"PATCH",headers:authHeaders,cache:"no-store"});if(!response.ok)throw new Error("一括既読にできませんでした");setNotices(current=>current.map(item=>({...item,unread:false})));setSelected(current=>current?{...current,unread:false}:current)}catch(reason){setError(reason instanceof Error?reason.message:"一括既読にできませんでした")}finally{setMarkingAll(false)}};
 const unread=notices.filter(item=>item.unread).length;
 return <main className="inbox-shell"><header><button onClick={()=>{window.location.href="/"}} aria-label="会員証へ戻る"><ArrowLeft size={20}/></button><div><small>COMPASSION WORLD</small><h1>受信ボックス</h1></div><span><Bell size={18}/>{unread>0&&<b>{unread}</b>}</span></header><section className="inbox-list"><div className="inbox-heading"><p>INFORMATION</p><div><strong>{unread?`未読 ${unread}件`:"すべて確認済みです"}</strong>{unread>0&&<button disabled={markingAll||!authHeaders} onClick={()=>void markAllRead()}>{markingAll?"処理中…":"すべて既読にする"}</button>}</div></div>{loading&&<div className="inbox-empty">お知らせを読み込んでいます…</div>}{error&&<div className="inbox-empty">{error}</div>}{!loading&&!error&&!notices.length&&<div className="inbox-empty"><MailOpen size={30}/><strong>お知らせはありません</strong></div>}{notices.map(item=><button className={`inbox-row ${item.unread?"unread":""}`} key={item.id} onClick={()=>open(item)}><span>{label(item.category)}</span><div><strong>{item.title}</strong><p>{item.body.split("\n").find(Boolean)}</p><small>{item.createdAt}</small></div>{item.unread&&<i/>}<b>›</b></button>)}</section>{selected&&<div className="notice-mail-backdrop" onClick={()=>setSelected(null)}><article className="notice-mail" role="dialog" aria-modal="true" onClick={event=>event.stopPropagation()}><header><button onClick={()=>setSelected(null)} aria-label="受信ボックスへ戻る">‹</button><div><small>INFORMATION</small><strong>お知らせ</strong></div><span>COMPASSION WORLD</span></header><section><p className="notice-mail-category">{label(selected.category)}</p><h2>{selected.title}</h2><dl><div><dt>差出人</dt><dd>{selected.sender??"COMPASSION WORLD"}</dd></div><div><dt>受信日時</dt><dd>{selected.createdAt}</dd></div></dl><div className="notice-mail-body">{selected.body.split("\n").map((line,index)=><p key={index}>{line||<br/>}</p>)}</div><p className="notice-mail-signature">COMPASSION WORLD</p></section><footer><button onClick={()=>setSelected(null)}>受信ボックスへ戻る</button></footer></article></div>}</main>
}
