"use client";
import { ArrowLeft,ChevronLeft,ChevronRight } from "lucide-react";
import { useCallback,useEffect,useState } from "react";

declare global{interface Window{liff?:{init(c:{liffId:string}):Promise<void>;isLoggedIn():boolean;login(c?:{redirectUri?:string}):void;getAccessToken():string|null}}}
type Entry={id:string;occurredAt:string;kind:"EARN"|"USE"|"EARN_AND_USE"|"VISIT";grantedPoint:number;usedPoint:number;delta:number;balanceAfter:number|null;amount:number;cancelled:boolean;label?:string};
type RankProgress={currentRank:string;currentRankLabel:string;pointRatePercent:number;qualifyingSpend:number;nextRank:string|null;nextRankLabel:string|null;amountToNextRank:number;periodEndsAt:string|null;syncedAt:string|null};
type History={month:string;balance:number;entries:Entry[];syncedAt:string;summary:{earned:number;used:number;net:number;count:number};rankProgress:RankProgress};
const currentMonth=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit"}).format(new Date());
const moveMonth=(value:string,amount:number)=>{const [year,month]=value.split("-").map(Number),date=new Date(year,month-1+amount,1);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`};
function loadLiff(){return new Promise<void>((resolve,reject)=>{if(window.liff)return resolve();const script=document.createElement("script");script.src="https://static.line-scdn.net/liff/edge/2/sdk.js";script.onload=()=>resolve();script.onerror=()=>reject(new Error("LINE認証を読み込めませんでした"));document.head.appendChild(script)})}
function entryTitle(item:Entry){if(item.label)return item.label;if(item.cancelled)return"取消・返品";if(item.kind==="EARN_AND_USE")return"お買い上げ・ポイント利用";if(item.kind==="USE")return"ポイント利用";if(item.amount>0)return"お買い上げ";return item.delta>=0?"ポイント付与":"ポイント調整"}
function entryDetail(item:Entry){if(item.kind==="VISIT")return"ご来館によるポイント";if(item.cancelled)return item.amount>0?`¥${item.amount.toLocaleString("ja-JP")}のお会計を取消・返品`:"取消・返品によるポイント調整";if(item.amount>0){const parts=[`お会計 ¥${item.amount.toLocaleString("ja-JP")}`];if(item.grantedPoint>0)parts.push(`${item.grantedPoint.toLocaleString("ja-JP")} P付与`);if(item.usedPoint>0)parts.push(`${item.usedPoint.toLocaleString("ja-JP")} P利用`);return parts.join(" ／ ")}return item.delta>=0?"キャンペーン・来店などによる付与":"ポイント残高の調整"}

export default function PointsPage(){
 const [token,setToken]=useState(""),[month,setMonth]=useState(currentMonth()),[history,setHistory]=useState<History|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async(accessToken:string,target:string)=>{setLoading(true);setError("");try{const response=await fetch(`/api/v1/me/points?month=${target}`,{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"}),result=await response.json();if(!response.ok)throw new Error(result.message??"ポイント履歴を取得できませんでした");setHistory(result)}catch(e){setHistory(null);setError(e instanceof Error?e.message:"ポイント履歴を取得できませんでした")}finally{setLoading(false)}},[]);
 useEffect(()=>{void(async()=>{try{const config=await fetch("/api/v1/client-config").then(r=>r.json());await loadLiff();await window.liff!.init({liffId:String(config.liffId??"")});if(!window.liff!.isLoggedIn()){window.liff!.login({redirectUri:location.href});return}const value=window.liff!.getAccessToken();if(!value)throw new Error("LINE認証を確認できませんでした");setToken(value);await load(value,month)}catch(e){setError(e instanceof Error?e.message:"ポイント履歴を開けませんでした");setLoading(false)}})()},[load]);
 const change=(next:string)=>{if(next>currentMonth()||loading)return;setMonth(next);if(token)void load(token,next)};
 return <main className="point-history-page">
  <header><a href="/"><ArrowLeft size={18}/>ポイントカードへ戻る</a><small>POINT HISTORY</small><h1>ポイント履歴</h1></header>
  <section className="point-history-balance"><small>現在の保有ポイント</small><strong>{history?history.balance.toLocaleString("ja-JP"):"—"}<span> P</span></strong>{history&&<p>最終更新：{new Date(history.syncedAt).toLocaleString("ja-JP")}</p>}</section>
  {history&&<section className="point-rank-progress"><div><small>現在の会員ランク</small><strong>{history.rankProgress.currentRankLabel}</strong><span>{history.rankProgress.pointRatePercent}%還元</span></div>{history.rankProgress.nextRankLabel?<><p>次の{history.rankProgress.nextRankLabel}まで <b>あと¥{history.rankProgress.amountToNextRank.toLocaleString("ja-JP")}</b></p><progress max={Math.max(1,history.rankProgress.qualifyingSpend+history.rankProgress.amountToNextRank)} value={history.rankProgress.qualifyingSpend}/><small>対象利用額 ¥{history.rankProgress.qualifyingSpend.toLocaleString("ja-JP")}</small></>:<p><b>最高ランクに到達しています</b></p>}</section>}
  <nav><button onClick={()=>change(moveMonth(month,-1))} disabled={loading}><ChevronLeft size={18}/></button><strong>{month.replace("-","年")}月</strong><button onClick={()=>change(moveMonth(month,1))} disabled={loading||month>=currentMonth()}><ChevronRight size={18}/></button></nav>
  {history&&<section className="point-month-summary"><span><small>付与</small><b>+{history.summary.earned.toLocaleString("ja-JP")} P</b></span><span><small>利用</small><b>-{history.summary.used.toLocaleString("ja-JP")} P</b></span><span><small>履歴</small><b>{history.summary.count}件</b></span></section>}
  {loading?<div className="point-history-state loading"><progress aria-label="ポイント履歴を読み込み中"/><strong>ポイント履歴を読み込んでいます</strong><span>最新の情報を確認しています。少しお待ちください。</span></div>:error?<p className="point-history-state error">{error}</p>:history?.entries.length?<section className="point-history-list">{history.entries.map(item=><article key={item.id}><time>{new Date(item.occurredAt).toLocaleString("ja-JP",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"})}</time><div><strong>{entryTitle(item)}</strong><small>{entryDetail(item)}</small></div><b className={item.delta>=0?"plus":"minus"}>{item.delta>=0?"+":""}{item.delta.toLocaleString("ja-JP")} P</b>{item.balanceAfter!==null&&<small>利用後 {item.balanceAfter.toLocaleString("ja-JP")} P</small>}</article>)}</section>:<p className="point-history-state">この月のポイント履歴はありません</p>}
  <footer>月を切り替えて、会員登録後のポイント履歴を確認できます。</footer>
 </main>
}
