"use client";
import { ArrowLeft, ChevronLeft, ChevronRight } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

declare global{interface Window{liff?:{init(c:{liffId:string}):Promise<void>;isLoggedIn():boolean;login(c?:{redirectUri?:string}):void;getAccessToken():string|null}}}
type Entry={id:string;occurredAt:string;kind:"EARN"|"USE"|"EARN_AND_USE";grantedPoint:number;usedPoint:number;delta:number;balanceAfter:number;amount:number;cancelled:boolean};
type History={month:string;balance:number;entries:Entry[];syncedAt:string};
const currentMonth=()=>new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit"}).format(new Date());
const moveMonth=(value:string,amount:number)=>{const [year,month]=value.split("-").map(Number),date=new Date(year,month-1+amount,1);return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`};
function loadLiff(){return new Promise<void>((resolve,reject)=>{if(window.liff)return resolve();const script=document.createElement("script");script.src="https://static.line-scdn.net/liff/edge/2/sdk.js";script.onload=()=>resolve();script.onerror=()=>reject(new Error("LINE認証を読み込めませんでした"));document.head.appendChild(script)})}
export default function PointsPage(){
 const [token,setToken]=useState(""),[month,setMonth]=useState(currentMonth()),[history,setHistory]=useState<History|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=useCallback(async(accessToken:string,target:string)=>{setLoading(true);setError("");try{const response=await fetch(`/api/v1/me/points?month=${target}`,{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"}),result=await response.json();if(!response.ok)throw new Error(result.message??"ポイント履歴を取得できませんでした");setHistory(result)}catch(e){setHistory(null);setError(e instanceof Error?e.message:"ポイント履歴を取得できませんでした")}finally{setLoading(false)}},[]);
 useEffect(()=>{void(async()=>{try{const config=await fetch("/api/v1/client-config").then(r=>r.json());await loadLiff();await window.liff!.init({liffId:String(config.liffId??"")});if(!window.liff!.isLoggedIn()){window.liff!.login({redirectUri:location.href});return}const value=window.liff!.getAccessToken();if(!value)throw new Error("LINE認証を確認できませんでした");setToken(value);await load(value,month)}catch(e){setError(e instanceof Error?e.message:"ポイント履歴を開けませんでした");setLoading(false)}})()},[load]);
 const change=(next:string)=>{if(next>currentMonth()||loading)return;setMonth(next);if(token)void load(token,next)};
 return <main className="point-history-page"><header><a href="/"><ArrowLeft size={18}/>ポイントカードへ戻る</a><small>POINT HISTORY</small><h1>ポイント履歴</h1></header><section className="point-history-balance"><small>現在の保有ポイント</small><strong>{history?history.balance.toLocaleString("ja-JP"):"—"}<span> P</span></strong>{history&&<p>スマレジ最終取得：{new Date(history.syncedAt).toLocaleString("ja-JP")}</p>}</section><nav><button onClick={()=>change(moveMonth(month,-1))} disabled={loading}><ChevronLeft size={18}/></button><strong>{month.replace("-","年")}月</strong><button onClick={()=>change(moveMonth(month,1))} disabled={loading||month>=currentMonth()}><ChevronRight size={18}/></button></nav>{loading?<p className="point-history-state">ポイント履歴を読み込んでいます…</p>:error?<p className="point-history-state error">{error}</p>:history?.entries.length?<section className="point-history-list">{history.entries.map(item=><article key={item.id}><time>{new Date(item.occurredAt).toLocaleString("ja-JP",{month:"numeric",day:"numeric",hour:"2-digit",minute:"2-digit"})}</time><div><strong>{item.cancelled?"取消・返品":item.kind==="USE"?"ポイント利用":"お買い上げ"}</strong><small>{item.amount>0?`お会計 ¥${item.amount.toLocaleString("ja-JP")}`:"スマレジポイント処理"}</small></div><b className={item.delta>=0?"plus":"minus"}>{item.delta>=0?"+":""}{item.delta.toLocaleString("ja-JP")} P</b><small>利用後 {item.balanceAfter.toLocaleString("ja-JP")} P</small></article>)}</section>:<p className="point-history-state">この月のポイント利用履歴はありません</p>}<footer>購入・利用履歴はスマレジの確定データを表示しています。</footer></main>
}
