import { env } from "cloudflare:workers";
import { NextRequest,NextResponse } from "next/server";
function admin(request:NextRequest){const email=request.headers.get("oai-authenticated-user-email")?.toLowerCase(),allowed=((env as unknown as Record<string,string|undefined>).ADMIN_EMAILS??"").split(",").map(v=>v.trim().toLowerCase());return email&&allowed.includes(email)?email:null}
export async function GET(request:NextRequest){if(!admin(request))return NextResponse.json({error:"FORBIDDEN"},{status:403});const p=request.nextUrl.searchParams,q=(p.get("q")??"").trim().slice(0,80),like=`%${q}%`,status=(p.get("status")??"").trim(),rank=(p.get("rank")??"").trim(),resident=(p.get("resident")??"").trim(),sync=(p.get("sync")??"").trim(),tag=(p.get("tag")??"").trim().slice(0,80),tagLike=`%${tag}%`,source=(p.get("source")??"").trim().slice(0,80),sourceLike=`%${source}%`;
 const [rows,duplicates,stats]=await Promise.all([
 env.DB.prepare(`SELECT m.member_code AS memberCode,m.display_name AS displayName,m.line_display_name AS lineDisplayName,m.phone,m.status,m.created_at AS createdAt,m.acquisition_source AS acquisitionSource,m.legacy_tags AS legacyTags,s.status AS syncStatus,s.last_error AS syncError,r.current_rank AS currentRank,r.current_rate_percent AS pointRatePercent,r.qualifying_spend_excluding_tax AS qualifyingSpend,r.resident_plan_active AS residentPlanActive FROM members m LEFT JOIN member_registration_syncs s ON s.member_id=m.id LEFT JOIN member_rank_states r ON r.member_id=m.id WHERE (?='' OR m.member_code LIKE ? OR m.display_name LIKE ? OR m.line_display_name LIKE ? OR m.phone LIKE ? OR m.email LIKE ?) AND (?='' OR m.status=?) AND (?='' OR r.current_rank=?) AND (?='' OR CAST(COALESCE(r.resident_plan_active,0) AS TEXT)=?) AND (?='' OR COALESCE(s.status,'NONE')=?) AND (?='' OR COALESCE(m.legacy_tags,'') LIKE ?) AND (?='' OR COALESCE(m.acquisition_source,'') LIKE ?) ORDER BY m.created_at DESC LIMIT 500`).bind(q,like,like,like,like,like,status,status,rank,rank,resident,resident,sync,sync,tag,tagLike,source,sourceLike).all(),
 env.DB.prepare(`SELECT phone,COUNT(*) AS count FROM members WHERE phone<>'' GROUP BY phone HAVING COUNT(*)>1 ORDER BY count DESC LIMIT 50`).all(),
 env.DB.prepare(`SELECT COUNT(*) AS total,SUM(CASE WHEN status='ACTIVE' THEN 1 ELSE 0 END) AS active,SUM(CASE WHEN source_system='L_MEMBERS' THEN 1 ELSE 0 END) AS migrated,SUM(CASE WHEN EXISTS(SELECT 1 FROM identity_links i WHERE i.member_id=members.id AND i.provider='LINE' AND i.revoked_at IS NULL) THEN 1 ELSE 0 END) AS lineLinked FROM members`).first()
 ]);return NextResponse.json({members:rows.results,duplicates:duplicates.results,stats},{headers:{"Cache-Control":"no-store"}})}
export async function PATCH(request:NextRequest){const actor=admin(request);if(!actor)return NextResponse.json({error:"FORBIDDEN"},{status:403});const body=await request.json().catch(()=>null) as {memberCode?:string;status?:"ACTIVE"|"INACTIVE";action?:"RETRY_SYNC";requestId?:string}|null,memberCode=(body?.memberCode??"").trim().toUpperCase();if(!/^[A-Z0-9]{10}$/.test(memberCode)||!body?.requestId||(!body.action&&!["ACTIVE","INACTIVE"].includes(body?.status??"")))return NextResponse.json({error:"INVALID_REQUEST"},{status:400});const member=await env.DB.prepare("SELECT id,status FROM members WHERE member_code=?").bind(memberCode).first<{id:string;status:string}>();if(!member)return NextResponse.json({error:"MEMBER_NOT_FOUND"},{status:404});const now=Date.now();if(body.action==="RETRY_SYNC"){await env.DB.batch([env.DB.prepare("UPDATE member_registration_syncs SET status='PENDING',last_error=NULL,last_request_id=?,updated_at=? WHERE member_id=?").bind(body.requestId,now,member.id),env.DB.prepare("INSERT INTO member_registration_events (id,member_id,event_type,actor,details_json,created_at) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),member.id,"SMAREGI_SYNC_REQUEUED",actor,JSON.stringify({requestId:body.requestId}),now)]);return NextResponse.json({ok:true,memberCode,syncStatus:"PENDING"})}await env.DB.batch([env.DB.prepare("UPDATE members SET status=?,updated_at=? WHERE id=?").bind(body.status,now,member.id),env.DB.prepare("INSERT INTO member_registration_events (id,member_id,event_type,actor,details_json,created_at) VALUES (?,?,?,?,?,?)").bind(crypto.randomUUID(),member.id,"MEMBER_STATUS_CHANGED",actor,JSON.stringify({requestId:body.requestId,before:member.status,after:body.status}),now)]);return NextResponse.json({ok:true,memberCode,status:body.status})}
